(function(i){function l(a){var b,g,d,e,f,h,a=a||{};this.id=r++;this.options=$.extend(!0,{},c.options,a.options);d=a.geometry instanceof THREE.Geometry?a.geometry:typeof a.geometry==="string"?i.get_asset_data(a.geometry):new THREE.Geometry;f=i.ensure_not_array(a.material||a.materials);f instanceof THREE.Material!==!0&&(f=d.materials&&d.materials.length>0?new THREE.MeshFaceMaterial:new THREE.MeshLambertMaterial({vertexColors:THREE.VertexColors,shading:THREE.SmoothShading}));e=[f];if(d.materials&&d.materials.length>
0)for(b=0,g=d.materials.length;b<g;b++)e.push(d.materials[b]);for(b=0,g=e.length;b<g;b++){h=e[b];if(h.hasOwnProperty("morphTargets"))h.morphTargets=d.morphTargets&&d.morphTargets.length>0?!0:!1;if(a.hasOwnProperty("shading"))h.shading=a.shading;if(a.hasOwnProperty("side"))h.side=a.side;else if(a.doubleSided===!0)h.side=THREE.DoubleSide;else if(a.flipSided===!0)h.side=THREE.BackSide}THREE.Mesh.call(this,d,f);this.useQuaternion=!0;if(a.hasOwnProperty("rotation"))b=a.rotation,b instanceof THREE.Quaternion?
this.quaternion.copy(b):b instanceof THREE.Vector3?this.quaternion.setFromEuler(b):b instanceof THREE.Matrix4&&this.quaternion.setFromRotationMatrix(b);if(a.hasOwnProperty("position")&&a.position instanceof THREE.Vector3)b=a.position,this.position.copy(b);this.castShadow=typeof a.castShadow==="boolean"?a.castShadow:!1;this.receiveShadow=typeof a.receiveShadow==="boolean"?a.receiveShadow:!1;a.center===!0&&j.center(this);a.centerRotation===!0&&j.center_rotation(this);a.normalizeFaces===!0&&j.normalize_faces(this);
if(a.hasOwnProperty("physics"))this.rigidBody=new m.Instance(this,a.physics);this.actions=new n.Instance;this.actions.add(a.actions)}function s(a){var b,g;b=this.geometry;g=this.material;var d=this.children,e,f;typeof a==="undefined"&&(a=new c.Instance);if(a instanceof c.Instance){a.options=$.extend(!0,{},this.options);a.geometry=j.clone_geometry(b);a.material=g.clone();a.name=this.name;a.parent=this.parent;a.up.copy(this.up);a.position.copy(this.position);a.rotation instanceof THREE.Vector3&&a.rotation.copy(this.rotation);
a.eulerOrder=this.eulerOrder;a.scale.copy(this.scale);a.dynamic=this.dynamic;a.renderDepth=this.renderDepth;a.rotationAutoUpdate=this.rotationAutoUpdate;a.matrix.copy(this.matrix);a.matrixWorld.copy(this.matrixWorld);a.matrixRotationWorld.copy(this.matrixRotationWorld);a.matrixAutoUpdate=this.matrixAutoUpdate;a.matrixWorldNeedsUpdate=this.matrixWorldNeedsUpdate;a.quaternion.copy(this.quaternion);a.useQuaternion=this.useQuaternion;a.boundRadius=this.boundRadius;a.boundRadiusScale=this.boundRadiusScale;
a.visible=this.visible;a.castShadow=this.castShadow;a.receiveShadow=this.receiveShadow;a.frustumCulled=this.frustumCulled;if(this.hasOwnProperty("rigidBody"))a.rigidBody=this.rigidBody.clone(a);for(b=0,g=d.length;b<g;b++)e=d[b],e instanceof c.Instance?f=e.clone():e instanceof THREE.Object3D&&(f=THREE.SceneUtils.cloneObject(e)),a.add(f)}return a}function o(a,b){this.set_option_and_refresh("dynamic",a,b)}function p(a,b){this.set_option_and_refresh("intersectable",a,b)}function t(a,b,c){var d,e,f;if(this.options[a]!==
intersectable)f=this.parent,f instanceof THREE.Object3D&&f.remove(this);this.options[a]=b;if(c===!0){children=q.extract_children_from_objects(this);for(c=0,d=children.length;c<d;c++)e=this.children[c],e instanceof l?e.options[a]=b:e[a]=b}f instanceof THREE.Object3D&&f.add(this)}i.shared=i.shared||{};var c={},k,n,m,q,j,r=0;i.asset_register("js/kaiopua/core/Model.js",{data:c,requirements:["js/kaiopua/core/Morphs.js","js/kaiopua/core/Actions.js","js/kaiopua/physics/RigidBody.js","js/kaiopua/utils/SceneHelper.js",
"js/kaiopua/utils/ObjectHelper.js"],callbacksOnReqs:function(a,b,g,d,e){k=a;n=b;m=g;q=d;j=e;c.options={interactive:!1,dynamic:!1,intersectable:!0,actionTypes:{interactive:"action_interactive"},morphs:{duration:1E3}};c.Instance=l;c.Instance.prototype=new THREE.Mesh;c.Instance.prototype.constructor=c.Instance;c.Instance.prototype.clone=s;c.Instance.prototype.set_dynamic=o;c.Instance.prototype.set_intersectable=p;c.Instance.prototype.set_option_and_refresh=t;Object.defineProperty(c.Instance.prototype,
"interactive",{get:function(){return this.options.interactive},set:function(a){this.options.interactive=a}});Object.defineProperty(c.Instance.prototype,"dynamic",{get:function(){return this.options.dynamic||this.rigidBody&&this.rigidBody.dynamic},set:o});Object.defineProperty(c.Instance.prototype,"intersectable",{get:function(){return this.options.intersectable},set:p});Object.defineProperty(c.Instance.prototype,"gravityBody",{get:function(){return this.rigidBody?this.rigidBody.gravityBody:!1}});
Object.defineProperty(c.Instance.prototype,"geometry",{get:function(){return this._geometry},set:function(a){var b;if(a instanceof THREE.Geometry&&this._geometry!==a){this.morphs instanceof k.Instance&&this.morphs.clear_all();this._geometry=a;this._geometry.boundingSphere||this._geometry.computeBoundingSphere();this.boundRadius=this._geometry.boundingSphere.radius;if(this._geometry.morphTargets.length){this.morphTargetBase=-1;this.morphTargetForcedOrder=[];this.morphTargetInfluences=[];this.morphTargetDictionary=
{};for(a=0,b=this._geometry.morphTargets.length;a<b;a++)this.morphTargetInfluences.push(0),this.morphTargetDictionary[this._geometry.morphTargets[a].name]=a}this.morphs=new k.Instance(this,this.options.morphs)}}})},wait:!0})})(KAIOPUA);
