(function(d){function o(a,c,h){this.morphs=a;this.name=c;this.map=this.morphs.maps[this.name];this.options=$.extend(!0,this.options||{},b.options,h);this.prepare()}function p(a){if(this.cleared!==!0&&d.is_number(this.frame))if(this.options.direction===-1){if(this.frame<0)this.frame=this.map.length-1}else{if(this.frame>=this.map.length)this.frame=0}else this.frame=this.options.direction===-1?this.map.length-1:0;this.frameLast=d.is_number(this.frameLast)&&this.frameLast!==this.frame?this.frameLast:
-1;if(a!==!0)this.animating=this.clearing=!1,this.alternateTime=0;if(this.alternatingNeedsClear!==!1)this.alternating=this.alternatingNeedsClear=!1;this.recycle();return this}function q(){this.frameTimeDelta=this.framesUpdated=0;this.time=this.timeLast=this.timeStart=(new Date).getTime();return this}function r(a){var a=a||{},c,h=a.duration,b,e;if(d.is_number(h)&&this.durationOriginal!==h)c=this.options.duration,b=this.time-this.timeStart,e=b/c,b=this.map.length,this.timeStart+=c*e-h*e,c=this.frameTimeDelta/
(c/b),this.frameTimeDelta=h/b*c,this.durationOriginal=h;a.reverse===!0&&this.reverse_direction();if(a.clearOnly)a.clearOnly=d.to_array(a.clearOnly);if(a.clearExceptions)a.clearExceptions=d.to_array(a.clearExceptions);this.options=$.extend(this.options||{},a);return this}function s(a){if(this.clearing===!0)this.clearing=!1,this.recycle();this.change(a);if(this.options.solo===!0&&this.morphs.animatingNames.length>1){if(this.options.durationClear===!0)this.options.durationClear=this.get_frame_duration();
this.options.clearOnly?this.morphs.clear_only(this.options.clearOnly,{duration:this.options.durationClear}):(a=[this.name],this.options.clearExceptions&&(a=a.concat(this.options.clearExceptions)),this.alternating===!0&&a.push(this.options.alternate),this.morphs.clear_all({duration:this.options.durationClear},a))}if(this.animating!==!0&&typeof this.startTimeoutHandle==="undefined"&&typeof this.loopTimeoutHandle==="undefined"){this.cleared!==!1&&this.options.prepare!==!1&&this.prepare();if(d.is_number(this.options.startAt)&&
this.options.startAt>-1&&this.options.startAt<this.map.length)this.frame=this.options.startAt;if(this.options.startAtMax===!0)this.morphs.mesh.morphTargetInfluences[this.map[this.frame].index]=1,this.frameTimeDelta=this.get_frame_duration();a=this.options.startDelay===!0?Math.round(Math.random()*this.options.duration):d.is_number(this.options.startDelay)?this.options.startDelay:0;a>0?this.startTimeoutHandle=window.requestTimeout($.proxy(this.resume,this),a):this.resume()}return this}function t(){if(this.animating!==
!0)f.call(this),this.animating=!0,this.cleared=!1,m.signals.onGameUpdated.add(this.update,this);return this}function u(){var a,c,b=!1;this.options.interruptable=!0;if(this.clearing===!0)this.clear();else{this.options.reverseOnComplete===!0&&this.reverse_direction();this.options.loop!==!0&&(this.stop().prepare(),this.options.clearOnComplete===!0&&this.clear({duration:this.options.durationClear}));typeof this.options.oneComplete==="function"&&(this.options.oneComplete(),delete this.options.oneComplete);
if(typeof this.options.onComplete==="function")this.options.onComplete();a=this.options.alternate;if(typeof a==="string"&&a!==this.name&&(this.alternateDelay=this.options.alternateDelay,this.options.alternateDelayRandom&&(this.alternateDelay+=Math.round(Math.random()*this.options.alternateDelay)),this.alternateTime+=this.options.duration,this.alternateTime>=this.alternateDelay&&(this.alternateTime=0,c=d.index_of_value(this.morphs.names,a),c!==-1)))c=$.extend(!0,{},this.options.alternateParameters),
c.clearOnly=c.clearOnly||this.options.clearOnly,c.clearExceptions=c.clearExceptions||this.options.clearExceptions,b=!0,this.alternateLoopDelay=c.duration||0,this.morphs.play(a,c);this.alternating=b;if(this.options.loop===!0){a=void 0;a=this.options.duration*this.options.loopDelayPct*(this.options.loopDelayRandom===!0?Math.random():1);this.prepare(!0);if(this.alternating===!0)this.alternatingNeedsClear=!0,a+=this.alternateLoopDelay;n.call(this,a)}}}function n(a){f.call(this);this.options.loopChance<
1&&Math.random()>this.options.loopChance&&(a=Math.round(this.options.duration*(this.options.loopDelayRandom===!0?Math.random():1)));a>0?(this.stop(),this.loopTimeoutHandle=window.requestTimeout($.proxy(n,this),a)):this.resume();return this}function v(){f.call(this);this.animating=!1;m.signals.onGameUpdated.remove(this.update,this);return this}function w(a){if(this.options.interruptable!==!1&&(f.call(this),this.cleared!==!0))if(a=a||{},a=a.duration,d.is_number(a)&&a>0){if(this.clearing!==!0||this.durationClear!==
a)this.clearing=!0,this.durationClear=a,this.recycle().resume()}else if(this.reset(),typeof this.options.oneClear==="function"&&(this.options.oneClear(),delete this.options.oneClear),typeof this.options.onClear==="function")this.options.onClear();return this}function x(){var a,c,b=this.morphs.mesh.morphTargetInfluences,d=this.map;this.stop().prepare();for(a=0,c=d.length;a<c;a++)b[d[a].index]=0;this.cleared=!0;this.morphs.remove(this.name);return this}function y(a){var c=this.morphs.mesh,b=c.morphTargetInfluences,
d=this.map,e=this.options,f,l,i=d.length,j,g;this.timeLast=this.time;this.time+=a;f=this.time-this.timeStart;if(this.clearing===!0){c=this.durationClear;f/=c;e=a/c;for(a=0;a<i;a++)g=d[a].index,b[g]=k.clamp(b[g]-e,0,1)}else if(c=e.duration*Math.max(c.scale.x,c.scale.y,c.scale.z,0.5),f/=c,c=e.direction,l=e.interpolationDirection,j=this.get_frame_duration(),e=a/j*l,g=d[this.frame].index,this.frameTimeDelta+=a,this.frameTimeDelta>=j){this.framesUpdated++;this.frameTimeDelta=Math.max(0,this.frameTimeDelta-
j);b[g]=1;if(this.frameLast>-1)a=d[this.frameLast].index,b[a]=0;this.frameLast=this.frame;this.frame+=1*c;if(c===-1&&this.frame<0)this.frame=i-1;else if(c===1&&this.frame>i-1)this.frame=0;if(d.length===1)l===-1&&(b[g]=0),this.frameLast=-1,this.reverse_interpolation()}else if(b[g]=k.clamp(b[g]+e,0,1),this.frameLast>-1)a=d[this.frameLast].index,b[a]=k.clamp(b[a]-e,0,1);(f>=1||this.framesUpdated>=i)&&this.complete()}function z(){this.options.direction=-this.options.direction;if(this.map.length===1){if(this.options.direction===
-1&&this.morphs.mesh.morphTargetInfluences[this.map[0]]>0)this.options.interpolationDirection=-1;this.options.direction=1}return this}function A(){this.options.interpolationDirection=-this.options.interpolationDirection;return this}function B(){var a=this.morphs.mesh,b=this.options.duration;a instanceof THREE.Object3D&&(b*=Math.max(a.scale.x,a.scale.y,a.scale.z,0.5));return b/this.map.length}function f(){typeof this.loopTimeoutHandle!=="undefined"&&(window.clearRequestTimeout(this.loopTimeoutHandle),
delete this.loopTimeoutHandle);typeof this.startTimeoutHandle!=="undefined"&&(window.clearRequestTimeout(this.startTimeoutHandle),delete this.startTimeoutHandle);return this}var m=d.shared=d.shared||{},b={},k;d.asset_register("js/kaiopua/core/MorphAnimator.js",{data:b,requirements:["js/kaiopua/utils/MathHelper.js"],callbacksOnReqs:function(a){k=a;b.options={duration:1E3,durationClear:125,direction:1,interpolationDirection:1,loop:!1,loopDelayPct:0,loopDelayRandom:!1,loopChance:1,reverseOnComplete:!1,
clearOnComplete:!0,startDelay:0,startAt:-1,startAtMax:!1,alternate:!1,alternateDelay:0,alternateDelayRandom:!0,solo:!1,clearOnly:!1,clearExceptions:!1,interruptable:!0,prepare:!0};b.Instance=o;b.Instance.prototype.constructor=b.Instance;b.Instance.prototype.prepare=p;b.Instance.prototype.recycle=q;b.Instance.prototype.change=r;b.Instance.prototype.play=s;b.Instance.prototype.resume=t;b.Instance.prototype.complete=u;b.Instance.prototype.stop=v;b.Instance.prototype.clear=w;b.Instance.prototype.reset=
x;b.Instance.prototype.update=y;b.Instance.prototype.reverse_direction=z;b.Instance.prototype.reverse_interpolation=A;b.Instance.prototype.get_frame_duration=B},wait:!0})})(KAIOPUA);
