(function(e){function m(a){a=a||{};this.options=$.extend(!0,{},b.options,a.options);this.showing=!1;this.$element=$(this.options.template);this.$inner=this.$element.find(this.options.inner);if(this.$inner.length===0)this.$inner=this.$element;this.$container=$(a.container||a.$container||d.domElements.$uiOverGame||d.domElements.$uiInGame||d.domElements.$game);this.content(a.content);this.reset()}function n(){this.position={top:0,left:0};this.positionBase={top:0,left:0};this.offset={top:0,left:0}}function o(a){return typeof a===
"string"?(this.$inner.html(a),this.update_placement(this.placementCurrent,!0).update_position(),this.$element.css(this.position),this):this.$inner.html()}function p(a){if(typeof a!=="undefined")this.options=$.extend(!0,this.options,a);if(this.showing!==!0)this.showing=!0,this.$element.appendTo(this.$container).addClass("in"),this.options.animate===!0&&e.dom_fade({element:this.$element,duration:this.options.animateDuration,opacity:1,initHidden:!0}),this.update_placement(this.options.placement,!0);
return this}function q(){var a;if(this.showing!==!1){this.showing=!1;a=this.options.oneHidden;typeof a==="function"&&(delete this.options.oneHidden,a());if(typeof this.options.onHidden==="function")this.options.onHidden();this.options.animate===!0?e.dom_fade({element:this.$element,duration:this.options.animateDuration,callback:$.proxy(this.hide_complete,this)}):this.hide_complete()}else this.hide_complete();return this}function r(){this.$element.removeClass("in").remove();return this}function s(){if(this.showing!==
!1){this.showing=!1;oneRemoved=this.options.oneRemoved;typeof oneRemoved==="function"&&(delete this.options.oneRemoved,oneRemoved());if(typeof this.options.onRemoved==="function")this.options.onRemoved();this.options.animate===!0?e.dom_fade({element:this.$element,duration:this.options.animateDuration,callback:$.proxy(this.remove_complete,this)}):this.remove_complete()}else this.remove_complete();return this}function t(){this.$element.removeClass("in").remove();this.reset();return this}function u(a,
c){var f,b,d,g,h;if(e.is_number(a)&&this.positionBase.left!==a)d=!0,this.positionBase.left=a;if(e.is_number(c)&&this.positionBase.top!==c)d=!0,this.positionBase.top=c;if(d===!0){this.options.checkBoundsClockwise!==!0?(d=k,f=j):(d=i,f=l);g=this.options.placement;h=f[g];for(f=0,b=d.length;f<b;f++){g=d[h];this.placementCurrent!==g&&this.update_placement(g);this.update_position();if(this.check_bounds())break;h++;h===b&&(h=0)}this.$element.css(this.position)}return this}function v(){if(this.position.top<
0)return!1;else if(this.position.top+this.elementHeight>d.screenViewableHeight)return!1;if(this.position.left<0)return!1;else if(this.position.left+this.elementWidth>d.screenViewableWidth)return!1;return!0}function w(a,c){if(this.placementCurrent!==a||c===!0)if(typeof this.placementCurrent==="string"&&this.$element.removeClass(this.placementCurrent),typeof a==="string")this.$element.addClass(a),this.placementCurrent=a,this.elementWidth=this.$element.outerWidth(!0),this.elementHeight=this.$element.outerHeight(!0);
return this}function x(){var a=this.placementCurrent;if(a==="top")this.position.left=this.positionBase.left-this.elementWidth*0.5+this.offset.left,this.position.top=this.positionBase.top-this.elementHeight+this.offset.top;else if(a==="topright")this.position.left=Math.max(this.positionBase.left+this.offset.left,0),this.position.top=this.positionBase.top-this.elementHeight+this.offset.top;else if(a==="right")this.position.left=this.positionBase.left+this.offset.left,this.position.top=this.positionBase.top-
this.elementHeight*0.5+this.offset.top;else if(a==="bottomright")this.position.left=Math.max(this.positionBase.left+this.offset.left,0),this.position.top=this.positionBase.top+this.offset.top;else if(a==="bottom")this.position.left=this.positionBase.left-this.elementWidth*0.5+this.offset.left,this.position.top=this.positionBase.top+this.offset.top;else if(a==="bottomleft")this.position.left=Math.min(this.positionBase.left-this.elementWidth+this.offset.left,d.screenViewableWidth-this.elementWidth),
this.position.top=this.positionBase.top+this.offset.top;else if(a==="left")this.position.left=this.positionBase.left-this.elementWidth+this.offset.left,this.position.top=this.positionBase.top-this.elementHeight*0.5+this.offset.top;else if(a==="topleft")this.position.left=Math.min(this.positionBase.left-this.elementWidth+this.offset.left,d.screenViewableWidth-this.elementWidth),this.position.top=this.positionBase.top-this.elementHeight+this.offset.top;return this}function y(a){var c=a.x,b=a.y,a=this.options.normalThreshold;
c<0?b<0?(c-=b,this.options.placement=c<-a?"left":c>a?"top":"topleft",this.options.checkBoundsClockwise=!1):(c=b+c,this.options.placement=c<-a?"left":c>a?"bottom":"bottomleft",this.options.checkBoundsClockwise=!0):b<0?(c+=b,this.options.placement=c<-a?"top":c>a?"right":"topright",this.options.checkBoundsClockwise=!0):(c-=b,this.options.placement=c<-a?"bottom":c>a?"right":"bottomright",this.options.checkBoundsClockwise=!1);return this}var d=e.shared=e.shared||{},b={},i="top,topright,right,bottomright,bottom,bottomleft,left,topleft".split(","),
k=[],l={},j={};(function(){var a,c,d;for(a=0,c=i.length;a<c;a++)d=i[a],l[d]=a,j[d]=i.length-1-a,k[j[d]]=d;b.options={placement:"top",template:"<div></div>",animate:!1,checkBoundsClockwise:!0,normalThreshold:0.5};b.Instance=m;b.Instance.prototype.constructor=b.Instance;b.Instance.prototype.reset=n;b.Instance.prototype.content=o;b.Instance.prototype.show=p;b.Instance.prototype.hide=q;b.Instance.prototype.hide_complete=r;b.Instance.prototype.remove=s;b.Instance.prototype.remove_complete=t;b.Instance.prototype.reposition=
u;b.Instance.prototype.check_bounds=v;b.Instance.prototype.update_placement=w;b.Instance.prototype.update_position=x;b.Instance.prototype.normal_to_placement=y})();e.asset_register("js/kaiopua/ui/Popover.js",{data:b})})(KAIOPUA);
