(function(b){function y(){$().add(a.domElements.$workerProgressBarStarted).add(a.domElements.$workerProgressBarCompleted).children(".work-task").remove()}function z(d){typeof f!=="undefined"&&(window.clearTimeout(f),f=void 0);b.dom_collapse({element:a.domElements.$worker,show:!0});a.domElements.$workerProgressBarStarted.append($('<img src="img/bar_vertical_rev_64.png" id="'+d+'" class="iconk-tiny-widthFollow-tight work-task">'))}function A(b){var c=b.replace(/([ #;?&,.+*~\':"!^$[\]()=>|\/@])/g,"\\$1");
a.domElements.$workerProgressBarStarted.find("#"+c).remove();a.domElements.$workerProgressBarCompleted.append($('<img src="img/bar_vertical_rev_64.png" id="'+b+'" class="iconk-tiny-widthFollow-tight work-task">'))}function B(){typeof f!=="undefined"&&(window.clearTimeout(f),f=void 0);f=window.setTimeout(function(){b.dom_collapse({element:a.domElements.$worker})},C)}function t(){if(b.playable===!0&&a.supports.webGL===!0){a.domElements.$gameState.find(".state-loading").removeClass("active");b.ready===
!0?a.domElements.$gameState.find(".state-usable").removeClass("active").end().find(".state-ready").addClass("active"):a.domElements.$gameState.find(".state-ready").removeClass("active").end().find(".state-usable").addClass("active");var d,c;d=$().add(a.domElements.$buttonsGameStart).add(a.domElements.$buttonsGameStop);c=d.closest("li");c.length===0&&(c=d);c.removeClass("disabled dim");a.domElements.$buttonsGameStart.tooltip("destroy").on("tap",b.start)}else a.domElements.$gameState.find(".state-loading").addClass("active").end().find(".state-usable").removeClass("active").end().find(".state-ready").removeClass("active"),
u()}function u(){var b,c;b=$().add(a.domElements.$buttonsGameStart).add(a.domElements.$buttonsGameStop);c=b.closest("li");c.length===0&&(c=b);c.addClass("disabled dim");if(a.supports.webGL!==!0){a.domElements.$buttonsGameStart.tooltip("destroy").tooltip({title:"We need WebGL!",trigger:"manual",placement:"left",selector:a.domElements.$buttonsGameStart}).tooltip("show");c=a.domElements.$buttonsGameStart.closest("li");if(c.length===0)c=a.domElements.$buttonsGameStart;b=a.domElements.$buttonsGameStart.data("tooltip").$tip;
b.css({top:(c.height()-b.height())*0.5,left:-(b.outerWidth()+5)}).appendTo(c)}}function D(){j()}function E(){}function F(){}function G(){b.dom_fade({element:a.domElements.$navMain,opacity:1})}function r(){b.started!==!0&&(a.domElements.$uiGameDimmer.off(".resume"),b.dom_fade({element:a.domElements.$uiGameDimmer}));b.dom_fade({element:a.domElements.$navMainAlt,duration:0});a.domElements.$menuToggleDefault.length>0?a.domElements.$menuToggleDefault.trigger("tap"):a.domElements.$menuDefault.length>0&&
a.domElements.$menuDefault.trigger("open")}function H(a,c,k){k==="up"&&c==="escape"&&(b.started===!0&&b.paused===!0||s===!0?o():m())}function m(a,c){b.started===!0?b.paused!==!0?b.pause(a,c):p(a,c):p(a,c)}function p(d,c){var k=c instanceof jQuery&&!a.domElements.$menuDefault.is(c);s=!0;b.dom_fade({element:a.domElements.$buttonsGamePause,duration:0,invisible:!0});b.dom_fade({element:a.domElements.$buttonsGameResume,duration:0,invisible:!0});if(d===!0)b.dom_fade({element:a.domElements.$uiBlocker,opacity:0.9});
else if(k===!0?(n=c,a.domElements.$social.addClass("blocking"),a.domElements.$sponsorsLite.addClass("hidden"),b.dom_fade({element:a.domElements.$navMainAlt,opacity:1})):(n=void 0,r()),b.started===!0||k===!0)b.dom_fade({element:a.domElements.$uiGameDimmer,opacity:0.9}),a.domElements.$uiGameDimmer.on("tap.resume",j),b.dom_fade({element:a.domElements.$buttonsGameResume,opacity:1})}function o(){b.started===!0&&typeof n==="undefined"?b.resume():j()}function j(d){s=!1;b.dom_fade({element:a.domElements.$uiBlocker});
d!==!0&&(typeof n!=="undefined"?(a.domElements.$social.removeClass("blocking"),a.domElements.$sponsorsLite.removeClass("hidden"),r()):(a.domElements.$uiGameDimmer.off(".resume"),b.dom_fade({element:a.domElements.$uiGameDimmer}),b.started===!0?(q.clear(a.domElements.$uiOutGame),b.dom_fade({element:a.domElements.$uiOutGame}),b.dom_fade({element:a.domElements.$buttonsGamePause,opacity:1})):r()));b.started===!0&&b.paused!==!0?b.dom_fade({element:a.domElements.$buttonsGamePause,opacity:1}):typeof n!==
"undefined"?b.dom_fade({element:a.domElements.$buttonsGameResume,opacity:1}):b.dom_fade({element:a.domElements.$buttonsGameResume,duration:0,invisible:!0})}function v(d,c,k){w();if(b.index_of_value(a.errorTypes,d)===-1)d=a.errorTypeGeneral;if(b.index_of_value(a.errorTypesOnlyOnce,d)!==-1&&window.localStorage)if(typeof window.localStorage[d]!=="undefined")return;else window.localStorage[d]="shown";g=a.domElements["$"+a.errorString+d];d===a.errorTypeGeneral&&(typeof c==="string"&&(index=c.search(/\/(?![\s\S]*\/)/),
index!==-1&&(c=c.slice(index+1)),index=c.search(/\?(?![\s\S]*\?)/),index!==-1&&(c=c.slice(0,index))),g.find("#errorMessage").html(v),g.find("#errorFile").html(c),g.find("#errorLine").html(k));m(!0);b.dom_collapse({element:g,show:!0});if(b.started!==!0)$(window).one("click.errorclear",function(){w();o()})}function w(){typeof g!=="undefined"&&b.dom_collapse({element:g})}function I(){a.domElements.$uiOutGame[0].scrollHeight>a.screenViewableHeight&&a.domElements.$menusInner.css("padding-left",$.scrollbarWidth())}
var a=b.shared=b.shared||{},h={},q,s=!1,x=!1,C=1E3,f,n,g;b.asset_register("js/kaiopua/ui/UI.js",{data:h,requirements:["js/kaiopua/ui/UIQueue.js","js/lib/jquery.scrollbarwidth.min.js","js/lib/jquery.multi-sticky.js"],callbacksOnReqs:function(d){q=d;h.pause=p;h.resume=j;h.resize=I;h.error=v;Object.defineProperty(h,"ready",{get:function(){return x}});a.domElements=a.domElements||{};a.domElements.cloneables=a.domElements.cloneables||{};a.domElements.$uiGameDimmer=$("#uiGameDimmer");a.domElements.$uiBlocker=
$("#uiBlocker");a.domElements.$ui=$("#ui");a.domElements.$uiInGame=$("#uiInGame");a.domElements.$uiOverGame=$("#uiOverGame");a.domElements.$uiOutGame=$("#uiOutGame");a.domElements.$uiOverlay=$("#uiOverlay");a.domElements.$autoCenter=$(".auto-center");a.domElements.$autoCenterVertical=$(".auto-center-vertical");a.domElements.$autoCenterHorizontal=$(".auto-center-horizontal");a.domElements.$preloader=$("#preloader");a.domElements.$statusInactive=$("#statusInactive");a.domElements.$statusActive=$("#statusActive");
a.domElements.$statusItems=$(".status-item");a.domElements.$worker=$("#worker");a.domElements.$workerProgressBarStarted=$("#workerProgressBarStarted");a.domElements.$workerProgressBarCompleted=$("#workerProgressBarCompleted");a.domElements.$uiState=$("#uiState");a.domElements.$gameState=$("#gameState");a.domElements.$dropdowns=$(".dropdown");a.domElements.$tabToggles=$(".tab-toggles").find('[href^="#"]').not(".tab-toggle-empty");a.domElements.$stickied=$(".is-sticky");a.domElements.$actionsActive=
$("#actionsActive");a.domElements.$actionsInactive=$("#actionsInactive");a.domElements.$actionItems=$(".action-item");a.domElements.$menus=$(".menu");a.domElements.$menuDefault=$("#menuMain");a.domElements.$menusInner=$();a.domElements.$menuToggles=$();a.domElements.$menuToggleDefault=$();a.domElements.$menuActive=$("#menuActive");a.domElements.$menuInactive=$("#menuInactive");a.domElements.$navbars=$(".navbar, .subnavbar");a.domElements.$navMenus=$("#navMenus");a.domElements.$navMain=$("#navMain");
a.domElements.$navMainAlt=$("#navMainAlt");a.domElements.$social=$("#social");a.domElements.$sponsors=$("#sponsors");a.domElements.$sponsorsLite=$("#sponsorsLite");a.domElements.$buttonsGameStart=$(".game-start");a.domElements.$buttonsGameStop=$(".game-stop");a.domElements.$buttonsGamePause=$(".game-pause");a.domElements.$buttonsGameResume=$(".game-resume");$("img").attr("draggable",!1);$('a[href^="#"]').each(function(){var a=$(this),b=$(a.data("section")),d=$(a.attr("href"));a.attr("onclick","return false;");
if(b.length>0||d.length>0)a.on("tap",function(){(b[0]||d[0]).scrollIntoView(!0)})});a.supports.pointerEvents===!1&&b.dom_ignore_pointer($(".ignore-pointer, .disabled"),!0);a.domElements=a.domElements||{};for(i=0,l=a.errorTypes.length;i<l;i++)errorName=a.errorString+a.errorTypes[i],a.domElements["$"+errorName]=$("#"+errorName);a.domElements.$worker.on("hidden.reset",function(){b.worker_reset()});a.domElements.$statusItems.each(function(){var c=$(this);c.is(".hidden, .collapsed")&&a.domElements.$statusInactive.append(c)}).on("show.active",
function(){a.domElements.$statusActive.append(this)}).on("hidden.active",function(){a.domElements.$statusInactive.append(this)});a.domElements.$actionItems.each(function(){var c=$(this);c.parent().is(a.domElements.$actionsActive)&&c.is(".hidden, .collapsed")&&a.domElements.$actionsInactive.append(c)}).on("show.active",function(){a.domElements.$actionsActive.append(this)}).on("hidden.active",function(){a.domElements.$actionsInactive.append(this)});a.domElements.$dropdowns.each(function(){var a=$(this);
a.find(".dropdown-menu a").each(function(){var b=$(this);b.on("tap",function(){b.parent().removeClass("active");a.removeClass("open")})})});a.domElements.$navbars.each(function(){var a=$(this),b=a.find('[data-toggle="collapse"]'),a=a.find(".nav-collapse");b.length>0&&a.length>0&&a.find("a").each(function(){$(this).on("tap",function(){b.is(".collapsed")!==!0&&b.trigger("click")})})});a.domElements.$stickied.each(function(){var b=$(this),d=$(b.data("relative")),e=$(b.data("target"));if(e.length===0)e=
a.domElements.$uiOutGame;b.removeClass("is-sticky").sticky({topSpacing:function(){return d.offset().top+d.outerHeight(!0)},scrollTarget:e,handlePosition:!1})});a.domElements.$menus.each(function(){var c=$(this),d=c.find(".menu-inner"),e=a.domElements.$tabToggles.filter('[href="#'+c.attr("id")+'"]'),f,g,h,j;c.data("$inner",d);c.data("$toggle",e);c.data("scrollTop",0);a.domElements.$menusInner=a.domElements.$menusInner.add(d);f=function(){m(!1,c);e.length>0&&e.closest("li").addClass("active");c.addClass("active");
b.dom_fade({element:c,opacity:1});$(window).trigger("resize");a.domElements.$uiOutGame.scrollTop(c.data("scrollTop"))};g=function(){c.data("scrollTop",a.domElements.$uiOutGame.scrollTop());e.length>0&&e.closest("li").removeClass("active");c.removeClass("active");b.dom_fade({element:c,duration:0})};h=function(){m(!1,c)};j=function(){o()};d=function(){c.is(".active")===!0?c.trigger("close"):c.trigger("open")};c.on("open",function(){q.add({element:c,container:a.domElements.$uiOutGame,activate:f,deactivate:g,
first:h,last:j})}).on("close",function(){q.remove(c)}).on("toggle",d);if(e.length>0)e.data("$menu",c),a.domElements.$menuToggles=a.domElements.$menuToggles.add(e),e.on("tap",d);if(c.is(".active")===!0)a.domElements.$menuDefault=c,a.domElements.$menuToggleDefault=e});a.domElements.$sponsors.length>0&&a.domElements.$sponsorsLite.length>0&&a.domElements.$sponsorsLite.html(a.domElements.$sponsors.clone().html());a.domElements.$buttonsGameStop.on("tap",b.stop);a.domElements.$buttonsGamePause.on("tap",
m);a.domElements.$buttonsGameResume.on("tap",o);a.signals.onGameInput.add(H);a.signals.onWorkerReset.add(y);a.signals.onWorkerTaskStarted.add(z);a.signals.onWorkerTaskCompleted.add(A);a.signals.onWorkerTasksCompleted.add(B);a.signals.onGamePlayable.add(t);a.signals.onGameReadyChange.add(t);a.signals.onGameStarted.add(D);a.signals.onGameStartedCompleted.add(E);a.signals.onGameStopped.add(F);a.signals.onGameStoppedCompleted.add(G);a.signals.onGamePaused.add(p);a.signals.onGameResumed.add(j);x=!0;a.domElements.$uiState.find(".state-loading").removeClass("active").end().find(".state-usable").removeClass("active").end().find(".state-ready").addClass("active");
$(window).trigger("resize");a.domElements.$menuDefault.trigger("open");b.dom_fade({element:a.domElements.$preloader,duration:0});b.dom_fade({element:a.domElements.$uiGameDimmer});b.dom_fade({element:a.domElements.$navMain,opacity:1});u()},wait:!0})})(KAIOPUA);
