(function(b){function u(){$().add(a.domElements.$workerProgressBarStarted).add(a.domElements.$workerProgressBarCompleted).children(".work-task").remove()}function v(d){typeof e!=="undefined"&&(window.clearTimeout(e),e=void 0);k(!0);b.dom_collapse({element:a.domElements.$worker,show:!0});a.domElements.$workerProgressBarStarted.append($('<img src="img/bar_vertical_color_64.png" id="'+d+'" class="iconk-tiny iconk-widthFollow iconk-tight work-task">'))}function w(b){var c=b.replace(/([ #;?&,.+*~\':"!^$[\]()=>|\/@])/g,
"\\$1");a.domElements.$workerProgressBarStarted.find("#"+c).remove();a.domElements.$workerProgressBarCompleted.append($('<img src="img/bar_vertical_rev_64.png" id="'+b+'" class="iconk-tiny iconk-widthFollow iconk-tight work-task">'))}function x(){typeof e!=="undefined"&&(window.clearTimeout(e),e=void 0);e=window.setTimeout(function(){b.dom_collapse({element:a.domElements.$worker,callback:function(){n()}})},y)}function z(){var d,c;b.dom_fade({element:a.domElements.$preloader,duration:0});b.dom_fade({element:a.domElements.$navMain,
opacity:1});b.dom_fade({element:a.domElements.$uiGameDimmer});if(a.supports.webGL===!0)a.domElements.$buttonsGameStart.on("tap",b.start),a.domElements.$buttonsGameStop.on("tap",b.stop);else{d=$().add(a.domElements.$buttonsGameStart).add(a.domElements.$buttonsGameStop);c=d.closest("li");c.length===0&&(c=d);c.addClass("disabled dim");a.domElements.$buttonsGameStart.tooltip({title:"We need WebGL!",trigger:"manual",placement:"left",selector:a.domElements.$buttonsGameStart}).tooltip("show");c=a.domElements.$buttonsGameStart.closest("li");
if(c.length===0)c=a.domElements.$buttonsGameStart;d=a.domElements.$buttonsGameStart.data("tooltip").$tip;d.css({top:(c.height()-d.height())*0.5,left:-(d.outerWidth()+5)}).appendTo(c)}}function A(){h()}function B(){}function C(){}function D(){b.dom_fade({element:a.domElements.$navMain,opacity:1})}function r(){a.domElements.$uiGameDimmer.off(".resume");b.dom_fade({element:a.domElements.$uiGameDimmer});a.domElements.$menuToggleDefault.length>0?a.domElements.$menuToggleDefault.trigger("tap"):a.domElements.$menuDefault.length>
0&&a.domElements.$menuDefault.trigger("open")}function E(a,c,m){m==="up"&&c==="escape"&&(b.started===!0&&b.paused===!0||p===!0?n():k())}function k(a,c){b.started===!0?b.pause(a,c):q(a,c)}function q(d,c){var m=c instanceof jQuery&&!a.domElements.$menuDefault.is(c);p=!0;b.dom_fade({element:a.domElements.$buttonsGamePause,duration:0});b.dom_fade({element:a.domElements.$buttonsGameResume,duration:0});if(d===!0)b.dom_fade({element:a.domElements.$uiBlocker,opacity:0.9});else if(m!==!0&&r(),b.started===
!0||m===!0)b.dom_fade({element:a.domElements.$uiGameDimmer,opacity:0.9}),a.domElements.$uiGameDimmer.on("tap.resume",h),b.dom_fade({element:a.domElements.$buttonsGameResume,opacity:1})}function n(){b.started===!0?b.resume():h()}function h(d){p=!1;b.dom_fade({element:a.domElements.$uiBlocker});d!==!0&&(a.domElements.$uiGameDimmer.off(".resume"),b.dom_fade({element:a.domElements.$uiGameDimmer}),b.started===!0?o.clear(a.domElements.$uiOutGame):r());b.dom_fade({element:a.domElements.$buttonsGameResume,
duration:0});b.started!==!0?(b.dom_fade({element:a.domElements.$buttonsGamePause,duration:0}),a.domElements.$menuDefault.is(".active")||b.dom_fade({element:a.domElements.$buttonsGameResume,opacity:1})):b.dom_fade({element:a.domElements.$buttonsGamePause,opacity:1})}function s(d,c,m){t();if(b.index_of_value(a.errorTypes,d)===-1)d=a.errorTypeGeneral;if(b.index_of_value(a.errorTypesOnlyOnce,d)!==-1&&window.localStorage)if(typeof window.localStorage[d]!=="undefined")return;else window.localStorage[d]=
"shown";f=a.domElements["$"+a.errorString+d];d===a.errorTypeGeneral&&(typeof c==="string"&&(index=c.search(/\/(?![\s\S]*\/)/),index!==-1&&(c=c.slice(index+1)),index=c.search(/\?(?![\s\S]*\?)/),index!==-1&&(c=c.slice(0,index))),f.find("#errorMessage").html(s),f.find("#errorFile").html(c),f.find("#errorLine").html(m));k(!0);b.dom_collapse({element:f,show:!0});if(b.started!==!0)$(window).one("click.errorclear",function(){t();n()})}function t(){typeof f!=="undefined"&&b.dom_collapse({element:f})}function F(){var b=
a.domElements.$buttonsGamePauseMain.hasClass("hidden");b&&a.domElements.$buttonsGamePauseMain.removeClass("hidden");a.domElements.$buttonsGameResumeMain.css({top:a.domElements.$buttonsGamePauseMain.position().top,left:a.domElements.$buttonsGamePauseMain.position().left});b&&a.domElements.$buttonsGamePauseMain.addClass("hidden");a.domElements.$uiOutGame[0].scrollHeight>a.screenViewableHeight&&a.domElements.$menusInner.css("padding-left",$.scrollbarWidth())}var a=b.shared=b.shared||{},j={},o,p=!1,y=
1E3,e,f;b.asset_register("js/kaiopua/ui/UI.js",{data:j,requirements:["js/kaiopua/ui/UIQueue.js","js/lib/jquery.scrollbarwidth.min.js","js/lib/jquery.multi-sticky.js"],callbacksOnReqs:function(d){o=d;j.pause=q;j.resume=h;j.resize=F;j.error=s;a.domElements=a.domElements||{};a.domElements.cloneables=a.domElements.cloneables||{};a.domElements.$uiGameDimmer=$("#uiGameDimmer");a.domElements.$uiBlocker=$("#uiBlocker");a.domElements.$ui=$("#ui");a.domElements.$uiInGame=$("#uiInGame");a.domElements.$uiOverGame=
$("#uiOverGame");a.domElements.$uiOutGame=$("#uiOutGame");a.domElements.$uiOverlay=$("#uiOverlay");a.domElements.$uiHeader=$("#uiHeader");a.domElements.$uiFooter=$("#uiFooter");a.domElements.$uiSidebarLeft=$("#uiSidebarLeft");a.domElements.$uiSidebarRight=$("#uiSidebarRight");a.domElements.$autoCenter=$(".auto-center");a.domElements.$autoCenterVertical=$(".auto-center-vertical");a.domElements.$autoCenterHorizontal=$(".auto-center-horizontal");a.domElements.$preloader=$("#preloader");a.domElements.$statusInactive=
$("#statusInactive");a.domElements.$statusActive=$("#statusActive");a.domElements.$statusItems=$(".status-item");a.domElements.$worker=$("#worker");a.domElements.$workerProgressBarStarted=$("#workerProgressBarStarted");a.domElements.$workerProgressBarCompleted=$("#workerProgressBarCompleted");a.domElements.$dropdowns=$(".dropdown");a.domElements.$tabToggles=$(".tab-toggles").find('[href^="#"]').not(".tab-toggle-empty");a.domElements.$stickied=$(".is-sticky");a.domElements.$actionsActive=$("#actionsActive");
a.domElements.$actionsInactive=$("#actionsInactive");a.domElements.$actionItems=$(".action-item");a.domElements.$menus=$(".menu");a.domElements.$menuDefault=$("#menuMain");a.domElements.$menusInner=$();a.domElements.$menuToggles=$();a.domElements.$menuToggleDefault=$();a.domElements.$menuActive=$("#menuActive");a.domElements.$menuInactive=$("#menuInactive");a.domElements.$navbars=$(".navbar, .subnavbar");a.domElements.$navMenus=$("#navMenus");a.domElements.$navMain=$("#navMain");a.domElements.$buttonsGameStart=
$(".game-start");a.domElements.$buttonsGameStop=$(".game-stop");a.domElements.$buttonsGamePause=$(".game-pause");a.domElements.$buttonsGameResume=$(".game-resume");a.domElements.$buttonsGamePauseMain=$("#gamePauseMain");a.domElements.$buttonsGameResumeMain=$("#gameResumeMain");$("img").attr("draggable",!1);$('a[href^="#"]').each(function(){var a=$(this),b=$(a.data("section")),d=$(a.attr("href"));a.attr("onclick","return false;");if(b.length>0||d.length>0)a.on("tap",function(){(b[0]||d[0]).scrollIntoView(!0)})});
a.supports.pointerEvents===!1&&b.dom_ignore_pointer($(".ignore-pointer, .disabled"),!0);a.domElements=a.domElements||{};for(i=0,l=a.errorTypes.length;i<l;i++)errorName=a.errorString+a.errorTypes[i],a.domElements["$"+errorName]=$("#"+errorName);a.domElements.$worker.on("hidden.reset",function(){b.worker_reset()});a.domElements.$statusItems.each(function(){var c=$(this);c.is(".hidden, .collapsed")&&a.domElements.$statusInactive.append(c)}).on("show.active",function(){a.domElements.$statusActive.append(this)}).on("hidden.active",
function(){a.domElements.$statusInactive.append(this)});a.domElements.$actionItems.each(function(){var c=$(this);c.parent().is(a.domElements.$actionsActive)&&c.is(".hidden, .collapsed")&&a.domElements.$actionsInactive.append(c)}).on("show.active",function(){a.domElements.$actionsActive.append(this)}).on("hidden.active",function(){a.domElements.$actionsInactive.append(this)});a.domElements.$dropdowns.each(function(){var a=$(this);a.find(".dropdown-menu a").each(function(){var b=$(this);b.on("tap",
function(){b.parent().removeClass("active");a.removeClass("open")})})});a.domElements.$navbars.each(function(){var a=$(this),b=a.find('[data-toggle="collapse"]'),a=a.find(".nav-collapse");b.length>0&&a.length>0&&a.find("a").each(function(){$(this).on("tap",function(){b.is(".collapsed")!==!0&&b.trigger("click")})})});a.domElements.$stickied.each(function(){var c=$(this),b=$(c.data("relative")),d=$(c.data("target"));if(b.length===0)b=a.domElements.$uiHeader;if(d.length===0)d=a.domElements.$uiOutGame;
c.removeClass("is-sticky").sticky({topSpacing:function(){return b.offset().top+b.outerHeight(!0)},scrollTarget:d,handlePosition:!1})});a.domElements.$menus.each(function(){var c=$(this),d=c.find(".menu-inner"),g=a.domElements.$tabToggles.filter('[href="#'+c.attr("id")+'"]'),e,f,h,j;c.data("$inner",d);c.data("$toggle",g);c.data("scrollTop",0);a.domElements.$menusInner=a.domElements.$menusInner.add(d);e=function(){k(!1,c);g.length>0&&g.closest("li").addClass("active");c.addClass("active");b.dom_fade({element:c,
opacity:1});$(window).trigger("resize");a.domElements.$uiOutGame.scrollTop(c.data("scrollTop"))};f=function(){c.data("scrollTop",a.domElements.$uiOutGame.scrollTop());g.length>0&&g.closest("li").removeClass("active");c.removeClass("active");b.dom_fade({element:c,duration:0})};h=function(){k(!1,c)};j=function(){b.dom_fade({element:a.domElements.$uiOutGame});n()};d=function(){c.is(".active")===!0?c.trigger("close"):c.trigger("open")};c.on("open",function(){o.add({element:c,container:a.domElements.$uiOutGame,
activate:e,deactivate:f,first:h,last:j})}).on("close",function(){o.remove(c)}).on("toggle",d);if(g.length>0)g.data("$menu",c),a.domElements.$menuToggles=a.domElements.$menuToggles.add(g),g.on("tap",d);if(c.is(".active")===!0)a.domElements.$menuDefault=c,a.domElements.$menuToggleDefault=g});a.domElements.$tabToggles.each(function(){var a=$(this),b=$(a.attr("href"));a.data("$tab",b);a.on("tap",function(){b.is(".active")===!0?a.trigger("showing"):a.tab("show")}).on("shown",function(){a.trigger("showing")})});
a.domElements.$buttonsGamePause.on("tap",k);a.domElements.$buttonsGameResume.on("tap",n);a.signals.onGameInput.add(E);a.signals.onWorkerReset.add(u);a.signals.onWorkerTaskStarted.add(v);a.signals.onWorkerTaskCompleted.add(w);a.signals.onWorkerTasksCompleted.add(x);a.signals.onGameReady.add(z);a.signals.onGameStarted.add(A);a.signals.onGameStartedCompleted.add(B);a.signals.onGameStopped.add(C);a.signals.onGameStoppedCompleted.add(D);a.signals.onGamePaused.add(q);a.signals.onGameResumed.add(h);$(window).trigger("resize");
a.domElements.$menuDefault.trigger("open")},wait:!0})})(KAIOPUA);
