(function(i){function q(a){var c,d,e={},j;this.utilProjector1Communicate=new THREE.Projector;this.utilVec31Communicate=new THREE.Vector3;this.utilVec32Communicate=new THREE.Vector3;this.utilVec31Look=new THREE.Vector3;this.utilVec32Look=new THREE.Vector3;this.utilVec33Look=new THREE.Vector3;this.utilVec34Look=new THREE.Vector3;this.utilVec35Look=new THREE.Vector3;this.utilVec36Look=new THREE.Vector3;a=a||{};a.name=typeof a.name==="string"&&a.name.length>0?a.name:"Character";a.geometry=a.geometry||
new THREE.CubeGeometry(50,100,50);a.center=!0;a.options=$.extend(!0,{},b.options,a.options);a.physics=$.extend({},b.options.physics,a.physics);s.Instance.call(this,a);stats=this.options.stats;c=this.options.movement;c.move.direction=new THREE.Vector3;d=c.rotate;d.facingDirectionBase=new THREE.Vector3(0,0,1);d.facingDirection=d.facingDirectionBase.clone();d.facingDirectionLast=d.facingDirection.clone();d.facing=new THREE.Quaternion;d.facingAngle=0;d.turn=new THREE.Quaternion;d.turnDirection=d.facingDirection.clone();
d.turnAngle=0;d.axis=new THREE.Vector3(0,1,0);d.delta=new THREE.Quaternion;d.vector=new THREE.Quaternion;c=c.jump;c.time=0;c.timeNotGrounded=0;c.ready=!0;c.active=!1;c.holding=!1;this.name=a.name||G;this.state={};this.materialAffect=this.material instanceof THREE.MeshFaceMaterial?this.geometry.materials[0]:this.material;this.communicating=!1;a=this.conversations={};a.activeCount=0;a.names=[];a.said=[];a.unsaid=[];a.randomable=[];a.randomableUnsaid=[];a.dialogueData={};a.positionStart=new THREE.Vector3;
a.projectedPosition=new THREE.Vector3;a.screenPosition=new THREE.Vector3;for(j in this.options.dialogues)e[j]=this.add_dialogue(j);e.silence=$.proxy(this.silence,this);this.actions.add({names:"communicate",eventCallbacks:e,deactivateCallbacks:"silence",activeCheck:$.proxy(function(){return this.communicating},this),options:{type:this.options.actionTypes.interactive}});this.onHurt=new signals.Signal;this.onDead=new signals.Signal;this.onRespawned=new signals.Signal;this.reset()}function H(){var a;
a=this.state;a.up=0;a.down=0;a.left=0;a.right=0;a.forward=0;a.back=0;a.moving=!1;a.movingSelf=!1;a.movingHorizontal=!1;a.movingSelfHorizontal=!1;a.movingBack=!1;a.grounded=!1;a.invulnerable=!1;a.invulnerableTime=0;a.dead=!1;a.decaying=!1;a.health=stats.healthMax;this.morphs.clear_all();this.actions.clear_active()}function I(a){this._scene=a;this._scene instanceof THREE.Scene?l.signals.onGameUpdated.add(this.update,this):(l.signals.onGameUpdated.remove(this.update,this),this.reset())}function J(a){var c=
this.state,d=this.options.animation,e=d.durations,d=d.names;if(this.options.stats.invincible!==!0&&c.invulnerable!==!0&&c.dead!==!0&&i.is_number(a)&&a>0)return this.health-=a,this.onHurt.dispatch(),this.morphs.play(d.hurt,{duration:e.hurt,solo:!0,durationClear:e.clearSolo}),c.health===0?this.die():this.invulnerable=!0,!0}function K(){var a=this.state,c=this.options.animation,d=c.durations,c=c.names;this.health=0;a.dead=!0;this.morphs.play(c.die,{duration:d.die,solo:!0,durationClear:d.clearSolo,callback:$.proxy(this.decay,
this)});this.onDead.dispatch()}function L(){var a=this.state,c=this.options.stats,d=this.options.animation,e=d.durations,j=d.delays,d=d.names,t=this;if(a.dead===!0)a.decaying=!0,this.morphs.play(d.decay,{duration:e.decay,delay:j.decay,solo:!0,durationClear:e.clearSolo}),this.materialAffect.transparent=!0,v.tween(this.materialAffect,{opacity:0},{duration:e.decay,delay:j.decay,onComplete:function(){t.parent instanceof THREE.Object3D&&t.parent.remove(t);t.material.transparent=!1;t.material.opacity=1;
t.morphs.clear_all();c.respawnOnDeath===!0&&t.respawn()}})}function M(a,c){var d=this.state;d.spawnParent=a;d.spawnLocation=c}function N(a,c){var d=this.state,e=this.options.animation,j=e.durations,e=e.names;this.reset();a instanceof THREE.Object3D&&this.set_spawn(a,c);if(d.spawnParent instanceof THREE.Object3D)this.materialAffect.transparent=!0,this.materialAffect.opacity=0,d.spawnParent.add(this),d.spawnLocation instanceof THREE.Vector3&&this.position.copy(d.spawnLocation),this.onRespawned.dispatch(),
this.morphs.play(e.respawn,{duration:j.respawn,solo:!0,durationClear:j.clearSolo}),this.invulnerable=!0}function O(a){this.target=a instanceof THREE.Object3D&&a.interactive===!0?a:void 0}function P(a,c){var d=this,e=this.conversations,c=this.options.dialogues[a]=c||this.options.dialogues[a]||{};i.array_cautious_add(e.names,a);i.array_cautious_add(e.unsaid,a);c.randomable!==!1&&(i.array_cautious_add(e.randomable,a),i.array_cautious_add(e.randomableUnsaid,a));return function(c){c=c||{};c.dialogueName=
a;d.communicate(c)}}function Q(a){var a=a||{},c,d,e=this.options.animation,j=e.names,t=e.durations,e=this.conversations,h=e.dialogueData,f=a.dialogueName;c=this.options.dialogues[f];var b,n,g;a.target instanceof q&&a.target!==this&&(this.communicate_target(a.target),this.targetCommunication.communicate_target(this));if(typeof c!=="undefined"){h.hasOwnProperty(f)!==!0&&(h[f]={said:[]},c.randomable!==!1?(i.array_cautious_add(e.randomable,f),i.array_cautious_add(e.randomableUnsaid,f)):(i.array_cautious_remove(e.randomable,
f),i.array_cautious_remove(e.randomableUnsaid,f)));h=h[f];b=typeof c==="string"?c:i.to_array(c.responses||c);if(typeof b==="string")n=b;else if(c=c.random===!0||h.said.length===b.length,c===!0)n=i.array_random_value(b);else for(c=0,d=b.length;c<d;c++)if(i.index_of_value(h.said,b[c])===-1){n=b[c];h.said.push(n);break}typeof n==="string"?h=n:(h=n.message,g=n.next);typeof h==="function"&&(h=h.call(this));i.array_cautious_add(e.said,f);i.array_cautious_remove(e.unsaid,f);i.array_cautious_remove(e.randomableUnsaid,
f);h=i.to_array(h);if(h.length>0){e.activeCount++;e.active=f;e.paused=!1;e.ending=a.ending||!1;if(e.greeted!==!0)e.greeted=!0,this.morphs.play(j.greeting,{duration:t.greeting});g==="unsaid"&&(g=e.randomableUnsaid.length>0?i.array_random_value(e.randomableUnsaid):void 0);g==="random"&&(j=e.randomable.slice(0),i.array_cautious_remove(j,f),g=i.array_random_value(j));e.next=g;if(e.textbubble instanceof p.Instance!==!0)e.textbubble=new p.Instance;a=a.textbubble||{};a.oneEnded=$.proxy(this.communicate_next,
this);a.oneRemoved=$.proxy(this.silence,this);a.disableAdvanceByUser=a.disableAdvanceByUser||!1;a.delayAdvanced=a.delayAdvanced||0;a.animateAlways=a.animateAlways||!1;e.textbubble.content(h).show(a)}}this.targetCommunication.communicate_start();this.communicate_start()}function R(a){if(this.targetCommunication!==a)this.targetCommunication=a,a instanceof q&&this.look_at(this.targetCommunication)}function S(){var a=this.conversations;if(this.communicating!==!0)this.communicating=!0,a.positionStart.copy(this.position),
l.cameraControls.onCameraMoved.add(this.communicate_update,this);this.communicate_update()}function T(a){var c=this.options.communication,d=this.targetCommunication,e=this.conversations,j=this.utilProjector1Communicate,b=this.utilVec31Communicate,h=this.utilVec32Communicate,f=e.projectedPosition,i=e.screenPosition;if(this.communicating===!0||a===!0)if(a=a===!0?0:r.distance_between(e.positionStart,this.position),a>c.distanceMovedMax)this.silence();else if(b.copy(this.matrixWorld.getPosition()),h.set(c.boundRadiusPctX,
c.boundRadiusPctY,c.boundRadiusPctZ).multiplyScalar(this.boundRadius),this.matrixRotationWorld.extractRotation(this.matrixWorld).multiplyVector3(h),b.addSelf(h),d instanceof q&&(h=r.normal_between(d.matrixWorld.getPosition(),b).multiplyScalar(this.boundRadius*c.boundRadiusPctAway),b.addSelf(h)),j.projectVector(b,l.camera),f.x=l.screenWidth*(b.x+1)*0.5,f.y=-(l.screenHeight*(b.y-1))*0.5,i.x=u.clamp(f.x,0,l.screenWidth),i.y=u.clamp(f.y,0,l.screenHeight),distance=r.distance_between(f,i),distance>c.distanceOutsideScreenMax)this.silence();
else{if(e.paused!==!0&&e.textbubble instanceof p.Instance){if(d instanceof q)c=d.conversations.screenPosition,c=r.normal_between(c,i),e.textbubble.normal_to_placement(c);e.textbubble.reposition(i.x,i.y)}}else l.cameraControls.onCameraMoved.remove(this.communicate_update,this)}function U(){var a=this.conversations,c=this.targetCommunication,d=a.active,a=a.next,e=!0;this.communicating===!0&&(c instanceof q&&typeof c.options.dialogues[d]!=="undefined"&&c.conversations.active!==d&&(e=!1,this.communicate_pause(),
c.actions.execute("communicate",d,{target:this})),e===!0&&(typeof a==="string"&&a!==d?this.communicate({dialogueName:a,textbubble:{animateAlways:!0}}):typeof c.conversations.next==="string"&&c.conversations.next!==c.conversations.active?c.communicate_next():this.communicate_end()))}function V(){var a=this.conversations;if(this.communicating===!0)a.paused=!0,a.textbubble instanceof p.Instance&&a.textbubble.hide()}function W(){var a=this.options.communication,c=this.conversations,d=this.targetCommunication,
e=this.options.dialogues.goodbye,j,b=!0;if(this.communicating===!0&&c.ending!==!0){c.ending=!0;if(c.activeCount>a.activeCountMinEnd)d instanceof q&&(j=d.options.dialogues.goodbye),typeof e!=="undefined"&&(b=!1,this.communicate({dialogueName:"goodbye",ending:!0,textbubble:{disableAdvanceByUser:!0,delayAdvanced:a.delayEnd,oneAdvanced:$.proxy(function(){c.ending===!0&&this.silence()},this)}})),typeof j!=="undefined"&&(b=!1,d.communicate_end());b===!0&&this.silence()}}function X(){var a=this.options.animation,
c=a.names,a=a.durations,d=this.conversations,e=this.targetCommunication;if(this.communicating!==!1)this.communicating=!1,l.cameraControls.onCameraMoved.remove(this.communicate_update,this),d.greeted=d.ending=d.paused=!1,d.active=d.next="",d.activeCount=0,this.morphs.clear(c.greeting,{duration:a.clear}),d.textbubble instanceof p.Instance&&(d.textbubble.remove(),delete d.textbubble),e&&e.communicating===!0&&e.targetCommunication===this&&e.silence(),this.targetCommunication=void 0}function Y(a,c){var d=
this.state,e=this.options.movement.rotate.facingDirection,j;d.hasOwnProperty(a)&&(d[a]=c===!0?0:1);if(d.forward===1)e.z=1,e.x=0,j=!0;else if(d.back===1)e.z=-1,e.x=0,j=!0;if(d.left===1||d.right===1)e.x=d.right===1?-d.right:d.left,j!==!0?e.z=0:e.normalize()}function Z(){this.options.movement.jump.active=!1;this.options.movement.jump.holding=!1}function aa(a){var c=this.options.movement.rotate,d=c.delta;if(a!==0)d.setFromAxisAngle(c.axis,a),this.quaternion.multiplySelf(d),c.turn.multiplySelf(d),d.multiplyVector3(c.turnDirection),
c.turnAngle=u.rad_between_PI(c.turnAngle+a)}function ba(a,c){var d=this.options.movement.rotate,e=d.axis,j=d.delta,b=d.facingDirectionLast,h=r.signed_angle_between_coplanar_vectors(b,a,e)*(i.is_number(c)?c:1),f;if(h!==0)h=u.rad_between_PI(d.facingAngle+h),f=u.shortest_rotation_between_angles(d.facingAngle,h),j.setFromAxisAngle(e,f),this.quaternion.multiplySelf(j),d.facing.multiplySelf(j),j.multiplyVector3(b),d.facingAngle=h}function ca(a){var c=this.options.movement.rotate,d=c.axis,e=this.utilVec31Look.copy(d),
j=this.utilVec32Look.copy(c.facingDirectionBase),b=c.delta,h=this.utilVec33Look.copy(this.matrixWorld.getPosition()),f=this.utilVec34Look.copy(a.matrixWorld.getPosition()),a=this.utilVec35Look,i=this.utilVec36Look;this.matrixWorld.rotateAxis(e);this.matrixWorld.rotateAxis(j);h=r.normal_between(h,f);a.cross(h,e);i.cross(e,a);e=r.signed_angle_between_coplanar_vectors(j,i,e);b.setFromAxisAngle(d,e);this.quaternion.multiplySelf(b);c.facing.multiplySelf(b);b.multiplyVector3(c.facingDirectionLast);c.facingAngle=
e}function da(a,c){var d=this.rigidBody,e=this.morphs,b=this.state,i=this.options,h=i.stats,f=i.movement,w=f.move,n=f.rotate,g=f.jump,f=i.animation,m=f.names,o=f.durations,i=f.delays,f=f.options,k,l=w.direction,r=w.speed*c,q,p,s,C,y,B,D,z,E,A,F,x;if(b.invulnerable===!0&&(b.invulnerableTime+=a,b.invulnerableTime>=h.invulnerabilityDuration))this.invulnerable=!1;if(b.dead!==!0&&(b.movingSelfHorizontal=b.forward===1||b.back===1||b.left===1||b.right===1?!0:!1,b.movingSelf=b.movingSelfHorizontal||b.up===
1||b.down===1?!0:!1,l.z=b.movingSelfHorizontal?1:0,b.movingSelfHorizontal===!0&&(this.turn_by((b.right===1?-b.right:b.left)*n.turnSpeed),this.face_local_direction(n.facingDirection,u.clamp(n.lerpDelta*c,0,1))),typeof d!=="undefined")){s=g.time;C=g.duration;B=g.delayNotGrounded;D=g.delayFalling;n=g.speedStart*c;q=g.speedEnd*c;k=g.airControl;p=g.moveDamping;A=d.velocityMovement;F=A.forceDelta;x=A.forceRotated.length()/c;z=d.velocityGravity;E=z.forceDelta;b.movingHorizontal=b.movingSelfHorizontal||x>
0;b.moving=b.movingSelf||b.movingHorizontal||z.forceRotated.lengthSq()>0;h=d.grounded;d=d.sliding;y=g.timeNotGrounded+=a;if(h===!1&&y>=B){if(typeof g.movementChangeLayer==="undefined")g.movementChangeLayer=v.temporary_change(A,{damping:new THREE.Vector3(p,p,p),speedDelta:new THREE.Vector3(k,k,k)})}else if(typeof g.movementChangeLayer!=="undefined")v.revert_change(A,g.movementChangeLayer),g.movementChangeLayer=void 0;if(g.active===!1&&h===!1&&y>=D)g.ready=!1,k={duration:o.jump,loop:!0,solo:!0,durationClear:o.clearSolo,
startAt:0,startAtMax:!1},f.jump&&$.extend(k,f.jump),e.play(m.jump,k);else if(b.up!==0&&(h===!0&&d===!1||y<B)&&g.ready===!0)g.time=0,g.ready=!1,g.active=!0,g.starting=!0,g.started=!1,g.holding=!0;else if(g.holding===!0&&g.active===!0&&g.time<C){if(b.up===0&&g.time>=g.durationMin)g.holding=!1;g.starting===!0?x===0?(k={duration:o.jumpStart,loop:!1,solo:!0,durationClear:o.clearSolo,oneComplete:function(){g.started=!0;g.starting=!1;z.reset()}},f.jumpStart&&$.extend(k,f.jumpStart),e.play(m.jumpStart,k)):
(g.starting=!1,z.reset()):(e.clear(m.jumpStart),k={duration:o.jump,loop:!0,solo:!0,durationClear:o.clearSolo,startAt:0,startAtMax:g.started},f.jump&&$.extend(k,f.jump),e.play(m.jump,k),s/=C,g.time+=a,E.y+=n*(1-s)+q*s)}else if(h===!0&&g.active!==!1&&(this.stop_jumping(),y>=B&&x===0&&(e.clear(m.jump),k={duration:o.jumpEnd,loop:!1,interruptable:!1,startAt:0,startAtMax:!0,oneComplete:function(){e.clear(m.jumpEnd,{duration:o.clear})}},f.jumpEnd&&$.extend(k,f.jumpEnd),e.play(m.jumpEnd,k))),h===!0&&d===
!1&&b.up===0)g.timeNotGrounded=0,g.ready=!0;if(d!==!0)if(l.multiplyScalar(r),b.movingHorizontal&&g.active===!0&&(l.z+=n*g.moveSpeedMod),F.addSelf(l),l.z<0)b.movingBack=!0;else if(l.z>0)b.movingBack=!1;g.active===!1&&b.grounded===!0&&(x>0||d===!0?x>=w.runThreshold?(k={duration:o.run,loop:!0,solo:!0,durationClear:o.clearSolo,reverse:b.movingBack},f.run&&$.extend(k,f.run),this.morphs.play(m.run,k)):(k={duration:o.walk,loop:!0,solo:!0,durationClear:o.clearSolo,reverse:b.movingBack},f.walk&&$.extend(k,
f.walk),this.morphs.play(m.walk,k)):(w=[m.run,m.walk,m.jump],this.actions.is_active(this.options.actionTypes.interactive)!==!0?(k={duration:o.idle,loop:!0,alternate:m.idleAlt,alternateDelay:i.idleAlt,alternateParameters:{duration:o.idleAlt}},f.idle&&$.extend(k,f.idle),this.morphs.play(m.idle,k)):w=w.concat([m.idle,m.idleAlt]),this.morphs.clear_only(w,{duration:o.clear})));b.grounded=h}}var l=i.shared=i.shared||{},b={},s,p,u,r,v,G="Character";i.asset_register("js/kaiopua/characters/Character.js",{data:b,
requirements:["js/kaiopua/core/Model.js","js/kaiopua/ui/Textbubble.js","js/kaiopua/utils/MathHelper.js","js/kaiopua/utils/VectorHelper.js","js/kaiopua/utils/ObjectHelper.js"],callbacksOnReqs:function(a,c,d,e,j){s=a;p=c;u=d;r=e;v=j;b.options={dynamic:!0,physics:{dynamic:!0,bodyType:"box",movementDamping:0.5,movementForceLengthMax:l.universeGravityMagnitude.length()*20},stats:{healthMax:100,invincible:!1,invulnerabilityDuration:1500,invulnerabilityOpacityPulses:6,invulnerabilityOpacityMin:0.5,respawnOnDeath:!1},
movement:{move:{speed:3,runThreshold:0},rotate:{lerpDelta:1,turnSpeed:0.025},jump:{speedStart:4,speedEnd:0,airControl:0.1,moveDamping:0.99,moveSpeedMod:0,durationMin:100,duration:100,delayNotGrounded:125,delayFalling:350}},animation:{names:{walk:"walk",run:"run",idle:"idle",idleAlt:!1,jump:"jump",jumpStart:"jump_start",jumpEnd:"jump_end",hurt:"hurt",die:"die",decay:"decay",respawn:"respawn",greeting:"greeting"},durations:{walk:750,run:500,idle:3E3,idleAlt:3E3,jump:1E3,jumpStart:125,jumpEnd:125,hurt:250,
die:1E3,decay:500,respawn:1E3,greeting:1E3,clear:125,clearSolo:125},delays:{decay:500,idleAlt:5E3},options:{}},communication:{delayEnd:500,activeCountMinEnd:2,boundRadiusPctAway:0.4,boundRadiusPctX:0,boundRadiusPctY:0.4,boundRadiusPctZ:0,distanceMovedMax:100,distanceOutsideScreenMax:50}};b.Instance=q;b.Instance.prototype=new s.Instance;b.Instance.prototype.constructor=b.Instance;b.Instance.prototype.supr=s.Instance.prototype;b.Instance.prototype.reset=H;b.Instance.prototype.set_scene=I;b.Instance.prototype.hurt=
J;b.Instance.prototype.die=K;b.Instance.prototype.decay=L;b.Instance.prototype.set_spawn=M;b.Instance.prototype.respawn=N;b.Instance.prototype.select=O;b.Instance.prototype.add_dialogue=P;b.Instance.prototype.communicate=Q;b.Instance.prototype.communicate_target=R;b.Instance.prototype.communicate_start=S;b.Instance.prototype.communicate_update=T;b.Instance.prototype.communicate_next=U;b.Instance.prototype.communicate_pause=V;b.Instance.prototype.communicate_end=W;b.Instance.prototype.silence=X;b.Instance.prototype.move_state_change=
Y;b.Instance.prototype.stop_jumping=Z;b.Instance.prototype.turn_by=aa;b.Instance.prototype.face_local_direction=ba;b.Instance.prototype.look_at=ca;b.Instance.prototype.update=da;Object.defineProperty(b.Instance.prototype,"scene",{get:function(){return this._scene},set:function(a){this.set_scene(a)}});Object.defineProperty(b.Instance.prototype,"health",{get:function(){return this.state.health},set:function(a){if(i.is_number(a))this.state.health=u.clamp(a,0,this.options.stats.healthMax)}});Object.defineProperty(b.Instance.prototype,
"invulnerable",{get:function(){return this.state.invulnerable},set:function(a){var d=this,c=this.state,b=this.options.stats,e=b.invulnerabilityDuration/(b.invulnerabilityOpacityPulses*2);c.invulnerable=a;c.invulnerableTime=0;c.invulnerable===!0?(this.materialAffect.transparent=!0,a=v.tween(this.materialAffect,{opacity:1},{start:!1,duration:e}),b=v.tween(this.materialAffect,{opacity:b.invulnerabilityOpacityMin},{start:!1,duration:e}),b.chain(a.chain(b)).start()):v.tween(this.materialAffect,{opacity:1},
{duration:e,onComplete:function(){d.material.transparent=!1}})}});Object.defineProperty(b.Instance.prototype,"moving",{get:function(){return this.state.moving}});Object.defineProperty(b.Instance.prototype,"movingHorizontal",{get:function(){return this.state.movingHorizontal}});Object.defineProperty(b.Instance.prototype,"jumping",{get:function(){return this.options.movement.jump.active}});Object.defineProperty(b.Instance.prototype,"turn",{get:function(){return this.options.movement.rotate.turn}});
Object.defineProperty(b.Instance.prototype,"facing",{get:function(){return this.options.movement.rotate.facing}})},wait:!0})})(KAIOPUA);
