(function(i){function q(a){var e,b,d={},j;this.utilProjector1Communicate=new THREE.Projector;this.utilVec31Communicate=new THREE.Vector3;this.utilVec32Communicate=new THREE.Vector3;this.utilVec31Look=new THREE.Vector3;this.utilVec32Look=new THREE.Vector3;this.utilVec33Look=new THREE.Vector3;this.utilVec34Look=new THREE.Vector3;this.utilVec35Look=new THREE.Vector3;this.utilVec36Look=new THREE.Vector3;a=a||{};a.name=typeof a.name==="string"&&a.name.length>0?a.name:"Character";a.geometry=a.geometry||
new THREE.CubeGeometry(50,100,50);a.center=!0;a.options=$.extend(!0,{},c.options,a.options);a.physics=$.extend({},c.options.physics,a.physics);s.Instance.call(this,a);stats=this.options.stats;e=this.options.movement;e.move.direction=new THREE.Vector3;b=e.rotate;b.facingDirectionBase=new THREE.Vector3(0,0,1);b.facingDirection=b.facingDirectionBase.clone();b.facingDirectionLast=b.facingDirection.clone();b.facing=new THREE.Quaternion;b.facingAngle=0;b.turn=new THREE.Quaternion;b.turnDirection=b.facingDirection.clone();
b.turnAngle=0;b.axis=new THREE.Vector3(0,1,0);b.delta=new THREE.Quaternion;b.vector=new THREE.Quaternion;e=e.jump;e.time=0;e.timeNotGrounded=0;e.ready=!0;e.active=!1;e.holding=!1;this.name=a.name||G;this.state={};this.materialAffect=this.material instanceof THREE.MeshFaceMaterial?this.geometry.materials[0]:this.material;this.communicating=!1;a=this.conversations={};a.activeCount=0;a.names=[];a.said=[];a.unsaid=[];a.randomable=[];a.randomableUnsaid=[];a.dialogueData={};a.positionStart=new THREE.Vector3;
a.projectedPosition=new THREE.Vector3;a.screenPosition=new THREE.Vector3;for(j in this.options.dialogues)d[j]=this.add_dialogue(j);d.silence=$.proxy(this.silence,this);this.actions.add({names:"communicate",eventCallbacks:d,deactivateCallbacks:"silence",activeCheck:$.proxy(function(){return this.communicating},this),options:{type:this.options.actionTypes.interactive}});this.onHurt=new signals.Signal;this.onDead=new signals.Signal;this.onRespawned=new signals.Signal;this.reset()}function H(){var a;
a=this.state;a.up=0;a.down=0;a.left=0;a.right=0;a.forward=0;a.back=0;a.moving=!1;a.movingSelf=!1;a.movingHorizontal=!1;a.movingSelfHorizontal=!1;a.movingBack=!1;a.grounded=!1;a.invulnerable=!1;a.invulnerableTime=0;a.dead=!1;a.decaying=!1;a.health=stats.healthMax;this.morphs.clear_all();this.actions.clear_active()}function I(a){this._scene=a;this._scene instanceof THREE.Scene?m.signals.onGameUpdated.add(this.update,this):(m.signals.onGameUpdated.remove(this.update,this),this.reset())}function J(a){var e=
this.state,b=this.options.animation,d=b.durations,b=b.names;if(this.options.stats.invincible!==!0&&e.invulnerable!==!0&&e.dead!==!0&&i.is_number(a)&&a>0)return this.health-=a,this.onHurt.dispatch(),this.morphs.play(b.hurt,{duration:d.hurt,solo:!0,durationClear:d.clearSolo}),e.health===0?this.die():this.invulnerable=!0,!0}function K(){var a=this.state,e=this.options.animation,b=e.durations,e=e.names;this.health=0;a.dead=!0;this.morphs.play(e.die,{duration:b.die,solo:!0,durationClear:b.clearSolo,callback:$.proxy(this.decay,
this)});this.onDead.dispatch()}function L(){var a=this.state,e=this.options.stats,b=this.options.animation,d=b.durations,j=b.delays,b=b.names,t=this;if(a.dead===!0)a.decaying=!0,this.morphs.play(b.decay,{duration:d.decay,delay:j.decay,solo:!0,durationClear:d.clearSolo}),this.materialAffect.transparent=!0,v.tween(this.materialAffect,{opacity:0},{duration:d.decay,delay:j.decay,onComplete:function(){t.parent instanceof THREE.Object3D&&t.parent.remove(t);t.material.transparent=!1;t.material.opacity=1;
t.morphs.clear_all();e.respawnOnDeath===!0&&t.respawn()}})}function M(a,e){var b=this.state;b.spawnParent=a;b.spawnLocation=e}function N(a,e){var b=this.state,d=this.options.animation,j=d.durations,d=d.names;this.reset();a instanceof THREE.Object3D&&this.set_spawn(a,e);if(b.spawnParent instanceof THREE.Object3D)this.materialAffect.transparent=!0,this.materialAffect.opacity=0,b.spawnParent.add(this),b.spawnLocation instanceof THREE.Vector3&&this.position.copy(b.spawnLocation),this.onRespawned.dispatch(),
this.morphs.play(d.respawn,{duration:j.respawn,solo:!0,durationClear:j.clearSolo}),this.invulnerable=!0}function O(a){this.target=a instanceof THREE.Object3D&&a.interactive===!0?a:void 0}function P(a,e){var b=this,d=this.conversations,e=this.options.dialogues[a]=e||this.options.dialogues[a]||{};i.array_cautious_add(d.names,a);i.array_cautious_add(d.unsaid,a);e.randomable!==!1&&(i.array_cautious_add(d.randomable,a),i.array_cautious_add(d.randomableUnsaid,a));return function(d){d=d||{};d.dialogueName=
a;b.communicate(d)}}function Q(a){var a=a||{},e,b,d=this.options.animation,j=d.names,t=d.durations,d=this.conversations,h=d.dialogueData,g=a.dialogueName,c=this.options.dialogues[g],n,f,l;a.target instanceof q&&a.target!==this&&(this.communicate_target(a.target),this.targetCommunication.communicate_target(this));if(typeof c!=="undefined"){h.hasOwnProperty(g)!==!0&&(h[g]={said:[]},c.randomable!==!1?(i.array_cautious_add(d.randomable,g),i.array_cautious_add(d.randomableUnsaid,g)):(i.array_cautious_remove(d.randomable,
g),i.array_cautious_remove(d.randomableUnsaid,g)));h=h[g];n=typeof c==="string"?c:i.to_array(c.responses||c);if(typeof n==="string")f=n;else if(e=c.random===!0||h.said.length===n.length,e===!0)f=i.array_random_value(n);else for(e=0,b=n.length;e<b;e++)if(i.index_of_value(h.said,n[e])===-1){f=n[e];h.said.push(f);break}typeof f==="string"?h=f:(h=f.message,l=f.next);typeof h==="function"&&(h=h.call(this));i.array_cautious_add(d.said,g);i.array_cautious_remove(d.unsaid,g);i.array_cautious_remove(d.randomableUnsaid,
g);h=i.to_array(h);if(h.length>0){d.activeCount++;d.active=g;d.paused=!1;d.ending=a.ending||!1;if(d.greeted!==!0)d.greeted=!0,this.morphs.play(j.greeting,{duration:t.greeting});l==="unsaid"&&(l=d.randomableUnsaid.length>0?i.array_random_value(d.randomableUnsaid):void 0);l==="random"&&(j=d.randomable.slice(0),i.array_cautious_remove(j,g),l=i.array_random_value(j));d.next=l;if(d.textbubble instanceof p.Instance!==!0)d.textbubble=new p.Instance;a=a.textbubble||{};a.oneEnded=$.proxy(this.communicate_next,
this);a.oneRemoved=$.proxy(this.silence,this);a.disableAdvanceByUser=a.disableAdvanceByUser||!1;a.delayAdvanced=a.delayAdvanced||0;a.animateAlways=a.animateAlways||!1;d.textbubble.content(h).show(a)}typeof c.callback==="function"&&c.callback()}this.targetCommunication.communicate_start();this.communicate_start()}function R(a){if(this.targetCommunication!==a)this.targetCommunication=a,a instanceof q&&this.look_at(this.targetCommunication)}function S(){var a=this.conversations;if(this.communicating!==
!0)this.communicating=!0,a.positionStart.copy(this.position),m.cameraControls.onCameraMoved.add(this.communicate_update,this);this.communicate_update()}function T(a){var e=this.options.communication,b=this.targetCommunication,d=this.conversations,j=this.utilProjector1Communicate,c=this.utilVec31Communicate,h=this.utilVec32Communicate,g=d.projectedPosition,i=d.screenPosition;if(this.communicating===!0||a===!0)if(a=a===!0?0:r.distance_between(d.positionStart,this.position),a>e.distanceMovedMax)this.silence();
else if(c.copy(this.matrixWorld.getPosition()),h.set(e.boundRadiusPctX,e.boundRadiusPctY,e.boundRadiusPctZ).multiplyScalar(this.boundRadius),this.matrixRotationWorld.extractRotation(this.matrixWorld).multiplyVector3(h),c.addSelf(h),b instanceof q&&(h=r.normal_between(b.matrixWorld.getPosition(),c).multiplyScalar(this.boundRadius*e.boundRadiusPctAway),c.addSelf(h)),j.projectVector(c,m.camera),g.x=m.screenWidth*(c.x+1)*0.5,g.y=-(m.screenHeight*(c.y-1))*0.5,i.x=u.clamp(g.x,0,m.screenWidth),i.y=u.clamp(g.y,
0,m.screenHeight),distance=r.distance_between(g,i),distance>e.distanceOutsideScreenMax)this.silence();else{if(d.paused!==!0&&d.textbubble instanceof p.Instance){if(b instanceof q)e=b.conversations.screenPosition,e=r.normal_between(e,i),d.textbubble.normal_to_placement(e);d.textbubble.reposition(i.x,i.y)}}else m.cameraControls.onCameraMoved.remove(this.communicate_update,this)}function U(){var a=this.conversations,e=this.targetCommunication,b=a.active,a=a.next,d=this.options.dialogues[b],j=!0;this.communicating===
!0&&(e instanceof q&&typeof e.options.dialogues[b]!=="undefined"&&e.conversations.active!==b&&(j=!1,this.communicate_pause(),e.actions.execute("communicate",b,{target:this})),typeof d.callbackComplete==="function"&&d.callbackComplete(),j===!0&&(typeof a==="string"&&a!==b?this.communicate({dialogueName:a,textbubble:{animateAlways:!0}}):typeof e.conversations.next==="string"&&e.conversations.next!==e.conversations.active?e.communicate_next():this.communicate_end()))}function V(){var a=this.conversations;
if(this.communicating===!0)a.paused=!0,a.textbubble instanceof p.Instance&&a.textbubble.hide()}function W(){var a=this.options.communication,e=this.conversations,b=this.targetCommunication,d=this.options.dialogues.goodbye,j,c=!0;if(this.communicating===!0&&e.ending!==!0){e.ending=!0;if(e.activeCount>a.activeCountMinEnd)b instanceof q&&(j=b.options.dialogues.goodbye),typeof d!=="undefined"&&(c=!1,this.communicate({dialogueName:"goodbye",ending:!0,textbubble:{disableAdvanceByUser:!0,delayAdvanced:a.delayEnd,
oneAdvanced:$.proxy(function(){e.ending===!0&&this.silence()},this)}})),typeof j!=="undefined"&&(c=!1,b.communicate_end());c===!0&&this.silence()}}function X(){var a=this.options.animation,e=a.names,a=a.durations,b=this.conversations,d=this.targetCommunication;if(this.communicating!==!1)this.communicating=!1,m.cameraControls.onCameraMoved.remove(this.communicate_update,this),b.greeted=b.ending=b.paused=!1,b.active=b.next="",b.activeCount=0,this.morphs.clear(e.greeting,{duration:a.clear}),b.textbubble instanceof
p.Instance&&(b.textbubble.remove(),delete b.textbubble),d&&d.communicating===!0&&d.targetCommunication===this&&d.silence(),this.targetCommunication=void 0}function Y(a,e){var b=this.state,d=this.options.movement.rotate.facingDirection,j;b.hasOwnProperty(a)&&(b[a]=e===!0?0:1);if(b.forward===1)d.z=1,d.x=0,j=!0;else if(b.back===1)d.z=-1,d.x=0,j=!0;if(b.left===1||b.right===1)d.x=b.right===1?-b.right:b.left,j!==!0?d.z=0:d.normalize()}function Z(){this.options.movement.jump.active=!1;this.options.movement.jump.holding=
!1}function aa(a){var e=this.options.movement.rotate,b=e.delta;if(a!==0)b.setFromAxisAngle(e.axis,a),this.quaternion.multiplySelf(b),e.turn.multiplySelf(b),b.multiplyVector3(e.turnDirection),e.turnAngle=u.rad_between_PI(e.turnAngle+a)}function ba(a,e){var b=this.options.movement.rotate,d=b.axis,j=b.delta,c=b.facingDirectionLast,h=r.signed_angle_between_coplanar_vectors(c,a,d)*(i.is_number(e)?e:1),g;if(h!==0)h=u.rad_between_PI(b.facingAngle+h),g=u.shortest_rotation_between_angles(b.facingAngle,h),
j.setFromAxisAngle(d,g),this.quaternion.multiplySelf(j),b.facing.multiplySelf(j),j.multiplyVector3(c),b.facingAngle=h}function ca(a){var e=this.options.movement.rotate,b=e.axis,d=this.utilVec31Look.copy(b),j=this.utilVec32Look.copy(e.facingDirectionBase),c=e.delta,h=this.utilVec33Look.copy(this.matrixWorld.getPosition()),g=this.utilVec34Look.copy(a.matrixWorld.getPosition()),a=this.utilVec35Look,i=this.utilVec36Look;this.matrixWorld.rotateAxis(d);this.matrixWorld.rotateAxis(j);h=r.normal_between(h,
g);a.cross(h,d);i.cross(d,a);d=r.signed_angle_between_coplanar_vectors(j,i,d);c.setFromAxisAngle(b,d);this.quaternion.multiplySelf(c);e.facing.multiplySelf(c);c.multiplyVector3(e.facingDirectionLast);e.facingAngle=d}function da(a,e){var b=this.rigidBody,d=this.morphs,c=this.state,i=this.options,h=i.stats,g=i.movement,w=g.move,n=g.rotate,f=g.jump,g=i.animation,l=g.names,o=g.durations,i=g.delays,g=g.options,k,m=w.direction,r=w.speed*e,q,p,s,C,y,B,D,z,E,A,F,x;if(c.invulnerable===!0&&(c.invulnerableTime+=
a,c.invulnerableTime>=h.invulnerabilityDuration))this.invulnerable=!1;if(c.dead!==!0&&(c.movingSelfHorizontal=c.forward===1||c.back===1||c.left===1||c.right===1?!0:!1,c.movingSelf=c.movingSelfHorizontal||c.up===1||c.down===1?!0:!1,m.z=c.movingSelfHorizontal?1:0,c.movingSelfHorizontal===!0&&(this.turn_by((c.right===1?-c.right:c.left)*n.turnSpeed),this.face_local_direction(n.facingDirection,u.clamp(n.lerpDelta*e,0,1))),typeof b!=="undefined")){s=f.time;C=f.duration;B=f.delayNotGrounded;D=f.delayFalling;
n=f.speedStart*e;q=f.speedEnd*e;k=f.airControl;p=f.moveDamping;A=b.velocityMovement;F=A.forceDelta;x=A.forceRotated.length()/e;z=b.velocityGravity;E=z.forceDelta;c.movingHorizontal=c.movingSelfHorizontal||x>0;c.moving=c.movingSelf||c.movingHorizontal||z.forceRotated.lengthSq()>0;h=b.grounded;b=b.sliding;y=f.timeNotGrounded+=a;if(h===!1&&y>=B){if(typeof f.movementChangeLayer==="undefined")f.movementChangeLayer=v.temporary_change(A,{damping:new THREE.Vector3(p,p,p),speedDelta:new THREE.Vector3(k,k,
k)})}else if(typeof f.movementChangeLayer!=="undefined")v.revert_change(A,f.movementChangeLayer),f.movementChangeLayer=void 0;if(f.active===!1&&h===!1&&y>=D)f.ready=!1,k={duration:o.jump,loop:!0,solo:!0,durationClear:o.clearSolo,startAt:0,startAtMax:!1},g.jump&&$.extend(k,g.jump),d.play(l.jump,k);else if(c.up!==0&&(h===!0&&b===!1||y<B)&&f.ready===!0)f.time=0,f.ready=!1,f.active=!0,f.starting=!0,f.started=!1,f.holding=!0;else if(f.holding===!0&&f.active===!0&&f.time<C){if(c.up===0&&f.time>=f.durationMin)f.holding=
!1;f.starting===!0?x===0?(k={duration:o.jumpStart,loop:!1,solo:!0,durationClear:o.clearSolo,oneComplete:function(){f.started=!0;f.starting=!1;z.reset()}},g.jumpStart&&$.extend(k,g.jumpStart),d.play(l.jumpStart,k)):(f.starting=!1,z.reset()):(d.clear(l.jumpStart),k={duration:o.jump,loop:!0,solo:!0,durationClear:o.clearSolo,startAt:0,startAtMax:f.started},g.jump&&$.extend(k,g.jump),d.play(l.jump,k),s/=C,f.time+=a,E.y+=n*(1-s)+q*s)}else if(h===!0&&f.active!==!1&&(this.stop_jumping(),y>=B&&x===0&&(d.clear(l.jump),
k={duration:o.jumpEnd,loop:!1,interruptable:!1,startAt:0,startAtMax:!0,oneComplete:function(){d.clear(l.jumpEnd,{duration:o.clear})}},g.jumpEnd&&$.extend(k,g.jumpEnd),d.play(l.jumpEnd,k))),h===!0&&b===!1&&c.up===0)f.timeNotGrounded=0,f.ready=!0;if(b!==!0)if(m.multiplyScalar(r),c.movingHorizontal&&f.active===!0&&(m.z+=n*f.moveSpeedMod),F.addSelf(m),m.z<0)c.movingBack=!0;else if(m.z>0)c.movingBack=!1;f.active===!1&&c.grounded===!0&&(x>0||b===!0?x>=w.runThreshold?(k={duration:o.run,loop:!0,solo:!0,durationClear:o.clearSolo,
reverse:c.movingBack},g.run&&$.extend(k,g.run),this.morphs.play(l.run,k)):(k={duration:o.walk,loop:!0,solo:!0,durationClear:o.clearSolo,reverse:c.movingBack},g.walk&&$.extend(k,g.walk),this.morphs.play(l.walk,k)):(w=[l.run,l.walk,l.jump],this.actions.is_active(this.options.actionTypes.interactive)!==!0?(k={duration:o.idle,loop:!0,alternate:l.idleAlt,alternateDelay:i.idleAlt,alternateParameters:{duration:o.idleAlt}},g.idle&&$.extend(k,g.idle),this.morphs.play(l.idle,k)):w=w.concat([l.idle,l.idleAlt]),
this.morphs.clear_only(w,{duration:o.clear})));c.grounded=h}}var m=i.shared=i.shared||{},c={},s,p,u,r,v,G="Character";i.asset_register("js/kaiopua/characters/Character.js",{data:c,requirements:["js/kaiopua/core/Model.js","js/kaiopua/ui/Textbubble.js","js/kaiopua/utils/MathHelper.js","js/kaiopua/utils/VectorHelper.js","js/kaiopua/utils/ObjectHelper.js"],callbacksOnReqs:function(a,e,b,d,j){s=a;p=e;u=b;r=d;v=j;c.options={dynamic:!0,physics:{dynamic:!0,bodyType:"box",movementDamping:0.5,movementForceLengthMax:m.universeGravityMagnitude.length()*
20},stats:{healthMax:100,invincible:!1,invulnerabilityDuration:1500,invulnerabilityOpacityPulses:6,invulnerabilityOpacityMin:0.5,respawnOnDeath:!1},movement:{move:{speed:3,runThreshold:0},rotate:{lerpDelta:1,turnSpeed:0.025},jump:{speedStart:4,speedEnd:0,airControl:0.1,moveDamping:0.99,moveSpeedMod:0,durationMin:100,duration:100,delayNotGrounded:125,delayFalling:350}},animation:{names:{walk:"walk",run:"run",idle:"idle",idleAlt:!1,jump:"jump",jumpStart:"jump_start",jumpEnd:"jump_end",hurt:"hurt",die:"die",
decay:"decay",respawn:"respawn",greeting:"greeting"},durations:{walk:750,run:500,idle:3E3,idleAlt:3E3,jump:1E3,jumpStart:125,jumpEnd:125,hurt:250,die:1E3,decay:500,respawn:1E3,greeting:1E3,clear:125,clearSolo:125},delays:{decay:500,idleAlt:5E3},options:{}},communication:{delayEnd:500,activeCountMinEnd:2,boundRadiusPctAway:0.4,boundRadiusPctX:0,boundRadiusPctY:0.4,boundRadiusPctZ:0,distanceMovedMax:100,distanceOutsideScreenMax:50},paths:{}};c.Instance=q;c.Instance.prototype=new s.Instance;c.Instance.prototype.constructor=
c.Instance;c.Instance.prototype.supr=s.Instance.prototype;c.Instance.prototype.reset=H;c.Instance.prototype.set_scene=I;c.Instance.prototype.hurt=J;c.Instance.prototype.die=K;c.Instance.prototype.decay=L;c.Instance.prototype.set_spawn=M;c.Instance.prototype.respawn=N;c.Instance.prototype.select=O;c.Instance.prototype.add_dialogue=P;c.Instance.prototype.communicate=Q;c.Instance.prototype.communicate_target=R;c.Instance.prototype.communicate_start=S;c.Instance.prototype.communicate_update=T;c.Instance.prototype.communicate_next=
U;c.Instance.prototype.communicate_pause=V;c.Instance.prototype.communicate_end=W;c.Instance.prototype.silence=X;c.Instance.prototype.move_state_change=Y;c.Instance.prototype.stop_jumping=Z;c.Instance.prototype.turn_by=aa;c.Instance.prototype.face_local_direction=ba;c.Instance.prototype.look_at=ca;c.Instance.prototype.update=da;Object.defineProperty(c.Instance.prototype,"scene",{get:function(){return this._scene},set:function(a){this.set_scene(a)}});Object.defineProperty(c.Instance.prototype,"health",
{get:function(){return this.state.health},set:function(a){if(i.is_number(a))this.state.health=u.clamp(a,0,this.options.stats.healthMax)}});Object.defineProperty(c.Instance.prototype,"invulnerable",{get:function(){return this.state.invulnerable},set:function(a){var b=this,c=this.state,d=this.options.stats,e=d.invulnerabilityDuration/(d.invulnerabilityOpacityPulses*2);c.invulnerable=a;c.invulnerableTime=0;c.invulnerable===!0?(this.materialAffect.transparent=!0,a=v.tween(this.materialAffect,{opacity:1},
{start:!1,duration:e}),d=v.tween(this.materialAffect,{opacity:d.invulnerabilityOpacityMin},{start:!1,duration:e}),d.chain(a.chain(d)).start()):v.tween(this.materialAffect,{opacity:1},{duration:e,onComplete:function(){b.material.transparent=!1}})}});Object.defineProperty(c.Instance.prototype,"moving",{get:function(){return this.state.moving}});Object.defineProperty(c.Instance.prototype,"movingHorizontal",{get:function(){return this.state.movingHorizontal}});Object.defineProperty(c.Instance.prototype,
"jumping",{get:function(){return this.options.movement.jump.active}});Object.defineProperty(c.Instance.prototype,"turn",{get:function(){return this.options.movement.rotate.turn}});Object.defineProperty(c.Instance.prototype,"facing",{get:function(){return this.options.movement.rotate.facing}})},wait:!0})})(KAIOPUA);
