(function(f){function l(d){var e=this,c,d=d||{};d.name=typeof d.name==="string"&&d.name.length>0?d.name:"Hero";d.options=$.extend(!0,{},b.options,d.options);d.physics=$.extend({},b.options.physics,d.physics);g.Instance.call(this,d);this.utilVec31Interactable=new THREE.Vector3;this.utilVec32Interactable=new THREE.Vector3;c=this.keybindingsDefault={};c.pointer="pointer";c.w=c.up_arrow="w";c.s=c.down_arrow="s";c.a=c.left_arrow="a";c.d=c.right_arrow="d";c.q="q";c.e="e";c["1"]="1";c["2"]="2";c["3"]="3";
c["4"]="4";c["5"]="5";c["6"]="6";c.escape="escape";c.space="space";c.alwaysAvailable=[];this.set_keybindings(c);this.actions.add([{names:"w up_arrow",eventCallbacks:{down:function(){e.move_state_change("forward")},up:function(){e.move_state_change("forward",!0)}},deactivateCallbacks:"up",options:{type:this.options.actionTypes.movement}},{names:"s down_arrow",eventCallbacks:{down:function(){e.move_state_change("back")},up:function(){e.move_state_change("back",!0)}},deactivateCallbacks:"up",options:{type:this.options.actionTypes.movement}},
{names:"a left_arrow",eventCallbacks:{down:function(){e.move_state_change("left")},up:function(){e.move_state_change("left",!0)}},deactivateCallbacks:"up",options:{type:this.options.actionTypes.movement}},{names:"d right_arrow",eventCallbacks:{down:function(){e.move_state_change("right")},up:function(){e.move_state_change("right",!0)}},deactivateCallbacks:"up",options:{type:this.options.actionTypes.movement}},{names:"space",eventCallbacks:{down:function(){e.move_state_change("up")},up:function(){e.move_state_change("up",
!0)}},deactivateCallbacks:"up",options:{type:this.options.actionTypes.movement}},{names:"pointer",eventCallbacks:{mousemove:$.proxy(this.hover,this)},activeCheck:function(){return e.targetHover instanceof THREE.Object3D},deactivateCallbacks:"mousemove",options:{type:this.options.actionTypes.targetting}},{names:"pointer",eventCallbacks:{tap:$.proxy(this.select,this),doubletap:$.proxy(this.interact,this)},activeCheck:function(){return e.target instanceof THREE.Object3D},deactivateCallbacks:"tap",options:{type:this.options.actionTypes.targetting}},
{names:"pointer",eventCallbacks:{dragstart:$.proxy(function(){this.hover();a.cameraControls.rotate_start.apply(a.cameraControls,arguments)},this),drag:$.proxy(a.cameraControls.rotate,a.cameraControls),dragend:$.proxy(a.cameraControls.rotate_stop,a.cameraControls),wheel:$.proxy(a.cameraControls.zoom,a.cameraControls)},activeCheck:function(){return a.cameraControls.rotating},options:{priority:1,silencing:!0}}]);this.tooltip=new k.Instance(d.tooltip);a.domElements.$playerState=$("#playerState");a.domElements.$playerHealth=
$(".player-health");a.domElements.$playerHealthBar=a.domElements.$playerHealth.find(".bar");a.domElements.$playerTarget=$("#playerTarget");a.domElements.$playerTargetPortrait=$("#playerTargetPortrait");a.domElements.$playerTargetImage=$(".target-image");a.domElements.$playerTargetName=$(".target-name");a.domElements.$playerTargetInteract=$("#playerTargetInteract");this.onHurt.add(this.update_ui_state,this);this.onDead.add(this.update_ui_state,this);this.onRespawned.add(this.update_ui_state,this);
this.update_ui_state()}function m(d){b.Instance.prototype.supr.set_scene.call(this,d);this._scene instanceof THREE.Scene?(a.signals.onGamePaused.add(this.pause,this),a.signals.onGamePointerLeft.add(this.pause,this),this.controllable=!0):(a.signals.onGamePaused.remove(this.pause,this),a.signals.onGamePointerLeft.remove(this.pause,this),this.controllable=!1)}function n(){a.domElements.$playerHealthBar.css("width",this.state.health/this.options.stats.healthMax*100+"%")}function o(){b.Instance.prototype.supr.die.apply(this,
arguments);this.controllable=!1;f.dom_fade({element:a.domElements.$playerState})}function p(){b.Instance.prototype.supr.respawn.apply(this,arguments);this.face_local_direction(new THREE.Vector3(0,0,-1));a.cameraControls.target=void 0;a.cameraControls.target=this;a.cameraControls.rotateTarget=!0;f.dom_fade({element:a.domElements.$playerState,opacity:1})}function h(d,e){return{pointer:e||f.get_pointer(d),camera:a.camera,far:this.options.interactions.distanceTarget+i.distance_between(this.matrixWorld.getPosition(),
a.camera.position),objects:a.scene.dynamics,octrees:a.scene.octree,objectOnly:!0}}function q(d){var e=!0,c,b=this.targetHover;if(typeof d!=="undefined"&&(c=d.event||d,d=f.get_pointer(c),c=j.raycast(h.call(this,c,d)),c instanceof THREE.Object3D&&c.interactive===!0))e=!1,this.targetHover=c,this.targetHover!==b&&(a.domElements.$game.css("cursor","pointer"),this.tooltip.content(this.targetHover.name).show(d));if(e===!0)this.targetHover=void 0,this.targetHover!==b&&(a.domElements.$game.css("cursor","auto"),
this.tooltip.hide())}function r(d){var e,c=this.target;if(typeof d!=="undefined")d instanceof THREE.Object3D?e=d:d.target instanceof THREE.Object3D?e=d.target:(d=d.event,e=j.raycast(h.call(this,d)));b.Instance.prototype.supr.select.call(this,e);this.target===this.targetHover&&this.tooltip.hide();this.target!==c&&(this.target instanceof g.Instance?(f.dom_fade({element:a.domElements.$playerTarget,opacity:1}),a.domElements.$playerTargetImage.css("background-image","url( '"+a.pathToAssets+this.target.options.assetsPath+
".png' )"),a.domElements.$playerTargetName.html(this.target.name),a.domElements.$playerTargetInteract.off(".interact").on("tap.interact",$.proxy(this.interact,this)),this.interaction_distance_check()):(f.dom_fade({element:a.domElements.$playerTarget}),a.domElements.$playerTargetInteract.off(".interact")))}function s(){this.targetInteract instanceof g.Instance&&this.silence();this.interaction_distance_check()?(this.targetInteract=this.target,this.actions.execute("communicate","greeting",{target:this.targetInteract})):
(this.tooltip.show().content("Too far away!"),this.tooltipNeedsUpdate=!0)}function t(){var d=this.options.interactions,b,c,f=!1;if(this.target instanceof g.Instance)if(b=this.utilVec31Interactable.copy(this.matrixWorld.getPosition()),c=this.utilVec32Interactable.copy(this.target.matrixWorld.getPosition()),i.distance_between(b,c)<=d.distance){if(f=!0,a.domElements.$playerTargetInteract.removeClass("disabled"),this.tooltipNeedsUpdate===!0)this.tooltipNeedsUpdate=!1,this.tooltip.content(this.target.name)}else a.domElements.$playerTargetInteract.addClass("disabled");
return f}function u(){b.Instance.prototype.supr.silence.apply(this,arguments);this.targetInteract=void 0}function v(a){this.keybindings=$.extend(!0,this.keybindings||{},a)}function w(a,b,c){var g=this.keybindings,b=g[b]||b,g=f.index_of_value(g.alwaysAvailable,b)!==-1;if(this.state.controllable===!0||g)this.actions.execute(b,c,{event:a,allowDefault:g||f.paused})}function x(){this.hover()}function y(){var a=this.state;b.Instance.prototype.supr.update.apply(this,arguments);a.dead!==!0&&a.moving===!0&&
this.interaction_distance_check()}var a=f.shared=f.shared||{},b={},g,k,i,j;f.asset_register("js/kaiopua/characters/Player.js",{data:b,requirements:"js/kaiopua/characters/Character.js,js/kaiopua/ui/Tooltip.js,js/kaiopua/utils/MathHelper.js,js/kaiopua/utils/VectorHelper.js,js/kaiopua/utils/KeyHelper.js,js/kaiopua/utils/ObjectHelper.js,js/kaiopua/utils/RayHelper.js".split(","),callbacksOnReqs:function(d,e,c,f,h,A,z){g=d;k=e;i=f;j=z;b.options={physics:{volumetric:!0},actionTypes:{movement:"action_movement",
targetting:"action_targetting",ui:"action_ui"},stats:{respawnOnDeath:!0},movement:{move:{speed:3},jump:{speedStart:3,duration:200}},interactions:{distanceTarget:600,distance:375},dialogues:{greeting:["Hello!","Heyo!","Hi!"]}};b.Instance=l;b.Instance.prototype=new g.Instance;b.Instance.prototype.constructor=b.Instance;b.Instance.prototype.supr=g.Instance.prototype;b.Instance.prototype.set_scene=m;b.Instance.prototype.update_ui_state=n;b.Instance.prototype.die=o;b.Instance.prototype.respawn=p;b.Instance.prototype.hover=
q;b.Instance.prototype.select=r;b.Instance.prototype.interact=s;b.Instance.prototype.interaction_distance_check=t;b.Instance.prototype.silence=u;b.Instance.prototype.set_keybindings=v;b.Instance.prototype.trigger_action=w;b.Instance.prototype.pause=x;b.Instance.prototype.update=y;Object.defineProperty(b.Instance.prototype,"controllable",{get:function(){return this.state.controllable},set:function(b){var c=this.state.controllable;this.state.controllable=b;this.state.controllable!==c&&(this.state.controllable===
!0?a.signals.onGameInput.add(this.trigger_action,this):(a.signals.onGameInput.remove(this.trigger_action,this),this.actions.clear_active()))}});Object.defineProperty(b.Instance.prototype,"target",{get:function(){return this._target},set:function(a){this._target=a}})},wait:!0})})(KAIOPUA);
