(function(e){function y(a){a=a||{};k.universeGravitySource=a.universeGravitySource instanceof THREE.Vector3?a.universeGravitySource:k.universeGravitySource;k.universeGravityMagnitude=a.universeGravityMagnitude instanceof THREE.Vector3?a.universeGravityMagnitude:k.universeGravityMagnitude;this.utilVec31Update=new THREE.Vector3;this.utilVec32Update=new THREE.Vector3;this.utilVec33Update=new THREE.Vector3;this.utilVec31Apply=new THREE.Vector3;this.utilVec31Velocity=new THREE.Vector3;this.utilVec32Velocity=
new THREE.Vector3;this.utilVec33Velocity=new THREE.Vector3;this.utilVec34Velocity=new THREE.Vector3;this.utilQ1Velocity=new THREE.Quaternion;this.octree=new THREE.Octree;this.bodies=[];this.bodiesGravity=[];this.bodiesDynamic=[];this.obstacles=[]}function z(a){p.call(this,a,!0)}function A(a){p.call(this,a)}function p(a,b){var d,h,c;if(typeof a!=="undefined"&&a.rigidBody instanceof o.Instance)d=a.rigidBody,h=d.collider,d.velocityMovement.reset(),d.velocityGravity.reset(),c=e.index_of_value(this.bodies,
d),b===!0?(d.setupOnNextUpdate=!0,c===-1&&this.bodies.push(d),d.gravitySource===!0&&e.array_cautious_add(this.bodiesGravity,d),d.dynamic===!0?e.array_cautious_add(this.bodiesDynamic,d):this.octree.add(a,h instanceof o.MeshCollider?!0:!1),a instanceof n.Instance&&e.array_cautious_add(this.obstacles,a)):(c!==-1&&this.bodies.splice(c,1),d.gravitySource===!0&&e.array_cautious_remove(this.bodiesGravity,d),d.dynamic===!0?e.array_cautious_remove(this.bodiesDynamic,d):this.octree.remove(a),a instanceof n.Instance&&
e.array_cautious_remove(this.obstacles,a));if(typeof a.children!=="undefined")for(d=0,h=a.children.length;d<h;d++)c=a.children[d],p.call(this,c,b)}function B(a,b){var d,h,c,f,j,e=this.utilVec31Update,i=this.utilVec32Update,g=this.utilVec33Update,l,m,n;for(d=0,h=this.bodiesDynamic.length;d<h;d++)c=this.bodiesDynamic[d],f=c.object,m=c.velocityGravity,n=c.velocityMovement,c.setupOnNextUpdate===!0?(c.setupOnNextUpdate=!1,f.updateMatrixWorld(!0),c.change_gravity_body(c.find_gravity_body_closest(this.bodiesGravity)),
l=1):l=c.lerpDelta,j=c.gravityBody,j instanceof o.Instance?(j=j.object,e.copy(j.matrixWorld.getPosition()),i.copy(c.gravityMagnitude||k.universeGravityMagnitude)):(e.copy(k.universeGravitySource),i.copy(k.universeGravityMagnitude)),i.multiplyScalar(b),m.forceDelta.addSelf(i),t.rotate_relative_to_source(f.quaternion,f.position,e,c.axes.up,c.axes.forward,l,c),u.call(this,c,n),g.sub(f.position,e).normalize(),m.relativeTo=g,u.call(this,c,m),c.find_gravity_body(this.bodiesGravity,a)}function u(a,b){var d=
b==a.velocityGravity,h=a.object,c=h.position,f=b.forceRotated,j,e,i,g,k,m,o,v=this.utilVec31Velocity,p=this.utilVec32Velocity,t=this.utilVec33Velocity,q=this.utilVec34Velocity,r,u,s;b.update();if(a.dynamic!==!0||f.isZero()===!0)b.clear();else{b.moving=!0;j=f.length();e=a.bounds_in_direction(f).length();g={octrees:this.octree,origin:c,direction:f,offsets:b.offsetsRotated,far:j+(b===a.velocityMovement?a.radius:e),ignore:h};i=w.raycast(g);d&&i&&h.jumping===!0&&(f.multiplyScalar(-1),(m=w.raycast(g))?
b.forceInternal.set(0,0,0):f.multiplyScalar(-1));m=x.call(this,c,b,i,j,e,!0);if(i&&b.options.collisionAngleThreshold<b.options.collisionAngleThresholdMax&&(v.copy(f).normalize(),q.copy(i.normal),i.object.matrixWorld.rotateAxis(q),f=l.angle_between_vectors(v,q),f=Math.PI-f,f>=b.options.collisionAngleThreshold)){if(b!==a.velocityMovement)u=a.velocityMovement.forceRotated,u.dot(q)<0?(a.velocityMovement.dampingPre.multiplyScalar(a.velocityMovement.options.dampingDecay),(o=a.velocityMovement.intersection&&
i)&&a.velocityMovement.dampingPre.multiplyScalar(0)):l.clamp_scalar(a.velocityMovement.dampingPre.addScalar(1-a.velocityMovement.options.dampingDecay),0,1);f<b.options.collisionAngleThresholdMax&&(p.copy(l.axis_between_vectors(v,q)),t.copy(l.axis_between_vectors(q,p)),r=l.q_to_axis(v,t),r instanceof THREE.Quaternion&&(m=!1,b.rotate(r),k=w.raycast(g),x.call(this,c,b,k,j,e),b.rotate(r.inverse())))}if(b.collision)s=b.collision.object;if((s||d!==!0)&&b.obstacle instanceof n.Instance&&b.obstacle!==s)b.obstacle.unaffect(h),
delete b.obstacle;if(s instanceof n.Instance)b.obstacle=s,s.affect(h,{velocity:b});d&&r instanceof THREE.Quaternion!==!0&&l.clamp_scalar(a.velocityMovement.dampingPre.addScalar(1-a.velocityMovement.options.dampingDecay),0,1);if(r instanceof THREE.Quaternion&&o!==!0&&!k)b.sliding=!0;else if(i)b.sliding=!1;m===!0?b.clear():b.damp()}}function x(a,b,d,e,c,f){var g;b.forceApplied.copy(b.forceRotated);d&&(c=d.distance-c,c-e<=0&&(b.forceApplied.multiplyScalar(c/e),g=!0));a.addSelf(b.forceApplied);if(f===
!0)return b.intersection=d,g===!0?(b.collision=d,b.moving=!1):b.collision=!1,g}var k=e.shared=e.shared||{},g={},o,n,w,l,t;e.asset_register("js/kaiopua/physics/Physics.js",{data:g,requirements:"js/kaiopua/physics/RigidBody.js,js/kaiopua/physics/Obstacle.js,js/kaiopua/utils/MathHelper.js,js/kaiopua/utils/VectorHelper.js,js/kaiopua/utils/RayHelper.js,js/kaiopua/utils/ObjectHelper.js,js/kaiopua/utils/PhysicsHelper.js,js/lib/three/ThreeOctree.min.js".split(","),callbacksOnReqs:function(a,b,d,e,c,f,j){o=
a;n=b;l=e;w=c;t=j;g.Instance=y;g.Instance.prototype={};g.Instance.prototype.constructor=g.Instance;g.Instance.prototype.add=z;g.Instance.prototype.remove=A;g.Instance.prototype.update=B},wait:!0})})(KAIOPUA);
