(function(b){function n(a){g.Instance.call(this,a);this.acceleration=0;this.accelerationDamping=o;this.speedLerp=p;this.speedMax=j;this.speedMin=k;this.speed=0;this.direction=new THREE.Vector3(1,1,1);this.directionChangeChance=new THREE.Vector3(h,h,h);this.angleSeed=Math.PI*2;this.angleZ=this.angleY=this.angleX=0;this.rangeMax=new THREE.Vector3(e,e,e);this.rangeMin=new THREE.Vector3(-e,-e,-e);this.originTarget=new THREE.Vector3;this.origin=new THREE.Vector3;this.positionOffsetTarget=new THREE.Vector3;
this.positionOffset=new THREE.Vector3;this.forApply={origin:new THREE.Vector3,positionOffset:new THREE.Vector3};this.reset()}function q(){var a=this.forApply;a.origin.set(0,0,0);a.positionOffset.set(0,0,0)}function r(a){a=a||{};a.origin&&this.originTarget.copy(a.origin);a.rangeMax instanceof THREE.Vector3?this.rangeMax.copy(a.rangeMax):b.is_number(a.rangeMax)&&this.rangeMax.set(a.rangeMax,a.rangeMax,a.rangeMax);a.rangeMin instanceof THREE.Vector3?this.rangeMin.copy(a.rangeMin):b.is_number(a.rangeMin)&&
this.rangeMin.set(a.rangeMin,a.rangeMin,a.rangeMin);a.direction instanceof THREE.Vector3?this.direction.copy(a.direction):b.is_number(a.direction)&&this.direction.set(a.direction,a.direction,a.direction);a.directionChangeChance instanceof THREE.Vector3?this.directionChangeChance.copy(a.directionChangeChance):b.is_number(a.directionChangeChance)&&this.directionChangeChance.set(a.directionChangeChance,a.directionChangeChance,a.directionChangeChance);this.waveX=typeof a.waveX==="boolean"?a.waveX:!1;
this.waveY=typeof a.waveY==="boolean"?a.waveY:!1;this.waveZ=typeof a.waveZ==="boolean"?a.waveZ:!1;this.angleSeed=b.is_number(a.angleSeed)?a.angleSeed:this.angleSeed;this.angleX=b.is_number(a.angleX)?a.angleX:b.is_number(a.angle)?a.angle:Math.random()*this.angleSeed*2-this.angleSeed;this.angleY=b.is_number(a.angleY)?a.angleY:b.is_number(a.angle)?a.angle:Math.random()*this.angleSeed*2-this.angleSeed;this.angleZ=b.is_number(a.angleZ)?a.angleZ:b.is_number(a.angle)?a.angle:Math.random()*this.angleSeed*
2-this.angleSeed;this.accelerationDamping=b.is_number(a.accelerationDamping)?a.accelerationDamping:this.accelerationDamping;this.speedLerp=b.is_number(a.speedLerp)?a.speedLerp:this.speedLerp;this.waveX===!0||this.waveY===!0||this.waveZ===!0?(this.speedMax=b.is_number(a.speedMax)?a.speedMax:b.is_number(a.speed)?a.speed:s,this.speedMin=b.is_number(a.speedMin)?a.speedMin:b.is_number(a.speed)?a.speed:t):(this.speedMax=b.is_number(a.speedMax)?a.speedMax:b.is_number(a.speed)?a.speed:j,this.speedMin=b.is_number(a.speedMin)?
a.speedMin:b.is_number(a.speed)?a.speed:k);this.speed=Math.random()*(this.speedMax-this.speedMin)+this.speedMin;a.snapToInitial===!0&&this.origin.copy(this.originTarget);d.Instance.prototype.supr.start.call(this,a)}function u(){var a=this.rangeMax,b=this.rangeMin,c;if(this.speed!==0){this.reset();this.acceleration+=this.speed;i.lerp_snap(this.origin,this.originTarget,this.speedLerp,l);if(this.waveX===!0||this.waveY===!0||this.waveZ===!0){if(this.waveX===!0)this.angleX=f.rad_between_PI(this.angleX+
this.acceleration),c=Math.sin(this.angleX),this.positionOffsetTarget.x=c>0?c*a.x:-c*b.x;if(this.waveY===!0)this.angleY=f.rad_between_PI(this.angleY+this.acceleration),c=Math.sin(this.angleY),this.positionOffsetTarget.y=c>0?c*a.y:-c*b.y;if(this.waveZ===!0)this.angleZ=f.rad_between_PI(this.angleZ+this.acceleration),c=Math.sin(this.angleZ),this.positionOffsetTarget.z=c>0?c*a.z:-c*b.z}else Math.random()<=this.directionChangeChance.x&&(this.direction.x*=-1),Math.random()<=this.directionChangeChance.y&&
(this.direction.y*=-1),Math.random()<=this.directionChangeChance.z&&(this.direction.z*=-1),this.positionOffsetTarget.set(f.clamp(this.positionOffsetTarget.x+this.acceleration*this.direction.x,b.x,a.x),f.clamp(this.positionOffsetTarget.y+this.acceleration*this.direction.y,b.y,a.y),f.clamp(this.positionOffsetTarget.z+this.acceleration*this.direction.z,b.z,a.z));i.lerp_snap(this.positionOffset,this.positionOffsetTarget,this.speedLerp,l);this.acceleration*=this.accelerationDamping;this.integrate(this)}}
function v(a){var b=this.forApply;a.origin&&b.origin.addSelf(a.origin);a.positionOffset&&b.positionOffset.addSelf(a.positionOffset)}function w(){var a;if(this.parent instanceof g.Instance!==!0&&this.object instanceof THREE.Object3D)a=this.forApply,m.object_orbit_source(this.object,a.origin,a.positionOffset)}b.shared=b.shared||{};var d={},g,f,i,m,o=0.9,p=0.01,j=0.1,s=0.001,k=0.001,t=1.0E-4,l=0.01,e=100,h=0.01;b.asset_register("js/kaiopua/model/WanderUpdater.js",{data:d,requirements:["js/kaiopua/core/PropertyUpdater.js",
"js/kaiopua/utils/MathHelper.js","js/kaiopua/utils/VectorHelper.js","js/kaiopua/utils/ObjectHelper.js"],callbacksOnReqs:function(a,b,c,e){g=a;f=b;i=c;m=e;d.Instance=n;d.Instance.prototype=new g.Instance;d.Instance.prototype.constructor=d.Instance;d.Instance.prototype.supr=g.Instance.prototype;d.Instance.prototype.start=r;d.Instance.prototype.reset=q;d.Instance.prototype.step=u;d.Instance.prototype.integrate=v;d.Instance.prototype.apply=w},wait:!0})})(KAIOPUA);
