(function(d){function u(a){a=a||{};a.options=$.extend(!0,{},b.options,a.options);l.Instance.call(this,a);this.numClouds=d.is_number(a.numClouds)?a.numClouds:b.numClouds;this.cloudParameters=a.cloudParameters;this.cloudInitAxis=d.is_number(a.cloudInitAxis)?a.cloudInitAxis:b.cloudInitAxis;this.cloudInitAngle=d.is_number(a.cloudInitAngle)?a.cloudInitAngle:b.cloudInitAngle;this.cloudRotateTowardWorld=typeof a.cloudRotateTowardWorld==="boolean"?a.cloudRotateTowardWorld:b.cloudRotateTowardWorld;this.cloudOpacityByDistance=
m.clamp(d.is_number(a.cloudOpacityByDistance)?a.cloudOpacityByDistance:b.cloudOpacityByDistance,-1,1);this.cloudRotateUtilVec31=new THREE.Vector3;this.cloudRotateUtilVec32=new THREE.Vector3;this.cloudScaleMax=d.is_number(a.cloudScaleMax)?a.cloudScaleMax:b.cloudScaleMax;this.cloudScaleMin=d.is_number(a.cloudScaleMin)?a.cloudScaleMin:b.cloudScaleMin;this.cloudBoundRadius=d.is_number(a.cloudBoundRadius)?a.cloudBoundRadius:b.cloudBoundRadius;this.cloudDistanceFromSurfaceMin=d.is_number(a.cloudDistanceFromSurfaceMin)?
a.cloudDistanceFromSurfaceMin:b.cloudDistanceFromSurfaceMin;this.cloudDistanceFromSurfaceMax=d.is_number(a.cloudDistanceFromSurfaceMax)?a.cloudDistanceFromSurfaceMax:b.cloudDistanceFromSurfaceMax;this.cloudRangeWander=d.is_number(a.cloudRangeWander)?a.cloudRangeWander:b.cloudRangeWander;this.cloudAnimationDuration=d.is_number(a.cloudAnimationDuration)?a.cloudAnimationDuration:b.cloudAnimationDuration;this.cloudsGeometry=a.cloudsGeometry||b.cloudsGeometry;this.bounds=a.bounds||{min:new THREE.Vector3,
max:new THREE.Vector3};this.layout=a.layout;this.zones=d.type(a.zones)==="array"?a.zones:b.zones;this.clouds=[];this.world=a.world}function v(a){this._world=a;this.set_clouds()}function r(a){var b,e,f;if(d.is_number(a)&&a>=0)this.numClouds=a;if(this.clouds.length>this.numClouds){f=this.clouds.splice(this.numClouds,this.clouds.length-this.numClouds);for(a=0,b=f.length;a<b;a++)e=f[a],this.remove(e)}else if(this.clouds.length<this.numClouds)for(a=this.clouds.length,b=this.numClouds;a<b;a++)e=new s.Instance(this.cloudParameters),
this.clouds.push(e),this.add(e)}function w(){var a,j,e,f;this.bounds.min.set(-this.cloudBoundRadius,-this.cloudBoundRadius,-this.cloudBoundRadius);this.bounds.max.set(this.cloudBoundRadius,this.cloudBoundRadius,this.cloudBoundRadius);if(this._world instanceof l.Instance){e=q.extract_children_from_objects(this._world,this._world);for(a=0,j=e.length;a<j;a++)f=e[a],this.bounds=t.push_bounds(f,this.bounds)}if(d.is_array(this.layout)){var c,h,i=this.cloudRotateUtilVec31,k=this.cloudRotateUtilVec32;r.call(this,
this.layout.length);for(a=0,j=this.numClouds;a<j;a++)e=this.clouds[a],c=this.layout[a],f=c.position,h=c.rotation,c=c.scale,f instanceof THREE.Vector3&&e.position.copy(f),h instanceof THREE.Quaternion?e.quaternion.copy(h):h instanceof THREE.Vector3?e.quaternion.setFromEuler(h):this.cloudRotateTowardWorld&&(i.copy(o.cardinalAxes.forward),k.copy(o.cardinalAxes.up),e.quaternion.multiplyVector3(i),e.quaternion.multiplyVector3(k),p.rotate_relative_to_source(e.quaternion,e.position,this._world,k,i)),d.is_number(c)?
e.scale.set(c,c,c):c instanceof THREE.Vector3?e.scale.copy(c):(c=Math.random()*(this.cloudScaleMax-this.cloudScaleMin)+this.cloudScaleMin,e.scale.set(c,c,c))}else{a=e;f=this.bounds.min;h=this.bounds.max;var g,n;j=this.cloudRotateUtilVec31;e=this.cloudRotateUtilVec32;a=d.type(a)==="array"?a:q.extract_children_from_objects(this._world,this._world);k=Math.abs(m.max_magnitude(f.x,f.y,f.z,h.x,h.y,h.z));r.call(this);for(f=0,h=this.numClouds;f<h;f++)i=this.clouds[f],g=d.array_random_value(this.zones),c=
g.polar&&d.is_number(g.polar.min)&&d.is_number(g.polar.max)?g.polar:b.zonePolar,g=g.azimuth&&d.is_number(g.azimuth.min)&&d.is_number(g.azimuth.max)?g.azimuth:b.zoneAzimuth,c=m.clamp(Math.random()*(c.max-c.min)+c.min,0,Math.PI),n=m.clamp(Math.random()*(g.max-g.min)+g.min,0,Math.PI*2),g=k*Math.cos(n)*Math.sin(c),n=k*Math.sin(n)*Math.sin(c),c=k*Math.cos(c),i.position.set(g,n,c),i.quaternion.setFromAxisAngle(this.cloudInitAxis,this.cloudInitAngle+Math.atan2(g,c)),this.cloudRotateTowardWorld&&(j.copy(o.cardinalAxes.forward),
e.copy(o.cardinalAxes.up),i.quaternion.multiplyVector3(j),i.quaternion.multiplyVector3(e),p.rotate_relative_to_source(i.quaternion,i.position,this._world,j,e)),c=Math.random()*(this.cloudScaleMax-this.cloudScaleMin)+this.cloudScaleMin,i.scale.set(c,c,c),c=Math.random()*(this.cloudDistanceFromSurfaceMax-this.cloudDistanceFromSurfaceMin)+this.cloudDistanceFromSurfaceMin,p.pull_to_source(i,this._world,a,c)}}function x(a){var b,e,d,a=a||{};for(b=0,e=this.clouds.length;b<e;b++)d=this.clouds[b],a.stop===
!0?d.morphs.stop_all():d.morphs.play("idle",{duration:this.cloudAnimationDuration,loop:!0,startDelay:!0})}var o=d.shared=d.shared||{},b={},l,s,m,q,t,p;d.asset_register("js/kaiopua/env/Sky.js",{data:b,requirements:"js/kaiopua/core/Model.js,js/kaiopua/env/Cloud.js,js/kaiopua/utils/MathHelper.js,js/kaiopua/utils/SceneHelper.js,js/kaiopua/utils/ObjectHelper.js,js/kaiopua/utils/PhysicsHelper.js".split(","),callbacksOnReqs:function(a,d,e,f,c,h){l=a;s=d;m=e;q=f;t=c;p=h;b.options={intersectable:!1};b.numClouds=
10;b.cloudInitAxis=new THREE.Vector3(0,1,0);b.cloudInitAngle=0;b.cloudRotateTowardWorld=!0;b.cloudOpacityByDistance=0;b.cloudScaleMax=6;b.cloudScaleMin=1;b.cloudBoundRadius=1500;b.cloudDistanceFromSurfaceMin=1E3;b.cloudDistanceFromSurfaceMax=3E3;b.cloudRangeWander=200;b.cloudAnimationDuration=3E3;b.zonePolar={min:0,max:Math.PI};b.zoneAzimuth={min:0,max:Math.PI*2};b.zones=[{polar:b.zonePolar,azimuth:b.zoneAzimuth}];b.Instance=u;b.Instance.prototype=new l.Instance;b.Instance.prototype.constructor=b.Instance;
b.Instance.prototype.supr=l.Instance.prototype;b.Instance.prototype.set_world=v;b.Instance.prototype.set_clouds=w;b.Instance.prototype.animate=x;Object.defineProperty(b.Instance.prototype,"world",{get:function(){return this._world},set:function(a){this.set_world(a)}})},wait:!0})})(KAIOPUA);
