var HAMMER=function(j){var u,m,d,e,p;function E(a){$(document)[a?"off":"on"]("selectstart",L);$("html")[a?"removeClass":"addClass"]("unselectable");document.unselectable=a?"off":"on"}function F(a){var a={down:a>=45&&a<135,left:a>=135||a<=-135,up:a<-45&&a>-135,right:a>=-45&&a<=45},b,c;for(c in a)if(a[c]){b=c;break}return b}function y(a){a=a||window.event;if(r){for(var b=[],c=a.touches.length>0?a.touches:a.changedTouches,g=0,d=c.length;g<d;g++)a=c[g],b.push({x:a.pageX,y:a.pageY});return b}else return b=
document,c=b.body,[{x:a.pageX||a.clientX+(b&&b.scrollLeft||c&&c.scrollLeft||0)-(b&&b.clientLeft||c&&c.clientLeft||0),y:a.pageY||a.clientY+(b&&b.scrollTop||c&&c.scrollTop||0)-(b&&b.clientTop||c&&c.clientTop||0)}]}function G(a,b){if(a.length==2&&b.length==2){var c,g;c=a[0].x-a[1].x;g=a[0].y-a[1].y;var d=Math.sqrt(c*c+g*g);c=b[0].x-b[1].x;g=b[0].y-b[1].y;return Math.sqrt(c*c+g*g)/d}return 0}function H(a,b){if(a.length==2&&b.length==2){var c,g;c=a[0].x-a[1].x;g=a[0].y-a[1].y;var d=Math.atan2(g,c)*180/
Math.PI;c=b[0].x-b[1].x;g=b[0].y-b[1].y;return Math.atan2(g,c)*180/Math.PI-d}return 0}function L(){return!1}function M(a,b,c){for(var b=b.split(" "),d=0,e=b.length;d<e;d++)a.addEventListener?a.addEventListener(b[d],c,!1):document.attachEvent&&a.attachEvent("on"+b[d],c)}function i(a,b){var c,d,e,f=!1;for(c=0,d=v.length;c<d;c++)if(e=v[c],typeof e["on"+a]==="function"){b.touches=y(b.originalEvent);b.position=b.position||b.touches;b.type=a;if(!b.target)b.target=e.element;e["on"+a].call(e,b);f=!0;break}return f}
function I(a){var b=a.type;if(b===z)w===!0&&(e=y(a),s.transform(a)||s.drag(a)),a.preventDefault();else if(b===A||b===B){$(window).off(z+" "+A+" "+B,I);if(w===!0){if(h!=="transform"&&a.touches&&a.touches.length>0)return!1;typeof o!=="undefined"&&(clearTimeout(o),o=void 0);b=h=="drag";s.swipe(a);b?(i("dragend",{originalEvent:a,direction:n,distance:k,angle:l}),E(!0)):h=="transform"?i("transformend",{originalEvent:a,center:p,scale:G(d,e),rotation:H(d,e)}):s.tap(J);K=h;i("release",{originalEvent:a,gesture:h})}v=
[];C=!1;h=null;d=void 0;e=void 0;p=void 0;w=q=!1;l=k=0}}var f={prevent_default:!1,css_hacks:!0,swipe:!0,swipe_time:200,swipe_min_distance:20,drag:!0,drag_vertical:!0,drag_horizontal:!0,drag_min_distance:20,transform:!0,scale_treshold:0.1,rotation_treshold:15,tap:!0,tap_double:!0,tap_max_interval:200,tap_max_distance:10,tap_double_distance:20,hold:!0,hold_timeout:500},r=Modernizr?Modernizr.touch:"ontouchstart"in window,N=r?"touchstart":"mousedown",z=r?"touchmove":"mousemove",A=r?"touchend":"mouseup",
B=r?"touchcancel":"",w=!1,O=0,C=!1,v=[],J;d=void 0;e=void 0;p=void 0;var k=0,l=0,n=0,q=!1,h,K,t={x:0,y:0},D,x,o;u=void 0;m=void 0;var s={hold:function(a){f.hold&&(h="hold",typeof o!=="undefined"&&(clearTimeout(o),o=void 0),o=setTimeout(function(){h=="hold"&&i("hold",{originalEvent:a,position:d})},f.hold_timeout))},swipe:function(a){if(e){var b=e[0].x-d[0].x,c=e[0].y-d[0].y;k=Math.sqrt(b*b+c*c);var g=(new Date).getTime()-x;f.swipe&&f.swipe_time>g&&k>f.swipe_min_distance&&(l=Math.atan2(e[0].y-d[0].y,
e[0].x-d[0].x)*180/Math.PI,n=F(l),h="swipe",i("swipe",{originalEvent:a,direction:n,distance:k,distanceX:b,distanceY:c,angle:l}))}},drag:function(a){var b=e[0].x-d[0].x,c=e[0].y-d[0].y,g;k=Math.sqrt(b*b+c*c);if(f.drag&&k>f.drag_min_distance||h=="drag")l=Math.atan2(e[0].y-d[0].y,e[0].x-d[0].x)*180/Math.PI,n=F(l),g=n=="up"||n=="down",(g&&!f.drag_vertical||!g&&!f.drag_horizontal)&&k>f.drag_min_distance||(h="drag",q&&(i("dragstart",{originalEvent:a,position:d,direction:n,distance:k,distanceX:b,distanceY:c,
angle:l}),q=!1),i("drag",{originalEvent:a,direction:n,distance:k,distanceX:b,distanceY:c,angle:l}))},transform:function(a){var b,c;if(f.transform){if((a.touches?a.touches.length:1)!=2)return!1;b=H(d,e);c=G(d,e);if(h!="drag"&&(h=="transform"||Math.abs(1-c)>f.scale_treshold||Math.abs(b)>f.rotation_treshold))return h="transform",p={x:(e[0].x+e[1].x)/2-m,y:(e[0].y+e[1].y)/2-u},q&&(q=!1,i("transformstart",{originalEvent:a,position:d,center:p,scale:c,rotation:b})),i("transform",{originalEvent:a,center:p,
scale:c,rotation:b}),!0}return!1},tap:function(a){var b=(new Date).getTime(),c=b-x,g;if(!f.hold||f.hold&&f.hold_timeout>c)t&&f.tap_double&&K=="tap"&&x-D<f.tap_max_interval&&t&&d&&Math.max(Math.abs(t[0].x-d[0].x),Math.abs(t[0].y-d[0].y))<f.tap_double_distance?(h="double_tap",D=null,i("doubletap",{originalEvent:a,position:d})):(c=e?Math.abs(e[0].x-d[0].x):0,g=e?Math.abs(e[0].y-d[0].y):0,k=Math.max(c,g),k<f.tap_max_distance&&(h="tap",D=b,t=d,f.tap&&i("tap",{originalEvent:a,position:d})))}};j.options=
f;j.option=function(a,b){typeof b!=="undefined"&&(f[a]=b);return f[a]};j.Instance=function(a){var b=this;b.id=O++;b.element=a;M(a,N,function(a){var e,f,h,i,j;if(C!==!0)C=!0,J=a,x=(new Date).getTime(),d=y(a),w=q=!0,l=k=0,e=b.element,f=e.getBoundingClientRect(),h=e.clientTop||document.body.clientTop||0,i=e.clientLeft||document.body.clientLeft||0,j=window.pageYOffset||e.scrollTop||document.body.scrollTop,e=window.pageXOffset||e.scrollLeft||document.body.scrollLeft,u=f.top+j-h,m=f.left+e-i,E(!1),$(window).on(z+
" "+A+" "+B,I),s.hold(a);v.push(b)})};return j}(HAMMER||{});(function(j){j.each("hold,tap,doubletap,transformstart,transform,transformend,dragstart,drag,dragend,swipe,release".split(","),function(u,m){j.event.special[m]={setup:function(){var d=j(this);d.data("hammerjs")||d.data("hammerjs",new HAMMER.Instance(this));d.data("hammerjs")["on"+m]=function(e){d.trigger(j.Event(m,e))}},teardown:function(){var d=j(this).data("hammerjs");d&&d["on"+m]&&delete d["on"+m]}}})})(jQuery);
