var TWEEN=TWEEN||function(){var a=[];return{REVISION:"6",getAll:function(){return a},removeAll:function(){a=[]},add:function(c){a.push(c)},remove:function(c){for(var b=a.length-1;b>=0;b--)if(c===a[b])return a.splice(b,1)},update:function(c){var b,e=a,d,c=c!==void 0?c:Date.now();for(b=e.length-1;b>=0;b--)d=e[b],d.update(c)!==!0&&TWEEN.remove(d)}}}();
TWEEN.Tween=function(a){var c={},b={},e=1E3,d=0,f=null,g=TWEEN.Easing.Linear.None,p=TWEEN.Interpolation.Linear,l=null,i=null,m=null,n=null,o=null;this.getObject=function(){return a};this.getTarget=function(){return b};this.to=function(a,c){c!==null&&(e=c);b=a;return this};this.start=function(e){TWEEN.add(this);f=e!==void 0?e:Date.now();f+=d;for(var e=Object.keys(b),g=0,k=e.length;g<k;g++){var h=e[g];if(a[h]!==null){var j=b[h];if(j instanceof Array){if(j.length===0)continue;b[h]=[a[h]].concat(j)}c[h]=
a[h]}}typeof i==="function"&&i.call(a);return this};this.stop=function(){TWEEN.remove(this);typeof n==="function"&&n.call(a);return this};this.delay=function(a){d=a;return this};this.easing=function(a){g=a;return this};this.interpolation=function(a){p=a;return this};this.chain=function(a){l=a;return this};this.onStart=function(a){i=a;return this};this.onUpdate=function(a){m=a;return this};this.onStop=function(a){n=a;return this};this.onComplete=function(a){o=a;return this};this.update=function(d){if(d<
f)return!0;var d=(d-f)/e,d=d>1?1:d,i=g(d),k;for(k in c){var h=c[k],j=b[k];a[k]=j instanceof Array?p(j,i):h+(j-h)*i}typeof m==="function"&&m.call(a,i);return d==1?(typeof o==="function"&&o.call(a),l!==null&&l.start(),!1):!0}};
TWEEN.Easing={Linear:{None:function(a){return a}},Quadratic:{In:function(a){return a*a},Out:function(a){return a*(2-a)},InOut:function(a){return(a*=2)<1?0.5*a*a:-0.5*(--a*(a-2)-1)}},Cubic:{In:function(a){return a*a*a},Out:function(a){return--a*a*a+1},InOut:function(a){return(a*=2)<1?0.5*a*a*a:0.5*((a-=2)*a*a+2)}},Quartic:{In:function(a){return a*a*a*a},Out:function(a){return 1- --a*a*a*a},InOut:function(a){return(a*=2)<1?0.5*a*a*a*a:-0.5*((a-=2)*a*a*a-2)}},Quintic:{In:function(a){return a*a*a*a*a},
Out:function(a){return--a*a*a*a*a+1},InOut:function(a){return(a*=2)<1?0.5*a*a*a*a*a:0.5*((a-=2)*a*a*a*a+2)}},Sinusoidal:{In:function(a){return 1-Math.cos(a*Math.PI/2)},Out:function(a){return Math.sin(a*Math.PI/2)},InOut:function(a){return 0.5*(1-Math.cos(Math.PI*a))}},Exponential:{In:function(a){return a===0?0:Math.pow(1024,a-1)},Out:function(a){return a===1?1:1-Math.pow(2,-10*a)},InOut:function(a){return a===0?0:a===1?1:(a*=2)<1?0.5*Math.pow(1024,a-1):0.5*(-Math.pow(2,-10*(a-1))+2)}},Circular:{In:function(a){return 1-
Math.sqrt(1-a*a)},Out:function(a){return Math.sqrt(1- --a*a)},InOut:function(a){return(a*=2)<1?-0.5*(Math.sqrt(1-a*a)-1):0.5*(Math.sqrt(1-(a-=2)*a)+1)}},Elastic:{In:function(a){var c,b=0.1;if(a===0)return 0;if(a===1)return 1;!b||b<1?(b=1,c=0.1):c=0.4*Math.asin(1/b)/(2*Math.PI);return-(b*Math.pow(2,10*(a-=1))*Math.sin((a-c)*2*Math.PI/0.4))},Out:function(a){var c,b=0.1;if(a===0)return 0;if(a===1)return 1;!b||b<1?(b=1,c=0.1):c=0.4*Math.asin(1/b)/(2*Math.PI);return b*Math.pow(2,-10*a)*Math.sin((a-c)*
2*Math.PI/0.4)+1},InOut:function(a){var c,b=0.1;if(a===0)return 0;if(a===1)return 1;!b||b<1?(b=1,c=0.1):c=0.4*Math.asin(1/b)/(2*Math.PI);return(a*=2)<1?-0.5*b*Math.pow(2,10*(a-=1))*Math.sin((a-c)*2*Math.PI/0.4):b*Math.pow(2,-10*(a-=1))*Math.sin((a-c)*2*Math.PI/0.4)*0.5+1}},Back:{In:function(a){return a*a*(2.70158*a-1.70158)},Out:function(a){return--a*a*(2.70158*a+1.70158)+1},InOut:function(a){return(a*=2)<1?0.5*a*a*(3.5949095*a-2.5949095):0.5*((a-=2)*a*(3.5949095*a+2.5949095)+2)}},Bounce:{In:function(a){return 1-
TWEEN.Easing.Bounce.Out(1-a)},Out:function(a){return a<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375},InOut:function(a){return a<0.5?TWEEN.Easing.Bounce.In(a*2)*0.5:TWEEN.Easing.Bounce.Out(a*2-1)*0.5+0.5}}};
TWEEN.Interpolation={Linear:function(a,c){var b=a.length-1,e=b*c,d=Math.floor(e),f=TWEEN.Interpolation.Utils.Linear;return c<0?f(a[0],a[1],e):c>1?f(a[b],a[b-1],b-e):f(a[d],a[d+1>b?b:d+1],e-d)},Bezier:function(a,c){var b=0,e=a.length-1,d=Math.pow,f=TWEEN.Interpolation.Utils.Bernstein,g;for(g=0;g<=e;g++)b+=d(1-c,e-g)*d(c,g)*a[g]*f(e,g);return b},CatmullRom:function(a,c){var b=a.length-1,e=b*c,d=Math.floor(e),f=TWEEN.Interpolation.Utils.CatmullRom;return a[0]===a[b]?(c<0&&(d=Math.floor(e=b*(1+c))),f(a[(d-
1+b)%b],a[d],a[(d+1)%b],a[(d+2)%b],e-d)):c<0?a[0]-(f(a[0],a[0],a[1],a[1],-e)-a[0]):c>1?a[b]-(f(a[b],a[b],a[b-1],a[b-1],e-b)-a[b]):f(a[d?d-1:0],a[d],a[b<d+1?b:d+1],a[b<d+2?b:d+2],e-d)},Utils:{Linear:function(a,c,b){return(c-a)*b+a},Bernstein:function(a,c){var b=TWEEN.Interpolation.Utils.Factorial;return b(a)/b(c)/b(a-c)},Factorial:function(){var a=[1];return function(c){var b=1,e;if(a[c])return a[c];for(e=c;e>1;e--)b*=e;return a[c]=b}}(),CatmullRom:function(a,c,b,e,d){var a=(b-a)*0.5,e=(e-c)*0.5,f=
d*d;return(2*c-2*b+a+e)*d*f+(-3*c+3*b-2*a-e)*f+a*d+c}}};
