(function(o){function pa(a){var c;c=o.extend(a,{});if(a.color instanceof THREE.Color)c.color=a.color.getHex();if(a.ambient instanceof THREE.Color)c.ambient=a.ambient.getHex();if(a.specular instanceof THREE.Color)c.specular=a.specular.getHex();return a instanceof THREE.MeshBasicMaterial?new THREE.MeshBasicMaterial(c):a instanceof THREE.MeshLambertMaterial?new THREE.MeshLambertMaterial(c):a instanceof THREE.MeshPhongMaterial?new THREE.MeshPhongMaterial(c):a instanceof THREE.MeshFaceMaterial?new THREE.MeshFaceMaterial(c):
new THREE.Material(c)}function qa(a){var c,f,b,d;b=a.vertices;d=a.faces;var e=a.faceVertexUvs[0],g,i=new THREE.Geometry;if(a.materials)for(c=0,f=a.materials.length;c<f;c++)i.materials.push(a.materials[c].clone());i.vertices=j(b);i.faces=j(d);for(c=0,f=e.length;c<f;c++){g=e[c];uvCopy=[];for(b=0,d=g.length;b<d;b++)uvCopy.push(new THREE.UV(g[b].u,g[b].v));i.faceVertexUvs[0].push(uvCopy)}i.morphTargets=p(a.morphTargets);i.morphColors=p(a.morphColors);return i}function p(a){var c,f,b=[],d,e;for(c=0,f=
a.length;c<f;c++){d=a[c];e={name:d.name};if(d.hasOwnProperty("vertices"))e.vertices=j(d.vertices);if(d.hasOwnProperty("colors"))e.colors=j(d.colors);if(d.hasOwnProperty("normals"))e.normals=j(d.normals);b.push(e)}return b}function j(a){var c,f,b,d=[];for(c=0,f=a.length;c<f;c++)b=a[c],d.push(b.clone());return d}function ra(a){var c,f,b,d;f=z.extract_parents_from_objects(a,a);for(a=0,c=f.length;a<c;a++)b=f[a],b.matrixWorldNeedsUpdate===!0&&(d=b);typeof d!=="undefined"&&d.updateMatrixWorld()}function v(a,
c){var f,b,d,e,g=a instanceof THREE.Mesh?a.geometry:a,i=g.morphTargets,h,k;g.applyMatrix(c);for(f=0,b=i.length;f<b;f++){d=i[f];h=d.vertices;for(d=0,e=h.length;d<e;d++)k=h[d],c.multiplyVector3(k)}g.computeBoundingSphere();g.computeBoundingBox();if(a instanceof THREE.Mesh)a.boundRadius=g.boundingSphere.radius}function D(a,c,f,b){var d=A.setRotationFromQuaternion(c),e=B;objectNewQ=J;v(a,d);if(f===!0&&a instanceof THREE.Mesh)a.useQuaternion===!0?e=a.quaternion:e.setFromRotationMatrix(a.matrix),b===!0?
objectNewQ.multiply(e,c.inverse()):objectNewQ.multiply(c.inverse(),e),a.useQuaternion===!0?a.quaternion.copy(objectNewQ):a.matrix.setRotationFromQuaternion(objectNewQ)}function sa(a,c){var f=a instanceof THREE.Mesh?a:!1,b=f?f.geometry:a,d=K;b.boundingBox||b.computeBoundingBox();(b=b.boundingBox)?(d.set(b.max.x-b.min.x,b.max.y-b.min.y,b.max.z-b.min.z),c!==!0&&f&&d.multiplySelf(f.scale)):d.set(0,0,0);return d}function ta(a,c){var f=a instanceof THREE.Mesh?a.geometry:a,b=a instanceof THREE.Mesh?a.matrixWorld:
L,d=M,e=N,g=c.min,i=c.max;f.boundingBox||f.computeBoundingBox();f=f.boundingBox;d.copy(f.min);e.copy(f.max);b.multiplyVector3(d);b.multiplyVector3(e);if(d.x<g.x)g.x=d.x;if(e.x>i.x)i.x=e.x;if(d.y<g.y)g.y=d.y;if(e.y>i.y)i.y=e.y;if(d.z<g.z)g.z=d.z;if(e.z>i.z)i.z=e.z;return c}function ua(a,c){var f=(a instanceof THREE.Mesh?a.geometry:a).vertices,b=c.centroid,d=f[c.a],e=f[c.b],g=f[c.c],i=O;c instanceof THREE.Face4?(f=f[c.d],b.add(d,e).addSelf(g).addSelf(f).divideScalar(4),b=Math.max(i.sub(b,d).length(),
i.sub(b,e).length(),i.sub(b,g).length(),i.sub(b,f).length())):(b.add(d,e).addSelf(g).divideScalar(3),b=Math.max(i.sub(b,d).length(),i.sub(b,e).length(),i.sub(b,g).length()));return b}function P(a){var c=a instanceof THREE.Mesh?a.geometry:a,a=Q;c.boundingBox||c.computeBoundingBox();c=c.boundingBox;a.add(c.min,c.max).multiplyScalar(-0.5);return a}function va(a){var c=P(a),f=R.makeTranslation(c.x,c.y,c.z);v(a,f);a instanceof THREE.Mesh&&a.position.subSelf(c);return c}function S(a,c,f){var b,d,e=(a instanceof
THREE.Mesh?a.geometry:a).faces,g,i=T.set(0,0,0),h=U.cardinalAxes;for(b=0,d=e.length;b<d;b++)g=e[b],i.addSelf(g.normal);i.normalize();c=c||(typeof a.rigidBody!=="undefined"?a.rigidBody.axes.up:h.up);f=f||(typeof a.rigidBody!=="undefined"?a.rigidBody.axes.forward:h.forward);return V.q_to_axis(i,c,f)}function wa(a){var c=S(a);c instanceof THREE.Quaternion&&D(a,c,!0)}function xa(a){var c,f,b,d,e,g;c=a instanceof THREE.Mesh?a.geometry:a;var i=c.vertices,I=c.faces,k,l,r,s,t,E,u,F,$=[W,X,Y,Z],j=h.faceVerticesExpected,
n,C,w,m,x,p,v,G,q,z=aa,y,A=ba,B=ca.set(0,1,0);for(c=0,f=I.length;c<f;c++){k=I[c];l=k instanceof THREE.Face4?["a","b","c","d"]:["a","b","c"];r=[];s=[];t=[];E={};F=[];p=[];v=[];G=[];y=Number.MAX_VALUE;for(b=0,d=l.length;b<d;b++){n=l[b];m=F[b]=k[n];p[b]=k.vertexNormals[b];v[b]=k.vertexColors[b];G[b]=k.vertexTangents[b];e=i[m];m=$[b].copy(e).normalize();u=E[n]={};for(e=0,g=l.length;e<g;e++)C=l[e],n=j[e],e>=b-1&&e<=b+1||b===0&&e===d-1||b===d-1&&e===0?(w=H.clamp(m.dot(n),-1,1),q=Math.acos(w),z.cross(m,
n).normalize(),n=B.dot(z),u[C]=q+=Math.acos(n),q<y&&(y=q,x=e)):u[C]=Number.MAX_VALUE;t.push(b)}t=[].concat(t.slice(x),t.slice(0,x));for(b=0,d=l.length;b<d;b++){m=t[b];w=l[m];y=Number.MAX_VALUE;for(e=0,g=l.length;e<g;e++)if(n=l[e],o.index_of_value(r,n)===-1&&(u=E[n],q=u[w],q<y&&(b===0||C===(e===0?l[l.length-1]:l[e-1]))))y=q,r[m]=n,s[m]=e;C=r[m]}q=0;for(b=0,d=l.length;b<d;b++)n=l[b],x=s[b],m=F[x],k[n]=m,k.vertexNormals[b]=p[m],k.vertexColors.length>b&&(k.vertexColors[b]=v[m]),k.vertexTangents.length>
b&&(k.vertexTangents[b]=G[m]),m=$[x],n=j[b],w=H.clamp(m.dot(n),-1,1),q+=Math.acos(w)}q/=Math.max(1,i.length);A.setFromAxisAngle(B,q-Math.PI*0.5);D(a,A,!0,!0)}function ya(a,c,f,b,d){var e=c.scale,e=Math.max(e.x,e.y,e.z),g=c.matrixWorld,i=da.setFromRotationMatrix(g),g=ea.copy(g.getPosition()),h=a.position,k=a.quaternion,l=fa,r=ga,s=ha,t=ia,j=ja,u,o,p;b instanceof THREE.Quaternion?l.copy(b):b instanceof THREE.Vector3?l.setFromEuler(b).normalize():(l.set(0,0,0,1),u=!0);d instanceof THREE.Quaternion?r.copy(d):
d instanceof THREE.Vector3?r.setFromEuler(d).normalize():(r.set(0,0,0,1),o=!0);f instanceof THREE.Vector3?s.set(f.x,f.y,f.z).multiplyScalar(e):p=!0;p!==!0&&(u!==!0&&l.multiplyVector3(s),o!==!0&&r.multiplyVector3(s),a.parent!==c&&i.multiplyVector3(s));a.parent instanceof THREE.Object3D&&a.parent!==c&&a.parent!==c.parent?(t.getInverse(a.parent.matrixWorld),j.setFromRotationMatrix(t),p!==!0&&j.multiplyVector3(s),j.multiplyVector3(g),h.copy(t.getPosition()),k.copy(j)):(h.set(0,0,0),k.set(0,0,0,1));a.parent!==
c&&h.addSelf(g);p!==!0&&h.addSelf(s);a.parent!==c&&k.multiplySelf(i);o!==!0&&k.multiplySelf(r);u!==!0&&k.multiplySelf(l)}function za(a,c,f,b,d){var e=a.position,a=a.quaternion,g=ka,i=la,h=ma,k,l,j;f instanceof THREE.Vector3?h.copy(f):j=!0;b instanceof THREE.Quaternion?g.copy(b):b instanceof THREE.Vector3?g.setFromEuler(b).normalize():k=!0;d instanceof THREE.Quaternion?i.copy(d):d instanceof THREE.Vector3?i.setFromEuler(d).normalize():l=!0;if(k!==!0||l!==!0)a.set(0,0,0,1),k!==!0&&(g.multiplyVector3(h),
a.multiplySelf(i)),l!==!0&&(i.multiplyVector3(h),a.multiplySelf(g));c instanceof THREE.Object3D?e.copy(c.position):e.copy(c);j!==!0&&e.addSelf(h)}function Aa(a,c){var f=a.changeStack=a.changeStack||[],b=a.changedProperties=a.changedProperties||{},d,e={id:Math.random()},g;for(g in c)c.hasOwnProperty(g)&&g!=="id"&&(d=c[g],e[g]=a[g],a[g]=d,d=b[g]=b[g]||[],d.push(e),d=!0);if(d===!0)return f.push(e),e}function na(a,c,f){var b=a.changeStack,d=a.changedProperties,e,g=-1,h,j;if(typeof b!=="undefined"&&typeof d!==
"undefined")if(c===!0)for(c=b.length-1;c>=0;c--)na(a,c,!0);else if(g=o.is_number(c)?c:typeof c!=="undefined"?o.last_index_of_value(b,c):b.length-1,g!==-1){c=b[g];for(j in c)c.hasOwnProperty(j)&&j!=="id"&&(e=d[j],h=f===!0?e.length-1:o.last_index_of_value(e,c),h!==-1&&(h===e.length-1?a[j]=c[j]:e[h+1][j]=e[Math.max(h-1,0)][j],e.splice(h,1)));b.splice(g,1)}}function Ba(a,c,f){f=f||{};oa(a,c);a=(new TWEEN.Tween(a)).to(c,f.duration).easing(f.easing||TWEEN.Easing.Quadratic.InOut).delay(f.delay||0).onStart(f.onStart).onStop(f.onStop).onUpdate(f.onUpdate).onComplete(f.onComplete);
f.start!==!1&&a.start();return a}function oa(a,c){var f,b=TWEEN.getAll(),d,e,g;for(f=b.length-1;f>=0;f--)if(d=b[f],e=d.getObject(),a===e)if(typeof c!=="undefined")for(g in e=d.getTarget(),c){if(c.hasOwnProperty(g)&&e&&e.hasOwnProperty(g)){d.stop();break}}else d.stop()}var U=o.shared=o.shared||{},h={},H,z,V,ea,ha,ma,M,N,O,K,Q,T,W,X,Y,Z,aa,ca,da,fa,ga,ja,ka,la,B,J,ba,ia,L,R,A;o.asset_register("js/kaiopua/utils/ObjectHelper.js",{data:h,requirements:["js/kaiopua/utils/MathHelper.js","js/kaiopua/utils/SceneHelper.js",
"js/kaiopua/utils/VectorHelper.js"],callbacksOnReqs:function(a,c,f){var b=Math.sqrt(0.5),d=U.cardinalAxes,e=d.right,d=d.forward;H=a;z=c;V=f;ea=new THREE.Vector3;ha=new THREE.Vector3;new THREE.Vector3;ma=new THREE.Vector3;M=new THREE.Vector3;N=new THREE.Vector3;O=new THREE.Vector3;K=new THREE.Vector3;Q=new THREE.Vector3;T=new THREE.Vector3;W=new THREE.Vector3;X=new THREE.Vector3;Y=new THREE.Vector3;Z=new THREE.Vector3;aa=new THREE.Vector3;ca=new THREE.Vector3;B=new THREE.Quaternion;J=new THREE.Quaternion;
ba=new THREE.Quaternion;da=new THREE.Quaternion;fa=new THREE.Quaternion;ga=new THREE.Quaternion;ja=new THREE.Quaternion;ka=new THREE.Quaternion;la=new THREE.Quaternion;ia=new THREE.Matrix4;L=new THREE.Matrix4;R=new THREE.Matrix4;A=new THREE.Matrix4;h.vertexExpectedA=new THREE.Vector3(e.x*-b,0,d.z*b);h.vertexExpectedB=new THREE.Vector3(e.x*-b,0,d.z*-b);h.vertexExpectedC=new THREE.Vector3(e.x*b,0,d.z*-b);h.vertexExpectedD=new THREE.Vector3(e.x*b,0,d.z*b);h.faceVerticesExpected=[h.vertexExpectedA,h.vertexExpectedB,
h.vertexExpectedC,h.vertexExpectedD];h.clone_material=pa;h.clone_geometry=qa;h.clone_morphs=p;h.clone_list=j;h.update_world_matrix=ra;h.apply_matrix=v;h.apply_quaternion=D;h.dimensions=sa;h.push_bounds=ta;h.face_bounding_radius=ua;h.center_offset=P;h.center=va;h.rotation_offset=S;h.center_rotation=wa;h.normalize_faces=xa;h.object_follow_object=ya;h.object_orbit_source=za;h.temporary_change=Aa;h.revert_change=na;h.tween=Ba;h.tween_stop=oa},wait:!0})})(KAIOPUA);
