(function(c){function k(){a.sceneBG.add(a.skybox);a.scene.add(a.world);h.revert_change(a.cameraControls.options,!0);a.cameraControls.target=a.world.parts.asteroid;a.cameraControls.enabled=!0;a.cameraControls.controllable=!0;a.signals.onGameUpdated.add(f)}function l(){a.signals.onGameUpdated.remove(f)}function m(){a.scene.remove(a.world);a.sceneBG.remove(a.skybox)}function f(){}var a=c.shared=c.shared||{},e={},d,i,h,j,g;c.asset_register("js/kaiopua/sections/Launcher.js",{data:e,requirements:["js/kaiopua/core/Model.js",
"js/kaiopua/env/Skybox.js","js/kaiopua/utils/ObjectHelper.js","js/kaiopua/physics/ObstacleSlippery.js","js/kaiopua/physics/ObstacleDamaging.js",{path:a.pathToAssets+"asteroid.js",type:"model"},a.pathToAssets+"skybox.jpg"],callbacksOnReqs:function(n,o,p,q,r,s){d=n;i=o;h=p;j=q;g=r;e.show=k;e.hide=l;e.remove=m;e.update=f;a.skybox=new i.Instance(a.pathToAssets+"skybox",{repeat:2,oneForAll:!0});a.world=new d.Instance;a.world.parts={};a.world.parts.ambientLight=new THREE.AmbientLight(5592405);a.world.add(a.world.parts.ambientLight);
a.world.parts.asteroidMoonLight=new THREE.PointLight(16777215,1.5);a.world.add(a.world.parts.asteroidMoonLight);a.world.parts.asteroid=new d.Instance({geometry:s,physics:{bodyType:"mesh",gravitySource:!0},center:!0});a.world.add(a.world.parts.asteroid);c.asset_require({path:a.pathToAssets+"asteroid_moon.js",type:"model"},function(b){b=new d.Instance({geometry:b,physics:{bodyType:"mesh"},center:!0});a.world.add(b);a.world.parts.asteroidMoonLight.distance=b.boundRadius*10;b.add(a.world.parts.asteroidMoonLight)});
c.asset_require({path:a.pathToAssets+"asteroid_colliders.js",type:"model"},function(b){b=new d.Instance({geometry:b,physics:{bodyType:"mesh"}});a.world.add(b)});c.asset_require({path:a.pathToAssets+"asteroid_noncolliders.js",type:"model"},function(b){b=new d.Instance({geometry:b});a.world.add(b)});c.asset_require({path:a.pathToAssets+"landing_colliders.js",type:"model"},function(b){b=new d.Instance({geometry:b,physics:{bodyType:"mesh"}});a.world.add(b)});c.asset_require({path:a.pathToAssets+"landing_noncolliders.js",
type:"model"},function(b){b=new d.Instance({geometry:b});a.world.add(b)});a.world.parts.gemLight=new THREE.PointLight(14809956,2);a.world.add(a.world.parts.gemLight);c.asset_require({path:a.pathToAssets+"gem.js",type:"model"},function(b){b=new d.Instance({geometry:b,physics:{bodyType:"mesh"},center:!0});a.world.add(b);a.world.parts.gemLight.distance=b.boundRadius*12;a.world.parts.gemLight.position.copy(b.position).normalize().multiplyScalar(a.world.parts.gemLight.distance*0.25);b.add(a.world.parts.gemLight)});
c.asset_require({path:a.pathToAssets+"gemforest_colliders.js",type:"model"},function(b){b=new d.Instance({geometry:b,physics:{bodyType:"mesh"}});a.world.add(b)});c.asset_require({path:a.pathToAssets+"gemforest_noncolliders.js",type:"model"},function(b){b=new d.Instance({geometry:b});a.world.add(b)});c.asset_require({path:a.pathToAssets+"snow_colliders.js",type:"model"},function(b){b=new d.Instance({geometry:b,physics:{bodyType:"mesh"}});a.world.add(b)});c.asset_require({path:a.pathToAssets+"snow_noncolliders.js",
type:"model"},function(b){b=new d.Instance({geometry:b});a.world.add(b)});c.asset_require({path:a.pathToAssets+"snow_obstacles_slippery.js",type:"model"},function(b){b=new j.Instance({geometry:b,physics:{bodyType:"mesh"}});a.world.add(b)});c.asset_require([{path:a.pathToAssets+"snow_obstacles_damaging.js",type:"model"}],function(b){b=new g.Instance({geometry:b,physics:{bodyType:"mesh"},options:{damage:25}});a.world.add(b)});a.world.parts.iceplanetMoonLight=new THREE.PointLight(7329019,2.5);a.world.add(a.world.parts.iceplanetMoonLight);
c.asset_require({path:a.pathToAssets+"iceplanet_moon.js",type:"model"},function(b){b=new d.Instance({geometry:b,physics:{bodyType:"mesh",gravitySource:!0},center:!0});a.world.add(b);a.world.parts.iceplanetMoonLight.distance=b.boundRadius*12;b.add(a.world.parts.iceplanetMoonLight)});a.world.parts.lavaLight=new THREE.PointLight(15769088,2);a.world.add(a.world.parts.lavaLight);c.asset_require({path:a.pathToAssets+"lava_volcano.js",type:"model"},function(b){b=new d.Instance({geometry:b,physics:{bodyType:"mesh"},
center:!0});a.world.add(b);a.world.parts.lavaLight.distance=b.boundRadius*7;b.add(a.world.parts.lavaLight)});c.asset_require({path:a.pathToAssets+"lava_colliders.js",type:"model"},function(b){b=new d.Instance({geometry:b,physics:{bodyType:"mesh"}});a.world.add(b)});c.asset_require([{path:a.pathToAssets+"lava_obstacles_damaging.js",type:"model"}],function(b){b=new g.Instance({geometry:b,physics:{bodyType:"mesh"},options:{damage:50}});a.world.add(b)});a.world.parts.starclusterLight=new THREE.PointLight(16767299,
2.5);a.world.add(a.world.parts.starclusterLight);c.asset_require({path:a.pathToAssets+"starcluster_core.js",type:"model"},function(b){b=new d.Instance({geometry:b,physics:{bodyType:"mesh",gravitySource:!0},center:!0});a.world.add(b);a.world.parts.starclusterLight.distance=b.boundRadius*7;b.add(a.world.parts.starclusterLight)});c.asset_require({path:a.pathToAssets+"starcluster_1.js",type:"model"},function(b){b=new d.Instance({geometry:b,physics:{bodyType:"mesh",gravitySource:!0},center:!0});a.world.add(b)});
c.asset_require({path:a.pathToAssets+"starcluster_2.js",type:"model"},function(b){b=new d.Instance({geometry:b,physics:{bodyType:"mesh",gravitySource:!0},center:!0});a.world.add(b)});c.asset_require({path:a.pathToAssets+"starcluster_3.js",type:"model"},function(b){b=new d.Instance({geometry:b,physics:{bodyType:"mesh",gravitySource:!0},center:!0});a.world.add(b)});c.asset_require({path:a.pathToAssets+"starcluster_noncolliders.js",type:"model"},function(b){b=new d.Instance({geometry:b});a.world.add(b)})},
wait:!0})})(KAIOPUA);
