(function(c){function n(d){c.asset_require([{path:b.pathToAssets+d.options.assetsPath+".js",type:"model"}],function(c){c=new j.Instance({name:d.name,options:d.options,geometry:c});b.world.add(c);c.face_local_direction((new THREE.Vector3(Math.random()*2-1,0,Math.random()*2-1)).normalize());c.respawn(b.scene,d.spawn)})}function q(){b.sceneBG.add(b.skybox);b.scene.add(b.world);k.revert_change(b.cameraControls.options,!0);b.cameraControls.target=b.world.parts.asteroid;b.cameraControls.enabled=!0;b.cameraControls.controllable=
!0;b.signals.onGameUpdated.add(f)}function r(){b.signals.onGameUpdated.remove(f)}function s(){b.scene.remove(b.world);b.sceneBG.remove(b.skybox)}function f(){}var b=c.shared=c.shared||{},e={},d,l,k,m,i,j;c.asset_register("js/kaiopua/sections/Launcher.js",{data:e,requirements:["js/kaiopua/core/Model.js","js/kaiopua/env/Skybox.js","js/kaiopua/utils/ObjectHelper.js","js/kaiopua/physics/ObstacleSlippery.js","js/kaiopua/physics/ObstacleDamaging.js","js/kaiopua/characters/Speaker.js",{path:b.pathToAssets+
"asteroid.js",type:"model"},b.pathToAssets+"skybox.jpg"],callbacksOnReqs:function(o,p,t,u,v,w,x){d=o;l=p;k=t;m=u;i=v;j=w;e.show=q;e.hide=r;e.remove=s;e.update=f;b.skybox=new l.Instance(b.pathToAssets+"skybox",{repeat:2,oneForAll:!0});b.world=new d.Instance;b.world.parts={};b.world.parts.ambientLight=new THREE.AmbientLight(5592405);b.world.add(b.world.parts.ambientLight);b.world.parts.asteroidMoonLight=new THREE.PointLight(16777215,1.5);b.world.add(b.world.parts.asteroidMoonLight);b.world.parts.asteroid=
new d.Instance({geometry:x,physics:{bodyType:"mesh",gravitySource:!0},center:!0});b.world.add(b.world.parts.asteroid);c.asset_require({path:b.pathToAssets+"asteroid_moon.js",type:"model"},function(a){a=new d.Instance({geometry:a,physics:{bodyType:"mesh"},center:!0});b.world.add(a);b.world.parts.asteroidMoonLight.distance=a.boundRadius*10;a.add(b.world.parts.asteroidMoonLight)});c.asset_require({path:b.pathToAssets+"asteroid_colliders.js",type:"model"},function(a){a=new d.Instance({geometry:a,physics:{bodyType:"mesh"}});
b.world.add(a)});c.asset_require({path:b.pathToAssets+"asteroid_noncolliders.js",type:"model"},function(a){a=new d.Instance({geometry:a});b.world.add(a)});c.asset_require({path:b.pathToAssets+"landing_colliders.js",type:"model"},function(a){a=new d.Instance({geometry:a,physics:{bodyType:"mesh"}});b.world.add(a)});c.asset_require({path:b.pathToAssets+"landing_noncolliders.js",type:"model"},function(a){a=new d.Instance({geometry:a});b.world.add(a)});b.world.parts.gemLight=new THREE.PointLight(14809956,
2);b.world.add(b.world.parts.gemLight);c.asset_require({path:b.pathToAssets+"gem.js",type:"model"},function(a){a=new d.Instance({geometry:a,physics:{bodyType:"mesh"},center:!0});b.world.add(a);b.world.parts.gemLight.distance=a.boundRadius*12;b.world.parts.gemLight.position.copy(a.position).normalize().multiplyScalar(b.world.parts.gemLight.distance*0.25);a.add(b.world.parts.gemLight)});c.asset_require({path:b.pathToAssets+"gemforest_colliders.js",type:"model"},function(a){a=new d.Instance({geometry:a,
physics:{bodyType:"mesh"}});b.world.add(a)});c.asset_require({path:b.pathToAssets+"gemforest_noncolliders.js",type:"model"},function(a){a=new d.Instance({geometry:a});b.world.add(a)});c.asset_require({path:b.pathToAssets+"snow_colliders.js",type:"model"},function(a){a=new d.Instance({geometry:a,physics:{bodyType:"mesh"}});b.world.add(a)});c.asset_require({path:b.pathToAssets+"snow_noncolliders.js",type:"model"},function(a){a=new d.Instance({geometry:a});b.world.add(a)});c.asset_require({path:b.pathToAssets+
"snow_obstacles_slippery.js",type:"model"},function(a){a=new m.Instance({geometry:a,physics:{bodyType:"mesh"}});b.world.add(a)});c.asset_require([{path:b.pathToAssets+"snow_obstacles_damaging.js",type:"model"}],function(a){a=new i.Instance({geometry:a,physics:{bodyType:"mesh"},options:{damage:25}});b.world.add(a)});b.world.parts.iceplanetMoonLight=new THREE.PointLight(7329019,2.5);b.world.add(b.world.parts.iceplanetMoonLight);c.asset_require({path:b.pathToAssets+"iceplanet_moon.js",type:"model"},
function(a){a=new d.Instance({geometry:a,physics:{bodyType:"mesh",gravitySource:!0},center:!0});b.world.add(a);b.world.parts.iceplanetMoonLight.distance=a.boundRadius*12;a.add(b.world.parts.iceplanetMoonLight)});b.world.parts.lavaLight=new THREE.PointLight(15769088,2);b.world.add(b.world.parts.lavaLight);c.asset_require({path:b.pathToAssets+"lava_volcano.js",type:"model"},function(a){a=new d.Instance({geometry:a,physics:{bodyType:"mesh"},center:!0});b.world.add(a);b.world.parts.lavaLight.distance=
a.boundRadius*7;a.add(b.world.parts.lavaLight)});c.asset_require({path:b.pathToAssets+"lava_colliders.js",type:"model"},function(a){a=new d.Instance({geometry:a,physics:{bodyType:"mesh"}});b.world.add(a)});c.asset_require([{path:b.pathToAssets+"lava_obstacles_damaging.js",type:"model"}],function(a){a=new i.Instance({geometry:a,physics:{bodyType:"mesh"},options:{damage:50}});b.world.add(a)});b.world.parts.starclusterLight=new THREE.PointLight(16767299,2.5);b.world.add(b.world.parts.starclusterLight);
c.asset_require({path:b.pathToAssets+"starcluster_core.js",type:"model"},function(a){a=new d.Instance({geometry:a,physics:{bodyType:"mesh",gravitySource:!0},center:!0});b.world.add(a);b.world.parts.starclusterLight.distance=a.boundRadius*7;a.add(b.world.parts.starclusterLight)});c.asset_require({path:b.pathToAssets+"starcluster_1.js",type:"model"},function(a){a=new d.Instance({geometry:a,physics:{bodyType:"mesh",gravitySource:!0},center:!0});b.world.add(a)});c.asset_require({path:b.pathToAssets+"starcluster_2.js",
type:"model"},function(a){a=new d.Instance({geometry:a,physics:{bodyType:"mesh",gravitySource:!0},center:!0});b.world.add(a)});c.asset_require({path:b.pathToAssets+"starcluster_3.js",type:"model"},function(a){a=new d.Instance({geometry:a,physics:{bodyType:"mesh",gravitySource:!0},center:!0});b.world.add(a)});c.asset_require({path:b.pathToAssets+"starcluster_noncolliders.js",type:"model"},function(a){a=new d.Instance({geometry:a});b.world.add(a)});c.asset_require({path:b.pathToAssets+"spawn_random.js",
type:"model"},function(a){var d,g,e,h,f=[{name:"Michal Budzynski",options:{assetsPath:"speaker_budzynski_michal"}},{name:"Collin Hover",options:{assetsPath:"speaker_hover_collin"}},{name:"Jesse Freeman",options:{assetsPath:"speaker_freeman_jesse"}},{name:"Pascal Rettig",options:{assetsPath:"speaker_rettig_pascal"}}];h=b.spawns.random=b.spawns.random||[];g=a.vertices;for(a=0,d=g.length;a<d;a++)e=g[a],h.push(e.clone());h=h.slice(0);for(a=0,d=f.length;a<d;a++)g=f[a],g.spawn=c.array_random_value_remove(h),
n(g)})},wait:!0})})(KAIOPUA);
