var KAIOPUA=function(e){var ta,aa,ba,ca,v,M,E,N,s,w,F,O,G,t,P,Q,u,H,I,da,J,R;function Qa(a,c,d){console.log("GAME: compatiblity check");z=a;ea=c;ua=d;z.errorState?(z.process(),b.signals.onGameReady.dispatch()):(b.supports.webGL=!0,e.asset_require(Ra,[Sa],!0))}function Sa(){e.asset_require(Ta,[Ua,Va],!0)}function Va(){e.asset_require(Wa,[Xa,Ya],!0)}function Ya(){e.asset_require(Za,[$a,ab],!0)}function ab(){e.asset_require(bb,cb,!0)}function Ua(){console.log("GAME: foundation");b.universeGravitySource=
new THREE.Vector3(0,0,0);b.universeGravityMagnitude=new THREE.Vector3(0,-0.4,0);b.cardinalAxes={up:new THREE.Vector3(0,1,0),forward:new THREE.Vector3(0,0,1),right:new THREE.Vector3(-1,0,0)};b.renderer=new THREE.WebGLRenderer({clearColor:0,clearAlpha:0,maxLights:8});b.renderer.setSize(b.gameWidth,b.gameHeight);b.renderer.autoClear=!1;b.renderTarget=new THREE.WebGLRenderTarget(b.gameWidth,b.gameHeight,{minFilter:THREE.LinearFilter,magFilter:THREE.NearestFilter})}function Xa(a,c){console.log("GAME: setup");
fa=a;va=c;b.scene=new fa.Instance;b.sceneBG=new fa.Instance;b.scene.fog=void 0;e.physics=b.scene.physics;b.camera=new THREE.PerspectiveCamera(60,b.gameWidth/b.gameHeight,1,2E4);b.cameraBG=new THREE.PerspectiveCamera(60,b.gameWidth/b.gameHeight,1,2E4);b.camera.useQuaternion=b.cameraBG.useQuaternion=!0;b.cameraControls=new va.Instance({camera:b.camera});b.cameraControls.onCameraMoved.add($.throttle(b.throttleTimeMedium,function(){b.domElements.$game.triggerHandler("mousemove")}));ta=new THREE.RenderPass(b.sceneBG,
b.cameraBG);aa=new THREE.RenderPass(b.scene,b.camera);ba=new THREE.ShaderPass(THREE.ShaderExtras.screen);aa.clear=!1;ba.renderToScreen=!0;A=new THREE.EffectComposer(b.renderer,b.renderTarget);A.addPass(ta);A.addPass(aa);A.addPass(ba);b.domElements.$game.prepend(b.renderer.domElement);b.throttled.on_game_pointer_moved=$.throttle(b.throttleTimeShort,db);b.throttled.on_game_pointer_dragged=$.throttle(b.throttleTimeShort,!0,eb);b.domElements.$game.on("mouseleave",fb).on("mouseenter",gb).on("mousemove",
b.throttled.on_game_pointer_moved).on("tap",hb).on("doubletap",ib).on("hold",jb).on("dragstart",kb).on("drag",b.throttled.on_game_pointer_dragged).on("dragend",lb).on("mousewheel DOMMouseScroll",mb).on("contextmenu",nb);K=!0;wa()}function $a(a){ga=a;S(ga)}function cb(a){console.log("GAME: ready");xa=a;T=!0;b.signals.onGameReady.dispatch()}function S(a,c){var d=b.fadeBetweenSections,f=!1,g=function(){typeof b.sectionLast!=="undefined"&&b.sectionLast.remove();a.show();b.section=a;d!==!1&&e.dom_fade({element:b.domElements.$uiBlocker});
U();typeof c!=="undefined"&&c.call()};V(!0);if(typeof b.section!=="undefined")f=!0,b.sectionLast=b.section,b.sectionLast.hide(),d!==!1&&e.dom_fade({element:b.domElements.$uiBlocker,opacity:1});b.section=void 0;typeof startedValue!=="undefined"&&(B=startedValue);typeof a!=="undefined"&&(d!==!1&&f===!0?window.requestTimeout(function(){g()},ob):g())}function pb(){T===!0&&(B===!1?(console.log("GAME: START"),B=!0,b.signals.onGameStarted.dispatch(),S(xa,function(){b.signals.onGameStartedCompleted.dispatch()})):
U())}function qb(){T===!0&&(console.log("GAME: STOP"),B=!1,b.signals.onGameStopped.dispatch(),S(ga,function(){b.signals.onGameStoppedCompleted.dispatch()}))}function V(a,c){x===!1&&(console.log("GAME: PAUSE"),x=!0,b.signals.onGamePaused.dispatch(a,c),ha())}function U(a){if(x===!0&&(z.errorState!==!0||B!==!0))console.log("GAME: RESUME"),x=!1,b.signals.onGameResumed.dispatch(a)}function ya(){var a,c;window.requestAnimationFrame(ya);b.timeLast=b.time;b.time=(new Date).getTime();a=b.time-b.timeLast;c=
Math.round(a/b.timeDeltaExpected*b.timeDeltaModDec)/b.timeDeltaModDec;C(c)!==!0&&(c=1);b.signals.onUpdated.dispatch(a,c);x!==!0&&K===!0&&(TWEEN.update(),e.physics&&e.physics.update(a,c),b.signals.onGameUpdated.dispatch(a,c),ha())}function ha(){K===!0&&(b.cameraControls.update(),b.cameraBG.quaternion.copy(b.camera.quaternion),b.renderer.setViewport(0,0,b.gameWidth,b.gameHeight),b.renderer.clear(),A.render())}function za(a){return a===null?a+"":Object.prototype.toString.call(a).slice(8,-1).toLowerCase()}
function W(a){return Object.prototype.toString.call(a)==="[object Array]"}function C(a){return!isNaN(a)&&isFinite(a)&&typeof a!=="boolean"}function ia(a){return typeof a!=="undefined"&&a.hasOwnProperty("nodeName")&&a.nodeName.toLowerCase()==="img"}function Aa(a){return a==="jpg"||a==="jpeg"||a==="png"||a==="gif"||a==="bmp"?!0:!1}function rb(a){return a&&a.type&&(a.target||a.srcElement)}function ja(a,c,b,f){var g,h,j,k,i,l,q,X,Y,m;if(typeof a!=="undefined"){c=e.type(c)==="object"?c:{};j=Object.getOwnPropertyNames(a);
for(g=0,h=j.length;g<h;g++)if(k=j[g],i=Object.getOwnPropertyDescriptor(a,k),c.hasOwnProperty(k)&&delete c[k],Object.defineProperty(c,k,i),b===!0&&(i=Object.getOwnPropertyDescriptor(c,k),l=i.value,q=za(l),q==="object"||q==="array"))f=f||{sources:[],copies:[]},X=f.sources,Y=f.copies,m=n(X,l),m===-1?(X[X.length]=l,q=Y[Y.length]=q==="object"?{}:[],l===a&&(l[k]=q),i.value=ja(l,q,!0,f)):i.value=Y[m],Object.defineProperty(c,k,i)}return c}function sb(a,c,b){var f,g,e,c=C(c)&&c>0?c:1,b=typeof b==="string"?
b:"";g=(new Date).getTime();for(f=0;f<c;f++)e=a.call();a=(new Date).getTime();console.log(b," > time test ( x",c,"): ",a-g);return e}function o(a){return a?W(a)!==!0?[a]:a:[]}function tb(a,c){return W(a)===!0?a[c||0]:a}function ub(a,c){var b,f,g,e,j=!1,a=o(a),c=o(c);for(b=0,f=c.length;b<f;b++)g=c[b],e=n(a,g),e===-1&&(a.push(g),j=!0);return j}function vb(a,c){var b,f,g,e=!1,a=o(a),c=o(c);for(b=0,f=c.length;b<f;b++)g=c[b],g=n(a,g),g!==-1&&(a.splice(g,1),e=!0);return e}function wb(a){return a[Math.round(Math.random()*
(a.length-1))]}function xb(a){return a.splice(Math.round(Math.random()*(a.length-1)),1)[0]}function n(a,c){for(var b=0,f=a.length;b<f;b++)if(c===a[b])return b;return-1}function yb(a,b){for(var d=a.length-1;d>=0;d--)if(b===a[d])return d;return-1}function zb(a,b){for(var d=[],f=0,g=a.length;f<g;f++)b===a[f]&&d.push(f);return d}function Ab(a,b){for(var d=0,f=a.length;d<f;d++)if(n(b,a[d])!==-1)return d;return-1}function Bb(a,b,d){for(var f=0,g=a.length;f<g;f++)if(d===a[f][b])return f;return-1}function Cb(a,
b,d){for(var f=[],g=0,e=a.length;g<e;g++)d===a[g][b]&&f.push(g);return f}function Db(a,b,d){for(var f=0,g=a.length;f<g;f++)for(var e=0,j=b.length;e<j;e++)if(d[e]===a[f][b[e]])return f;return-1}function Eb(a){var a=a||{},a=a.identifier=a.identifier?a.identifier:0,c=b.pointers[a];if(typeof c==="undefined")c=b.pointers[a]={},c.id=a,c.x=c.lx=b.screenWidth*0.5,c.y=c.ly=b.screenHeight*0.5,c.deltaX=c.deltaY=c.angle=c.distance=c.distanceX=c.distanceY=0,c.direction="none";return c}function L(a){b.timeSinceInteraction=
0;var c=e.get_pointer(a),d,f,g;if(a){d=a.position;W(d)&&d[c.id]&&(d=d[c.id]);if(typeof d==="undefined"){f=document;g=f.body;d={x:c.x,y:c.y};if(typeof a.pageX!=="undefined")d.x=a.pageX;else if(typeof a.clientX!=="undefined")d.x=a.clientX+(f&&f.scrollLeft||g&&g.scrollLeft||0)-(f&&f.clientLeft||g&&g.clientLeft||0);if(typeof a.pageY!=="undefined")d.y=a.pageY;else if(typeof a.clientY!=="undefined")d.y=a.clientY+(f&&f.scrollTop||g&&g.scrollTop||0)-(f&&f.clientTop||g&&g.clientTop||0)}if(c.x!==d.x||c.y!==
d.y)c.x=d.x||c.x,c.y=d.y||c.y,c.deltaX=c.x-c.lx,c.deltaY=c.y-c.ly,c.lx=c.x,c.ly=c.y,c.angle=a.angle||0,c.direction=a.direction||"none"}return c}function fb(a){b.pointerInGame=!1;b.signals.onGamePointerLeft.dispatch(a)}function gb(a){b.pointerInGame=!0;b.signals.onGamePointerEntered.dispatch(a)}function db(a){b.pointerInGame===!0&&(b.signals.onGamePointerMoved.dispatch(a),r(a))}function hb(a){b.signals.onGamePointerTapped.dispatch(a,L(a));r(a)}function ib(a){b.signals.onGamePointerDoubleTapped.dispatch(a,
L(a));r(a)}function jb(a){b.signals.onGamePointerHeld.dispatch(a,L(a));r(a)}function kb(a){b.signals.onGamePointerDragStarted.dispatch(a,e.get_pointer(a));r(a)}function eb(a){b.signals.onGamePointerDragged.dispatch(a,e.get_pointer(a));r(a)}function lb(a){b.signals.onGamePointerDragEnded.dispatch(a,e.get_pointer(a));r(a)}function mb(a){var c=a.originalEvent||a;a.wheelDelta=c.wheelDelta=(c.detail<0||c.wheelDelta>0?1:-1)*b.pointerWheelSpeed;b.signals.onGamePointerWheel.dispatch(a);r(a);a.preventDefault()}
function nb(a){a.preventDefault()}function Fb(a){b.signals.onKeyPressed.dispatch(a);r(a)}function Gb(a){b.signals.onKeyReleased.dispatch(a);r(a)}function r(a){var c,d;typeof a==="undefined"||a.metaKey||a.ctrlKey||a.shiftKey||a.altKey||(d=a.type+"",d==="tap"||d==="doubletap"||d==="hold"||d==="dragstart"||d==="drag"||d==="dragend"||d==="mousemove"?c="pointer":d==="mousewheel"||d==="DOMMouseScroll"?(c="pointer",d="wheel"):(c=((a.which||a.key||a.keyCode)+"").toLowerCase(),c=ua.key(c),d=d.toLowerCase(),
d=d.replace("key","")),b.signals.onGameInput.dispatch(a,c,d))}function Hb(a){b.focused=!1;b.signals.onFocusLost.dispatch(a)}function Ib(a){b.focused=!0;b.signals.onFocusGained.dispatch(a)}function wa(){var a,c;b.screenWidth=$(window).width();b.screenHeight=$(window).height();b.screenViewableWidth=b.domElements.$game.width();b.screenViewableHeight=b.domElements.$game.height();ea&&ea.resize();if(K===!0)b.signals.onWindowResized.dispatch(b.screenWidth,b.screenHeight),a=b.gameWidth=b.screenViewableWidth,
c=b.gameHeight=b.screenViewableHeight,$(b.renderer.domElement).css({top:b.screenOffsetTop,bottom:b.screenOffsetBottom,left:b.screenOffsetLeft,right:b.screenOffsetRight}),b.renderer.setSize(a,c),b.renderTarget.width=a,b.renderTarget.height=c,b.cameraBG.aspect=b.camera.aspect=a/c,b.camera.updateProjectionMatrix(),b.cameraBG.updateProjectionMatrix(),A.reset(b.renderTarget),ha()}function Ba(a,b,d){V(!0);z.errorState!==!0&&z.generate(a,b,d);throw a+" at "+d+" in "+b;}function Ca(a){a=Da(a);return!!Modernizr.prefixed(a)}
function Da(a){var b=a.split("-"),d=b.length;if(d==1)return b[0];for(var a=a.charAt(0)=="-"?b[0].charAt(0).toUpperCase()+b[0].substring(1):b[0],f=1;f<d;f++)a+=b[f].charAt(0).toUpperCase()+b[f].substring(1);return a}function Jb(a){return a.toLowerCase().replace(/\b[a-z]/g,function(a){return a.toUpperCase()})}function Kb(a){return a instanceof $?a.get(0):a}function y(a,c){if(b.supports.pointerEvents)c===!0?a.addClass("ignore-pointer-temporary"):a.removeClass("ignore-pointer-temporary");else if(c===
!0)a.on("tap.pointer doubletap.pointer hold.pointer dragstart.pointer drag.pointer, dragend.pointer",function(b){b.preventDefault();b.stopPropagation();a.stop(!0).addClass("invisible");$(document.elementFromPoint(b.clientX,b.clientY)).trigger(b);a.stop(!0).removeClass("invisible");return!1});else a.off(".pointer")}function Ea(a,b,d,f){var g=function(){typeof b==="function"&&b.call(d,f)};ia(f)!==!0&&(f=new Image);f.crossOrigin="";f.src=a;f.complete?g():f.onload=g;return f}function Lb(a){var c,d,f,
g,e,a=a||{};c=$(a.element);d=C(a.duration)?a.duration:b.domFadeDuration;f=C(a.opacity)?a.opacity:0;g=typeof a.easing==="string"?a.easing:b.domFadeEasing;e=a.callback;c.each(function(){var b=$(this),c,i,l;l=b.is(".hiding, .hidden, .invisible");i=b.is(".collapsed");b.stop(!0).removeClass("invisible hiding hidden collapsed");c=b.find("a, button").add(b);(l===!0||i===!0||a.initHidden===!0)&&b.fadeTo(0,0).css("height","");f===0?(b.addClass("hiding").trigger("hide"),y(c,!0)):(y(c,!1),b.trigger("show"));
b.animate({opacity:f},{duration:d,easing:g,complete:function(){b.removeClass("hiding");f===0?(b.addClass("hidden").css("opacity","").trigger("hidden"),y(c,!1)):(b.trigger("shown"),f===1&&b.css("opacity",""));typeof e==="function"&&e()}})})}function Mb(a){var c,d,f,e,h,a=a||{};c=$(a.element);f=typeof a.show==="boolean"?a.show:!1;d=C(a.duration)?a.duration:b.domCollapseDuration;e=typeof a.easing==="string"?a.easing:b.domCollapseEasing;h=a.callback;c.each(function(){var b=$(this),c,i,l,q=0,m=function(){f===
!0?b.css("height","").trigger("shown"):(b.addClass("hidden").trigger("hidden"),y(c,!1));typeof h==="function"&&h()};l=b.is(".hiding, .hidden, .invisible");i=b.is(".collapsed");if(i!==!0&&(l===!0||a.initHidden===!0))b.css("height",0).css("opacity",""),i=!0;i===f&&(b.stop(!0).removeClass("invisible hiding hidden collapsed"),c=b.find("a, button").add(b),f===!0?(b.placeholdme().appendTo("body"),i=b.height(),b.css("height",""),q=b.height(),b.css("height",i),b.placeholdme("revert"),y(c,!1),b.trigger("show")):
(y(c,!0),b.addClass("collapsed").trigger("hide")),b.animate({height:q},{duration:d,easing:e,complete:m}))})}function Fa(){v=[];M=[];b.signals.onWorkerReset.dispatch()}function Ga(a){typeof a==="string"&&a.length>0&&v.hasOwnProperty(a)!==!0&&(ca++,v.push(a),b.signals.onWorkerTaskStarted.dispatch(a))}function Ha(a){var c=n(v,a);c!==-1&&(v.splice(c,1),M.push(a),b.signals.onWorkerTaskCompleted.dispatch(a),v.length===0&&b.signals.onWorkerTasksCompleted.dispatch())}function Ia(a,b,d,f){var e,h,j,k,i,l=
!0;if(typeof a!=="undefined"){if(typeof a==="string"||a.hasOwnProperty("length")===!1)a=[a];a=a.slice(0);if(typeof d!=="string"||w.hasOwnProperty(d))d=N;N++;for(e=0,h=a.length;e<h;e++)j=a[e],j=m(j),k=n(t,j),i=n(u,j),k===-1&&i==-1&&(t.push(j),P.push(d),Ga(j),newLocations=!0),i===-1&&(l=!1);H=u.concat(t);w[d]=a;if(typeof b==="undefined")b=[];else if(typeof b==="function"||b.hasOwnProperty("length")===!1)b=[b];G[d]=b;typeof f!=="string"&&(f=J[Math.max(0,Math.min(J.length-1,Math.round(Math.random()*J.length)-
1))]);O[d]=f;F[d]=[];s.push(d);l===!0?Ja(d):Ka()}}function Ka(){var a,c,d,f,e;if(E===!1&&s.length>0){E=!0;I=s[0];d=w[I].slice(0);for(a=0,c=d.length;a<c;a+=1)f=d[a],e=m(f),n(u,e)!==-1?ka(f):n(Q,e)===-1&&(Q.push(e),Nb(f))}else I=void 0,b.signals.onLoadAllCompleted.dispatch()}function Nb(a){var b,d,f,e,h=function(){ka(a,e)},j=function(b){ka(a,b)};typeof a!=="undefined"&&(f=a.type||da,b=m(a),d=la(b),d===""&&(b=ma(b)),f==="image"||Aa(d)?(e=Ea(b,function(a){e=a;h()}),na(b,{data:e})):f==="model"||f==="model_ascii"?
(typeof R==="undefined"&&(R=new THREE.JSONLoader(!0)),R.load(b,j)):$LAB.script(b).wait(h))}function ka(a,c){var d,f,e,h,j,k,i;d=m(a);Ha(d);na(d,{data:c});oa(d);typeof b!=="undefined"&&b.signals.onLoadItemCompleted.dispatch(d);for(d=0,f=s.length;d<f;d++)e=s[d],h=w[e],k=n(h,a),k!==-1&&(j=F[e],h.splice(k,k!==-1?1:0),j.push(a),h.length===0&&(i=i||[],i.push(e)));if(typeof i!=="undefined")for(d=0,f=i.length;d<f;d++)Ja(i[d])}function Ja(a){var c,d,f,e;c=n(s,a);c!==-1&&s.splice(c,1);f=G[a];for(c=0,d=f.length;c<
d;c++)e=f[c],typeof e!=="undefined"&&e.call(this);typeof b!=="undefined"&&b.signals.onLoadListCompleted.dispatch(a);delete w[a];delete G[a];delete O[a];delete F[a];E=!1;Ka()}function oa(a){var b,d,e,g,h=!1,a=o(a);for(b=0,d=a.length;b<d;b++)e=a[b],e=m(e),g=n(t,e),g!==-1&&(P.splice(g,1),t.splice(g,1)),g=n(u,e),g===-1&&(u.push(e),h=!0);h===!0&&(H=u.concat(t))}function pa(a,b){var d;d=m(a);return n(b,d)!==-1?!0:!1}function Ob(a){return pa(a,H)}function Pb(a){return pa(a,u)}function Qb(a){return pa(a,
t)}function m(a){return a.path||a}function la(a){var b,d="",a=m(a);b=a.lastIndexOf(".");b!==-1&&(d=a.substr(b+1).toLowerCase());return d}function ma(a){a=qa(a);return a=a.replace(/\./g,"")+".js"}function qa(a){var b,a=m(a);b=a.lastIndexOf(".");b!==-1&&(a=a.substr(0,b));return a}function ra(a){a=m(a);return la(a)===""?ma(a):qa(a)}function La(a){var b,d,e;d=a.split(/[\\\/]/);for(a=0,b=d.length;a<b;a++){e=d[a];e=e.replace(/[^\w\.-]+/g,"");if(e===""){Ba("Invalid asset cascade","Main","N/A");return}d[a]=
e}return d}function D(a,b){var d,f,g,h,j,k;g=e;d=m(a);f=La(d);for(j=0,k=f.length;j<k;j++)if(h=f[j],g=g[h],typeof g==="undefined")break;b=b||1;return typeof g==="undefined"&&b===1?D(ra(d),b+1):g}function Ma(a,b){var d,f,g,h,j,k;if(b instanceof p){h=f=e;d=m(a);d=La(d);for(j=0,k=d.length;j<k;j++)f=h,g=d[j],h=f[g]=f[g]||{};h instanceof p&&h.is_empty()===!1?b.is_empty()===!1&&h.merge_asset_self(b):f[g]=h=b}return h}function Rb(a){a=D(a);return a instanceof p?a.data:a}function na(a,b){var d;d=D(a);if(d instanceof
p!==!0||b&&typeof b.data!=="undefined"&&b.data!==d.data)d=new p(a,b);return d=d.data}function Na(a,c){c=c||D(a);if(c instanceof p)c.ready=!0,c.wait=!1,typeof b.signals!=="undefined"&&typeof b.signals.onAssetReady!=="undefined"&&b.signals.onAssetReady.dispatch(a)}function sa(a,c,d,e){var g,h,j=[],k=[],i=[],l=!1,a=o(a),c=o(c);g=function(c,d){var e;e=n(k,c);e!==-1?(k.splice(e,1),i.push(c),k.length===0&&i.length===a.length&&(l===!0&&(b.signals.onAssetReady.remove(g),l=!1),h())):d!==!0&&g(ra(c),!0)};h=
function(){var a,b,d;for(a=0,b=c.length;a<b;a++)d=c[a],d.apply(this,j);if(e instanceof p&&e.readyAutoUpdate===!0)e.on_ready()};Ia(a,function(){var c,e,f,i;for(c=0,e=a.length;c<e;c++)f=a[c],i=m(f),f=D(f),f instanceof p&&j.push(f.data),d===!0&&(k.push(i),f instanceof p&&f.ready===!0?g(i):l===!1&&(l=!0,b.signals.onAssetReady.add(g)));(d!==!0||a.length===0)&&h()})}function p(a,b){var d=this,b=b||{};b.path=a;d.merge_asset_self(b,!0);if(typeof d.path!=="undefined"){d=Ma(d.path,d);if(d===this&&this.readyAutoUpdate===
!0&&(this.requirements.length===0||this.wait!==!0))this.on_ready();this.requirements.length>0&&sa(this.requirements,this.callbacksOnReqs,this.wait,this)}return d}window.console=window.console||{info:function(){},log:function(){},debug:function(){},warn:function(){},error:function(){}};var b=e.shared=e.shared||{};b.domElements=b.domElements||{};b.supports=b.supports||{};b.throttled={};b.spawns={};b.pointers=[];b.originLink=window.location.pathname.toString();b.pathToIcons="img/";b.pathToAssets="asset/";
b.frameRateMax=60;b.frameRateMin=20;b.time=(new Date).getTime();b.timeLast=b.time;b.timeDeltaExpected=1E3/60;b.timeDeltaModDec=Math.pow(10,2);b.pointerWheelSpeed=120;b.pointerHoldPositionShift=10;b.pointerInGame=!0;b.throttleTimeShort=b.timeDeltaExpected*3;b.throttleTimeMedium=100;b.throttleTimeLong=250;b.throttleTimeLong=250;b.focused=!0;b.errorString="error";b.errorTypeGeneral="General";b.errorTypes=[b.errorTypeGeneral,"WebGLBrowser","WebGLComputer"];b.errorTypesOnlyOnce=["WebGLBrowser","WebGLComputer"];
b.fadeBetweenSections=!1;b.domFadeDuration=500;b.domCollapseDuration=500;b.domFadeEasing="easeInOutCubic";b.domCollapseEasing="easeInOutCubic";b.screenWidth=0;b.screenHeight=0;b.screenViewableWidth=0;b.screenViewableHeight=0;b.screenOffsetTop=0;b.screenOffsetBottom=0;b.screenOffsetLeft=0;b.screenOffsetRight=0;E=void 0;N=void 0;s=void 0;w=void 0;F=void 0;O=void 0;G=void 0;t=void 0;P=void 0;Q=void 0;u=void 0;H=void 0;I=void 0;da=void 0;J=void 0;R=void 0;ca=void 0;v=void 0;M=void 0;var z,fa,va,ua,ea,
ga,xa,A,K=!1,T=!1,B=!1,x=!1,Z=!1,ob=500,Oa=["js/lib/RequestAnimationFrame.js","js/lib/RequestInterval.js","js/lib/RequestTimeout.js","js/lib/signals.min.js","js/lib/jquery-1.8.2.min.js"],Pa=["js/lib/hammer.custom.js","js/lib/bootstrap.min.js","js/lib/jquery.easing-1.3.min.js","js/lib/jquery.throttle-debounce.custom.min.js","js/lib/jquery.placeholdme.js"],Sb=["js/kaiopua/utils/ErrorHandler.js","js/kaiopua/ui/UI.js","js/kaiopua/utils/KeyHelper.js"],Ra=["js/lib/three/three.min.js","js/lib/Tween.custom.min.js"],
Ta="js/lib/three/ThreeOctree.min.js,js/lib/three/postprocessing/ShaderExtras.js,js/lib/three/postprocessing/EffectComposer.js,js/lib/three/postprocessing/RenderPass.js,js/lib/three/postprocessing/MaskPass.js,js/lib/three/postprocessing/ShaderPass.js".split(","),Wa=["js/kaiopua/core/Scene.js","js/kaiopua/core/CameraControls.js"],Za=["js/kaiopua/sections/Launcher.js"],bb=["js/kaiopua/sections/Intro.js"];$LAB.script(Oa).wait().script(Pa).wait(function(){b.domElements.$game=$("#game");b.supports.pointerEvents=
Ca("pointer-events");b.signals={onFocusLost:new signals.Signal,onFocusGained:new signals.Signal,onKeyPressed:new signals.Signal,onKeyReleased:new signals.Signal,onGameInput:new signals.Signal,onWindowResized:new signals.Signal,onUpdated:new signals.Signal,onWorkerReset:new signals.Signal,onWorkerTaskStarted:new signals.Signal,onWorkerTaskCompleted:new signals.Signal,onWorkerTasksCompleted:new signals.Signal,onLoadItemCompleted:new signals.Signal,onLoadListCompleted:new signals.Signal,onLoadAllCompleted:new signals.Signal,
onAssetReady:new signals.Signal,onGameReady:new signals.Signal,onGamePaused:new signals.Signal,onGameResumed:new signals.Signal,onGameUpdated:new signals.Signal,onGameStarted:new signals.Signal,onGameStartedCompleted:new signals.Signal,onGameStopped:new signals.Signal,onGameStoppedCompleted:new signals.Signal,onGamePointerLeft:new signals.Signal,onGamePointerEntered:new signals.Signal,onGamePointerMoved:new signals.Signal,onGamePointerTapped:new signals.Signal,onGamePointerDoubleTapped:new signals.Signal,
onGamePointerHeld:new signals.Signal,onGamePointerDragStarted:new signals.Signal,onGamePointerDragged:new signals.Signal,onGamePointerDragEnded:new signals.Signal,onGamePointerWheel:new signals.Signal};$(document).on("keydown",Fb).on("keyup",Gb);b.throttled.reposition_pointer=$.throttle(b.throttleTimeShort,L);b.throttled.on_window_resized=$.throttle(b.throttleTimeLong,wa);$(window).on("mousemove",b.throttled.reposition_pointer).on("blur",Hb).on("focus",Ib).on("resize",b.throttled.on_window_resized);
window.onerror=Ba;b.signals.onFocusLost.add(function(){x!==!0&&(Z=!0);V(!0)});b.signals.onFocusGained.add(function(){Z===!0&&(Z=!1,U(!0))});E=!1;N=0;s=[];w={};F={};O={};G={};t=[];P=[];Q=[];u=[];H=[];I="";da="script";J=[];oa(Oa);oa(Pa);ca=0;v=[];M=[];Fa();e.type=za;e.is_number=C;e.is_array=W;e.is_image=ia;e.is_image_ext=Aa;e.is_event=rb;e.extend=ja;e.time_test=sb;e.to_array=o;e.ensure_not_array=tb;e.array_cautious_add=ub;e.array_cautious_remove=vb;e.array_random_value=wb;e.array_random_value_remove=
xb;e.index_of_value=n;e.last_index_of_value=yb;e.indices_of_value=zb;e.index_of_values=Ab;e.index_of_property=Bb;e.indices_of_property=Cb;e.index_of_properties=Db;e.css_property_supported=Ca;e.str_to_camel=Da;e.str_to_title=Jb;e.dom_extract=Kb;e.dom_generate_image=Ea;e.dom_ignore_pointer=y;e.dom_fade=Lb;e.dom_collapse=Mb;e.get_pointer=Eb;e.reposition_pointer=L;e.worker_reset=Fa;e.worker_task_start=Ga;e.worker_task_complete=Ha;e.load=Ia;e.get_is_loaded=Pb;e.get_is_loading=Qb;e.get_is_loading_or_loaded=
Ob;e.get_asset_path=m;e.get_ext=la;e.add_default_ext=ma;e.remove_ext=qa;e.get_alt_path=ra;e.asset_register=na;e.asset_require=sa;e.asset_ready=Na;e.set_asset=Ma;e.get_asset=D;e.get_asset_data=Rb;e.set_section=S;e.start=pb;e.stop=qb;e.resume=U;e.pause=V;Object.defineProperty(e,"paused",{get:function(){return x}});Object.defineProperty(e,"started",{get:function(){return B}});Object.defineProperty(e,"setup",{get:function(){return K}});Object.defineProperty(e,"ready",{get:function(){return T}});Object.defineProperty(e,
"focusLost",{get:function(){return Z}});$(window).trigger("resize");ya();sa(Sb,Qa,!0)});p.prototype={};p.prototype={constructor:p,merge_asset_self:function(a,b){if(typeof a!=="undefined"){this.path=a.path;this.merge_asset_data_self(a);if(typeof this.wait!=="boolean"||this.wait===!1)this.wait=a.wait===!0?a.wait:!1;if(this.ready!==!0)this.ready=!1;if(typeof this.readyAutoUpdate!=="boolean")this.readyAutoUpdate=a.hasOwnProperty("readyAutoUpdate")?a.readyAutoUpdate:!0;this.requirements=o(this.requirements);
this.callbacksOnReqs=o(this.callbacksOnReqs);if(b===!0)this.requirements=this.requirements.concat(o(a.requirements)),this.callbacksOnReqs=this.callbacksOnReqs.concat(o(a.callbacksOnReqs))}},merge_asset_data_self:function(a){a=a.data;if(typeof a!=="undefined")typeof this.data==="undefined"||ia(a)?this.data=a:ja(a,this.data)},is_empty:function(){var a=!0;if(typeof this.data!=="undefined"||this.ready===!1&&this.requirements.length>0)a=!1;return a},on_ready:function(){console.log("[ KAIOPUA ] Module / Asset Ready: "+
this.path);Na(this.path,this)}};return e}(KAIOPUA||{});
